package main

import (
	"encoding/json"
	"fmt"

	"github.com/hyperledger/fabric-contract-api-go/contractapi"
)

//Hl7OrcFormat ..
type Hl7OrcFormat struct {
	Class                                             string `json:"$class"`
	MSHORC                                            string `json:"MSH_ORC" validate:"required"`
	ORCKEY                                            string `json:"ORCKEY"`
	MSHKEY                                            string `json:"MSHKEY" validate:"required"`
	OrderControl                                      string `json:"OrderControl"`
	PlacerOrderNumberEntityIdentifier                 string `json:"PlacerOrderNumberEntityIdentifier"`
	PlacerOrderNumberNamespaceID                      string `json:"PlacerOrderNumberNamespaceID"`
	PlacerOrderNumberUniversalID                      string `json:"PlacerOrderNumberUniversalID"`
	PlacerOrderNumberUniversalIDtype                  string `json:"PlacerOrderNumberUniversalIDtype"`
	FillerOrderNumberEntityIdentifier                 string `json:"FillerOrderNumberEntityIdentifier"`
	FillerOrderNumberNamespaceID                      string `json:"FillerOrderNumberNamespaceID"`
	FillerOrderNumberUniversalID                      string `json:"FillerOrderNumberUniversalID"`
	FillerOrderNumberUniversalIDtype                  string `json:"FillerOrderNumberUniversalIDtype"`
	PlacerOrderNumber1EntityIdentifier                string `json:"PlacerOrderNumber1EntityIdentifier"`
	PlacerOrderNumber1NamespaceID                     string `json:"PlacerOrderNumber1NamespaceID"`
	PlacerOrderNumber1UniversalID                     string `json:"PlacerOrderNumber1UniversalID"`
	PlacerOrderNumber1UniversalIDtype                 string `json:"PlacerOrderNumber1UniversalIDtype"`
	OrderStatus                                       string `json:"OrderStatus"`
	ResponseFlag                                      string `json:"ResponseFlag"`
	PNPlacerAssignedEntityIdentifier                  string `json:"PNPlacerAssignedEntityIdentifier"`
	PNPlacerAssignedNamespaceID                       string `json:"PNPlacerAssignedNamespaceID"`
	PNPlacerAssignedUniversalID                       string `json:"PNPlacerAssignedUniversalID"`
	PNPlacerAssignedUniversalIDType                   string `json:"PNPlacerAssignedUniversalIDType"`
	PNFillerAssignedEntityIdentifier                  string `json:"PNFillerAssignedEntityIdentifier"`
	PNFillerAssignedNamespaceID                       string `json:"PNFillerAssignedNamespaceID"`
	PNFillerAssignedUniversalID                       string `json:"PNFillerAssignedUniversalID"`
	PNFillerAssignedUniversalIDType                   string `json:"PNFillerAssignedUniversalIDType"`
	TransactionDTYear                                 string `json:"TransactionDTYear"`
	TransactionDTMonth                                string `json:"TransactionDTMonth"`
	TransactionDTDay                                  string `json:"TransactionDTDay"`
	TransactionDTHours                                string `json:"TransactionDTHours"`
	TransactionDTMinutes                              string `json:"TransactionDTMinutes"`
	TransactionDTSeconds                              string `json:"TransactionDTSeconds"`
	TransactionDTMillis                               string `json:"TransactionDTMillis"`
	TransactionDTGmtOffset                            string `json:"TransactionDTGmtOffset"`
	TransactionDTPrecision                            string `json:"TransactionDTPrecision"`
	EntererLocationPointOfCare                        string `json:"EntererLocationPointOfCare"`
	EntererLocationRoom                               string `json:"EntererLocationRoom"`
	EntererLocationBed                                string `json:"EntererLocationBed"`
	EntererLocationNamespaceID                        string `json:"EntererLocationNamespaceID"`
	EntererLocationUniversalID                        string `json:"EntererLocationUniversalID"`
	EntererLocationUniversalIDType                    string `json:"EntererLocationUniversalIDType"`
	EntererLocationlocationStatus                     string `json:"EntererLocationlocationStatus"`
	EntererLocationPersonlocationType                 string `json:"EntererLocationPersonlocationType"`
	EntererLocationBuilding                           string `json:"EntererLocationBuilding"`
	EntererLocationFloor                              string `json:"EntererLocationFloor"`
	EntererLocationLocationDescription                string `json:"EntererLocationLocationDescription"`
	OrderEffectiveDTYear                              string `json:"OrderEffectiveDTYear"`
	OrderEffectiveDTMonth                             string `json:"OrderEffectiveDTMonth"`
	OrderEffectiveDTDay                               string `json:"OrderEffectiveDTDay"`
	OrderEffectiveDTHours                             string `json:"OrderEffectiveDTHours"`
	OrderEffectiveDTMinutes                           string `json:"OrderEffectiveDTMinutes"`
	OrderEffectiveDTSeconds                           string `json:"OrderEffectiveDTSeconds"`
	OrderEffectiveDTMillis                            string `json:"OrderEffectiveDTMillis"`
	OrderEffectiveDTGmtOffset                         string `json:"OrderEffectiveDTGmtOffset"`
	OrderEffectiveDTPrecision                         string `json:"OrderEffectiveDTPrecision"`
	OrderControlCdReasonIdentifier                    string `json:"OrderControlCdReasonIdentifier"`
	OrderControlCdReasonText                          string `json:"OrderControlCdReasonText"`
	OrderControlCdReasonNameOfCodingSystem            string `json:"OrderControlCdReasonNameOfCodingSystem"`
	OrderControlCdReasonAlternateIdentifier           string `json:"OrderControlCdReasonAlternateIdentifier"`
	OrderControlCdReasonAlternateText                 string `json:"OrderControlCdReasonAlternateText"`
	OrderControlCdReasonAlternateCodingSystem         string `json:"OrderControlCdReasonAlternateCodingSystem"`
	EnteringOrganizationIdentifier                    string `json:"EnteringOrganizationIdentifier"`
	EnteringOrganizationText                          string `json:"EnteringOrganizationText"`
	EnteringOrganizationNameOfCodingSystem            string `json:"EnteringOrganizationNameOfCodingSystem"`
	EnteringOrganizationAlternateIdentifier           string `json:"EnteringOrganizationAlternateIdentifier"`
	EnteringOrganizationAlternateText                 string `json:"EnteringOrganizationAlternateText"`
	EnteringOrganizationAlternateCodingSystem         string `json:"EnteringOrganizationAlternateCodingSystem"`
	EnteringDeviceIdentifier                          string `json:"EnteringDeviceIdentifier"`
	EnteringDeviceText                                string `json:"EnteringDeviceText"`
	EnteringDeviceNameOfCodingSystem                  string `json:"EnteringDeviceNameOfCodingSystem"`
	EnteringDeviceAlternateIdentifier                 string `json:"EnteringDeviceAlternateIdentifier"`
	EnteringDeviceAlternateText                       string `json:"EnteringDeviceAlternateText"`
	EnteringDeviceAlternateCodingSystem               string `json:"EnteringDeviceAlternateCodingSystem"`
	AdvancedBeneficiaryIdentifier                     string `json:"AdvancedBeneficiaryIdentifier"`
	AdvancedBeneficiaryText                           string `json:"AdvancedBeneficiaryText"`
	AdvancedBeneficiaryNameOfCodingSystem             string `json:"AdvancedBeneficiaryNameOfCodingSystem"`
	AdvancedBeneficiaryAlternateIdentifier            string `json:"AdvancedBeneficiaryAlternateIdentifier"`
	AdvancedBeneficiaryAlternateText                  string `json:"AdvancedBeneficiaryAlternateText"`
	OrderStatusModifierIdentifier                     string `json:"OrderStatusModifierIdentifier"`
	OrderStatusModifierText                           string `json:"OrderStatusModifierText"`
	OrderStatusModifierNameOfCodingSystem             string `json:"OrderStatusModifierNameOfCodingSystem"`
	OrderStatusModifierAlternateIdentifier            string `json:"OrderStatusModifierAlternateIdentifier"`
	OrderStatusModifierAlternateText                  string `json:"OrderStatusModifierAlternateText"`
	OrderStatusModifierAlternateCodingSystem          string `json:"OrderStatusModifierAlternateCodingSystem"`
	OrderStatusModifierCodingSystemVersionID          string `json:"OrderStatusModifierCodingSystemVersionId"`
	OrderStatusModifierAlternatecodingsystemversionID string `json:"OrderStatusModifierAlternatecodingsystemversionID"`
	OrderStatusModifieroriginaltext                   string `json:"OrderStatusModifieroriginaltext"`
	OverrideReasonIdentifier                          string `json:"OverrideReasonIdentifier"`
	OverrideReasonText                                string `json:"OverrideReasonText"`
	OverrideReasonNameOfCodingSystem                  string `json:"OverrideReasonNameOfCodingSystem"`
	OverrideReasonAlternateIdentifier                 string `json:"OverrideReasonAlternateIdentifier"`
	OverrideReasonAlternateText                       string `json:"OverrideReasonAlternateText"`
	OverrideReasonAlternateCodingSystem               string `json:"OverrideReasonAlternateCodingSystem"`
	OverrideReasonCodingSystemVersionID               string `json:"OverrideReasonCodingSystemVersionId"`
	OverrideReasonAlternatecodingsystemversionID      string `json:"OverrideReasonAlternatecodingsystemversionID"`
	OverrideReasonoriginaltext                        string `json:"OverrideReasonoriginaltext"`
	FillerExpectedAvailabilityDTYear                  string `json:"FillerExpectedAvailabilityDTYear"`
	FillerExpectedAvailabilityDTMonth                 string `json:"FillerExpectedAvailabilityDTMonth"`
	FillerExpectedAvailabilityDTDay                   string `json:"FillerExpectedAvailabilityDTDay"`
	FillerExpectedAvailabilityDTHours                 string `json:"FillerExpectedAvailabilityDTHours"`
	FillerExpectedAvailabilityDTMinutes               string `json:"FillerExpectedAvailabilityDTMinutes"`
	FillerExpectedAvailabilityDTSeconds               string `json:"FillerExpectedAvailabilityDTSeconds"`
	FillerExpectedAvailabilityDTMillis                string `json:"FillerExpectedAvailabilityDTMillis"`
	FillerExpectedAvailabilityDTGmtOffset             string `json:"FillerExpectedAvailabilityDTGmtOffset"`
	FillerExpectedAvailabilityDTPrecision             string `json:"FillerExpectedAvailabilityDTPrecision"`
	ConfidentialityCodeIdentifier                     string `json:"ConfidentialityCodeIdentifier"`
	ConfidentialityCodeText                           string `json:"ConfidentialityCodeText"`
	ConfidentialityCodeNameOfCodingSystem             string `json:"ConfidentialityCodeNameOfCodingSystem"`
	ConfidentialityCodeAlternateIdentifier            string `json:"ConfidentialityCodeAlternateIdentifier"`
	ConfidentialityCodeAlternateText                  string `json:"ConfidentialityCodeAlternateText"`
	ConfidentialityCodeAlternateCodingSystem          string `json:"ConfidentialityCodeAlternateCodingSystem"`
	ConfidentialityCodeCodingSystemVersionID          string `json:"ConfidentialityCodeCodingSystemVersionId"`
	ConfidentialityCodeAlternatecodingsystemversionID string `json:"ConfidentialityCodeAlternatecodingsystemversionID"`
	ConfidentialityCodeoriginaltext                   string `json:"ConfidentialityCodeoriginaltext"`
	OrderTypeIdentifier                               string `json:"OrderTypeIdentifier"`
	OrderTypeText                                     string `json:"OrderTypeText"`
	OrderTypeNameOfCodingSystem                       string `json:"OrderTypeNameOfCodingSystem"`
	OrderTypeAlternateIdentifier                      string `json:"OrderTypeAlternateIdentifier"`
	OrderTypeAlternateText                            string `json:"OrderTypeAlternateText"`
	OrderTypeAlternateCodingSystem                    string `json:"OrderTypeAlternateCodingSystem"`
	OrderTypeCodingSystemVersionID                    string `json:"OrderTypeCodingSystemVersionId"`
	OrderTypeAlternatecodingsystemversionID           string `json:"OrderTypeAlternatecodingsystemversionID"`
	OrderTypeoriginaltext                             string `json:"OrderTypeoriginaltext"`
	EntererAuthModeIdentifier                         string `json:"EntererAuthModeIdentifier"`
	EntererAuthModeText                               string `json:"EntererAuthModeText"`
	EntererAuthModeNameOfCodingSystem                 string `json:"EntererAuthModeNameOfCodingSystem"`
	EntererAuthModeAlternateIdentifier                string `json:"EntererAuthModeAlternateIdentifier"`
	EntererAuthModeAlternateText                      string `json:"EntererAuthModeAlternateText"`
	EntererAuthModeAlternateCodingSystem              string `json:"EntererAuthModeAlternateCodingSystem"`
	EntererAuthModeCodingSystemVersionID              string `json:"EntererAuthModeCodingSystemVersionId"`
	EntererAuthModeAlternatecodingsystemversionID     string `json:"EntererAuthModeAlternatecodingsystemversionID"`
	EntererAuthModeoriginaltext                       string `json:"EntererAuthModeoriginaltext"`
	Parent                                            string `json:"Parent"`
	AdvancedBeneficiaryAlternateCodingSystem          string `json:"AdvancedBeneficiaryAlternateCodingSystem"`
	TransactionDTTime                                 string `json:"TransactionDTTime"`
	OrderEffectiveDTTime                              string `json:"OrderEffectiveDTTime"`
	ORCActionBy                                       struct {
		Class                                              string `json:"$class"`
		ActionByIDNumber                                   string `json:"ActionByIDNumber"`
		ActionByFamilyName                                 string `json:"ActionByFamilyName"`
		ActionByFNPrefix                                   string `json:"ActionByFNPrefix"`
		ActionByFNOwnFamilyName                            string `json:"ActionByFNOwnFamilyName"`
		ActionByFNPrefixFromPartnerSpouse                  string `json:"ActionByFNPrefixFromPartnerSpouse"`
		ActionByFNFrompartnerspouse                        string `json:"ActionByFNFrompartnerspouse"`
		ActionByGivenName                                  string `json:"ActionByGivenName"`
		ActionByMiddleinitialorname                        string `json:"ActionByMiddleinitialorname"`
		ActionBySuffix                                     string `json:"ActionBySuffix"`
		ActionByPrefix                                     string `json:"ActionByPrefix"`
		ActionByDegree                                     string `json:"ActionByDegree"`
		ActionBySourcetable                                string `json:"ActionBySourcetable"`
		ActionByAANamespaceID                              string `json:"ActionByAANamespaceID"`
		ActionByAAUniversalID                              string `json:"ActionByAAUniversalID"`
		ActionByAAUniversalIDtype                          string `json:"ActionByAAUniversalIDtype"`
		ActionByNametypecode                               string `json:"ActionByNametypecode"`
		ActionByIdentifiercheckdigit                       string `json:"ActionByIdentifiercheckdigit"`
		ActionByCodeidentifyingthecheckdigitschemeemployed string `json:"ActionByCodeidentifyingthecheckdigitschemeemployed"`
		ActionByIdentifiertypecode                         string `json:"ActionByIdentifiertypecode"`
		ActionByAFNamespaceID                              string `json:"ActionByAFNamespaceID"`
		ActionByAFUniversalID                              string `json:"ActionByAFUniversalID"`
		ActionByAFUniversalIDtype                          string `json:"ActionByAFUniversalIDtype"`
		ActionByNamerepresentationcode                     string `json:"ActionByNamerepresentationcode"`
		ActionByNCIdentifier                               string `json:"ActionByNCIdentifier"`
		ActionByNCText                                     string `json:"ActionByNCText"`
		ActionByNCNameOfCodingSystem                       string `json:"ActionByNCNameOfCodingSystem"`
		ActionByNCAlternateIdentifier                      string `json:"ActionByNCAlternateIdentifier"`
		ActionByNCAlternateText                            string `json:"ActionByNCAlternateText"`
		ActionByNCAlternateCodingSystem                    string `json:"ActionByNCAlternateCodingSystem"`
		ActionByNVStartDateYear                            string `json:"ActionByNVStartDateYear"`
		ActionByNVStartDateMonth                           string `json:"ActionByNVStartDateMonth"`
		ActionByNVStartDateDay                             string `json:"ActionByNVStartDateDay"`
		ActionByNVStartDateHours                           string `json:"ActionByNVStartDateHours"`
		ActionByNVStartDateMinutes                         string `json:"ActionByNVStartDateMinutes"`
		ActionByNVStartDateSeconds                         string `json:"ActionByNVStartDateSeconds"`
		ActionByNVStartDateMillis                          string `json:"ActionByNVStartDateMillis"`
		ActionByNVStartDateGmtOffset                       string `json:"ActionByNVStartDateGmtOffset"`
		ActionByNVStartDatePrecision                       string `json:"ActionByNVStartDatePrecision"`
		ActionByNVEndDateYear                              string `json:"ActionByNVEndDateYear"`
		ActionByNVEndDateMonth                             string `json:"ActionByNVEndDateMonth"`
		ActionByNVEndDateDay                               string `json:"ActionByNVEndDateDay"`
		ActionByNVEndDateHours                             string `json:"ActionByNVEndDateHours"`
		ActionByNVEndDateMinutes                           string `json:"ActionByNVEndDateMinutes"`
		ActionByNVEndDateSeconds                           string `json:"ActionByNVEndDateSeconds"`
		ActionByNVEndDateMillis                            string `json:"ActionByNVEndDateMillis"`
		ActionByNVEndDateGmtOffset                         string `json:"ActionByNVEndDateGmtOffset"`
		ActionByNVEndDatePrecision                         string `json:"ActionByNVEndDatePrecision"`
		ActionByNameassemblyorder                          string `json:"ActionByNameassemblyorder"`
		ActionByEffDTYear                                  string `json:"ActionByEffDTYear"`
		ActionByEffDTMonth                                 string `json:"ActionByEffDTMonth"`
		ActionByEffDTDay                                   string `json:"ActionByEffDTDay"`
		ActionByEffDTHours                                 string `json:"ActionByEffDTHours"`
		ActionByEffDTMinutes                               string `json:"ActionByEffDTMinutes"`
		ActionByEffDTSeconds                               string `json:"ActionByEffDTSeconds"`
		ActionByEffDTMillis                                string `json:"ActionByEffDTMillis"`
		ActionByEffDTGmtOffset                             string `json:"ActionByEffDTGmtOffset"`
		ActionByEffDTPrecision                             string `json:"ActionByEffDTPrecision"`
		ActionByExpDTYear                                  string `json:"ActionByExpDTYear"`
		ActionByExpDTMonth                                 string `json:"ActionByExpDTMonth"`
		ActionByExpDTDay                                   string `json:"ActionByExpDTDay"`
		ActionByExpDTHours                                 string `json:"ActionByExpDTHours"`
		ActionByExpDTMinutes                               string `json:"ActionByExpDTMinutes"`
		ActionByExpDTSeconds                               string `json:"ActionByExpDTSeconds"`
		ActionByExpDTMillis                                string `json:"ActionByExpDTMillis"`
		ActionByExpDTGmtOffset                             string `json:"ActionByExpDTGmtOffset"`
		ActionByExpDTPrecision                             string `json:"ActionByExpDTPrecision"`
		ActionByExpDTProfessionalSuffix                    string `json:"ActionByExpDTProfessionalSuffix"`
		ActionByAJIdentifier                               string `json:"ActionByAJIdentifier"`
		ActionByAJText                                     string `json:"ActionByAJText"`
		ActionByAJNameOfCodingSystem                       string `json:"ActionByAJNameOfCodingSystem"`
		ActionByAJAlternateIdentifier                      string `json:"ActionByAJAlternateIdentifier"`
		ActionByAJAlternateText                            string `json:"ActionByAJAlternateText"`
		ActionByAJNameOfAlternateCodingSystem              string `json:"ActionByAJNameOfAlternateCodingSystem"`
		ActionByAJCodingSystemVersionID                    string `json:"ActionByAJCodingSystemVersionID"`
		ActionByAJAlternateCodingSystemVersionID           string `json:"ActionByAJAlternateCodingSystemVersionID"`
		ActionByAJOriginalText                             string `json:"ActionByAJOriginalText"`
		ActionByAADIdentifier                              string `json:"ActionByAADIdentifier"`
		ActionByAADText                                    string `json:"ActionByAADText"`
		ActionByAADNameOfCodingSystem                      string `json:"ActionByAADNameOfCodingSystem"`
		ActionByAADAlternateIdentifier                     string `json:"ActionByAADAlternateIdentifier"`
		ActionByAADAlternateText                           string `json:"ActionByAADAlternateText"`
		ActionByAADNameOfAlternateCodingSystem             string `json:"ActionByAADNameOfAlternateCodingSystem"`
		ActionByAADCodingSystemVersionID                   string `json:"ActionByAADCodingSystemVersionID"`
		ActionByAADAlternateCodingSystemVersionID          string `json:"ActionByAADAlternateCodingSystemVersionID"`
		ActionByAADOriginalText                            string `json:"ActionByAADOriginalText"`
		ActionByNVStartDateTime                            string `json:"ActionByNVStartDateTime"`
		ActionByNVEndDateTime                              string `json:"ActionByNVEndDateTime"`
		ActionByEffDTTime                                  string `json:"ActionByEffDTTime"`
		ActionByExpDTTime                                  string `json:"ActionByExpDTTime"`
	} `json:"ORCActionBy"`
	ORCEnteredBy struct {
		Class                                               string `json:"$class"`
		EnteredByIDNumber                                   string `json:"EnteredByIDNumber"`
		EnteredByFamilyName                                 string `json:"EnteredByFamilyName"`
		EnteredByFNPrefix                                   string `json:"EnteredByFNPrefix"`
		EnteredByFNOwnFamilyName                            string `json:"EnteredByFNOwnFamilyName"`
		EnteredByFNPrefixFromPartnerSpouse                  string `json:"EnteredByFNPrefixFromPartnerSpouse"`
		EnteredByFNFrompartnerspouse                        string `json:"EnteredByFNFrompartnerspouse"`
		EnteredByGivenName                                  string `json:"EnteredByGivenName"`
		EnteredByMiddleinitialorname                        string `json:"EnteredByMiddleinitialorname"`
		EnteredBySuffix                                     string `json:"EnteredBySuffix"`
		EnteredByPrefix                                     string `json:"EnteredByPrefix"`
		EnteredByDegree                                     string `json:"EnteredByDegree"`
		EnteredBySourcetable                                string `json:"EnteredBySourcetable"`
		EnteredByAANamespaceID                              string `json:"EnteredByAANamespaceID"`
		EnteredByAAUniversalID                              string `json:"EnteredByAAUniversalID"`
		EnteredByAAUniversalIDtype                          string `json:"EnteredByAAUniversalIDtype"`
		EnteredByNametypecode                               string `json:"EnteredByNametypecode"`
		EnteredByIdentifiercheckdigit                       string `json:"EnteredByIdentifiercheckdigit"`
		EnteredByCodeidentifyingthecheckdigitschemeemployed string `json:"EnteredByCodeidentifyingthecheckdigitschemeemployed"`
		EnteredByIdentifiertypecode                         string `json:"EnteredByIdentifiertypecode"`
		EnteredByAFNamespaceID                              string `json:"EnteredByAFNamespaceID"`
		EnteredByAFUniversalID                              string `json:"EnteredByAFUniversalID"`
		EnteredByAFUniversalIDtype                          string `json:"EnteredByAFUniversalIDtype"`
		EnteredByNamerepresentationcode                     string `json:"EnteredByNamerepresentationcode"`
		EnteredByNCIdentifier                               string `json:"EnteredByNCIdentifier"`
		EnteredByNCText                                     string `json:"EnteredByNCText"`
		EnteredByNCNameOfCodingSystem                       string `json:"EnteredByNCNameOfCodingSystem"`
		EnteredByNCAlternateIdentifier                      string `json:"EnteredByNCAlternateIdentifier"`
		EnteredByNCAlternateText                            string `json:"EnteredByNCAlternateText"`
		EnteredByNCAlternateCodingSystem                    string `json:"EnteredByNCAlternateCodingSystem"`
		EnteredByNVStartDateYear                            string `json:"EnteredByNVStartDateYear"`
		EnteredByNVStartDateMonth                           string `json:"EnteredByNVStartDateMonth"`
		EnteredByNVStartDateDay                             string `json:"EnteredByNVStartDateDay"`
		EnteredByNVStartDateHours                           string `json:"EnteredByNVStartDateHours"`
		EnteredByNVStartDateMinutes                         string `json:"EnteredByNVStartDateMinutes"`
		EnteredByNVStartDateSeconds                         string `json:"EnteredByNVStartDateSeconds"`
		EnteredByNVStartDateMillis                          string `json:"EnteredByNVStartDateMillis"`
		EnteredByNVStartDateGmtOffset                       string `json:"EnteredByNVStartDateGmtOffset"`
		EnteredByNVStartDatePrecision                       string `json:"EnteredByNVStartDatePrecision"`
		EnteredByNVEndDateYear                              string `json:"EnteredByNVEndDateYear"`
		EnteredByNVEndDateMonth                             string `json:"EnteredByNVEndDateMonth"`
		EnteredByNVEndDateDay                               string `json:"EnteredByNVEndDateDay"`
		EnteredByNVEndDateHours                             string `json:"EnteredByNVEndDateHours"`
		EnteredByNVEndDateMinutes                           string `json:"EnteredByNVEndDateMinutes"`
		EnteredByNVEndDateSeconds                           string `json:"EnteredByNVEndDateSeconds"`
		EnteredByNVEndDateMillis                            string `json:"EnteredByNVEndDateMillis"`
		EnteredByNVEndDateGmtOffset                         string `json:"EnteredByNVEndDateGmtOffset"`
		EnteredByNVEndDatePrecision                         string `json:"EnteredByNVEndDatePrecision"`
		EnteredByNameassemblyorder                          string `json:"EnteredByNameassemblyorder"`
		EnteredByEffDTYear                                  string `json:"EnteredByEffDTYear"`
		EnteredByEffDTMonth                                 string `json:"EnteredByEffDTMonth"`
		EnteredByEffDTDay                                   string `json:"EnteredByEffDTDay"`
		EnteredByEffDTHours                                 string `json:"EnteredByEffDTHours"`
		EnteredByEffDTMinutes                               string `json:"EnteredByEffDTMinutes"`
		EnteredByEffDTSeconds                               string `json:"EnteredByEffDTSeconds"`
		EnteredByEffDTMillis                                string `json:"EnteredByEffDTMillis"`
		EnteredByEffDTGmtOffset                             string `json:"EnteredByEffDTGmtOffset"`
		EnteredByEffDTPrecision                             string `json:"EnteredByEffDTPrecision"`
		EnteredByExpDTYear                                  string `json:"EnteredByExpDTYear"`
		EnteredByExpDTMonth                                 string `json:"EnteredByExpDTMonth"`
		EnteredByExpDTDay                                   string `json:"EnteredByExpDTDay"`
		EnteredByExpDTHours                                 string `json:"EnteredByExpDTHours"`
		EnteredByExpDTMinutes                               string `json:"EnteredByExpDTMinutes"`
		EnteredByExpDTSeconds                               string `json:"EnteredByExpDTSeconds"`
		EnteredByExpDTMillis                                string `json:"EnteredByExpDTMillis"`
		EnteredByExpDTGmtOffset                             string `json:"EnteredByExpDTGmtOffset"`
		EnteredByExpDTPrecision                             string `json:"EnteredByExpDTPrecision"`
		EnteredByExpDTProfessionalSuffix                    string `json:"EnteredByExpDTProfessionalSuffix"`
		EnteredByAJIdentifier                               string `json:"EnteredByAJIdentifier"`
		EnteredByAJText                                     string `json:"EnteredByAJText"`
		EnteredByAJNameOfCodingSystem                       string `json:"EnteredByAJNameOfCodingSystem"`
		EnteredByAJAlternateIdentifier                      string `json:"EnteredByAJAlternateIdentifier"`
		EnteredByAJAlternateText                            string `json:"EnteredByAJAlternateText"`
		EnteredByAJNameOfAlternateCodingSystem              string `json:"EnteredByAJNameOfAlternateCodingSystem"`
		EnteredByAJCodingSystemVersionID                    string `json:"EnteredByAJCodingSystemVersionID"`
		EnteredByAJAlternateCodingSystemVersionID           string `json:"EnteredByAJAlternateCodingSystemVersionID"`
		EnteredByAJOriginalText                             string `json:"EnteredByAJOriginalText"`
		EnteredByAADIdentifier                              string `json:"EnteredByAADIdentifier"`
		EnteredByAADText                                    string `json:"EnteredByAADText"`
		EnteredByAADNameOfCodingSystem                      string `json:"EnteredByAADNameOfCodingSystem"`
		EnteredByAADAlternateIdentifier                     string `json:"EnteredByAADAlternateIdentifier"`
		EnteredByAADAlternateText                           string `json:"EnteredByAADAlternateText"`
		EnteredByAADNameOfAlternateCodingSystem             string `json:"EnteredByAADNameOfAlternateCodingSystem"`
		EnteredByAADCodingSystemVersionID                   string `json:"EnteredByAADCodingSystemVersionID"`
		EnteredByAADAlternateCodingSystemVersionID          string `json:"EnteredByAADAlternateCodingSystemVersionID"`
		EnteredByAADOriginalText                            string `json:"EnteredByAADOriginalText"`
		EnteredByNVStartDateTime                            string `json:"EnteredByNVStartDateTime"`
		EnteredByNVEndDateTime                              string `json:"EnteredByNVEndDateTime"`
		EnteredByEffDTTime                                  string `json:"EnteredByEffDTTime"`
		EnteredByExpDTTime                                  string `json:"EnteredByExpDTTime"`
	} `json:"ORCEnteredBy"`
	ORCVerifiedBy struct {
		Class                                                string `json:"$class"`
		VerifiedByIDNumber                                   string `json:"VerifiedByIDNumber"`
		VerifiedByFamilyName                                 string `json:"VerifiedByFamilyName"`
		VerifiedByFNPrefix                                   string `json:"VerifiedByFNPrefix"`
		VerifiedByFNOwnFamilyName                            string `json:"VerifiedByFNOwnFamilyName"`
		VerifiedByFNPrefixFromPartnerSpouse                  string `json:"VerifiedByFNPrefixFromPartnerSpouse"`
		VerifiedByFNFrompartnerspouse                        string `json:"VerifiedByFNFrompartnerspouse"`
		VerifiedByGivenName                                  string `json:"VerifiedByGivenName"`
		VerifiedByMiddleinitialorname                        string `json:"VerifiedByMiddleinitialorname"`
		VerifiedBySuffix                                     string `json:"VerifiedBySuffix"`
		VerifiedByPrefix                                     string `json:"VerifiedByPrefix"`
		VerifiedByDegree                                     string `json:"VerifiedByDegree"`
		VerifiedBySourcetable                                string `json:"VerifiedBySourcetable"`
		VerifiedByAANamespaceID                              string `json:"VerifiedByAANamespaceID"`
		VerifiedByAAUniversalID                              string `json:"VerifiedByAAUniversalID"`
		VerifiedByAAUniversalIDtype                          string `json:"VerifiedByAAUniversalIDtype"`
		VerifiedByNametypecode                               string `json:"VerifiedByNametypecode"`
		VerifiedByIdentifiercheckdigit                       string `json:"VerifiedByIdentifiercheckdigit"`
		VerifiedByCodeidentifyingthecheckdigitschemeemployed string `json:"VerifiedByCodeidentifyingthecheckdigitschemeemployed"`
		VerifiedByIdentifiertypecode                         string `json:"VerifiedByIdentifiertypecode"`
		VerifiedByAFNamespaceID                              string `json:"VerifiedByAFNamespaceID"`
		VerifiedByAFUniversalID                              string `json:"VerifiedByAFUniversalID"`
		VerifiedByAFUniversalIDtype                          string `json:"VerifiedByAFUniversalIDtype"`
		VerifiedByNamerepresentationcode                     string `json:"VerifiedByNamerepresentationcode"`
		VerifiedByNCIdentifier                               string `json:"VerifiedByNCIdentifier"`
		VerifiedByNCText                                     string `json:"VerifiedByNCText"`
		VerifiedByNCNameOfCodingSystem                       string `json:"VerifiedByNCNameOfCodingSystem"`
		VerifiedByNCAlternateIdentifier                      string `json:"VerifiedByNCAlternateIdentifier"`
		VerifiedByNCAlternateText                            string `json:"VerifiedByNCAlternateText"`
		VerifiedByNCAlternateCodingSystem                    string `json:"VerifiedByNCAlternateCodingSystem"`
		VerifiedByNVStartDateYear                            string `json:"VerifiedByNVStartDateYear"`
		VerifiedByNVStartDateMonth                           string `json:"VerifiedByNVStartDateMonth"`
		VerifiedByNVStartDateDay                             string `json:"VerifiedByNVStartDateDay"`
		VerifiedByNVStartDateHours                           string `json:"VerifiedByNVStartDateHours"`
		VerifiedByNVStartDateMinutes                         string `json:"VerifiedByNVStartDateMinutes"`
		VerifiedByNVStartDateSeconds                         string `json:"VerifiedByNVStartDateSeconds"`
		VerifiedByNVStartDateMillis                          string `json:"VerifiedByNVStartDateMillis"`
		VerifiedByNVStartDateGmtOffset                       string `json:"VerifiedByNVStartDateGmtOffset"`
		VerifiedByNVStartDatePrecision                       string `json:"VerifiedByNVStartDatePrecision"`
		VerifiedByNVEndDateYear                              string `json:"VerifiedByNVEndDateYear"`
		VerifiedByNVEndDateMonth                             string `json:"VerifiedByNVEndDateMonth"`
		VerifiedByNVEndDateDay                               string `json:"VerifiedByNVEndDateDay"`
		VerifiedByNVEndDateHours                             string `json:"VerifiedByNVEndDateHours"`
		VerifiedByNVEndDateMinutes                           string `json:"VerifiedByNVEndDateMinutes"`
		VerifiedByNVEndDateSeconds                           string `json:"VerifiedByNVEndDateSeconds"`
		VerifiedByNVEndDateMillis                            string `json:"VerifiedByNVEndDateMillis"`
		VerifiedByNVEndDateGmtOffset                         string `json:"VerifiedByNVEndDateGmtOffset"`
		VerifiedByNVEndDatePrecision                         string `json:"VerifiedByNVEndDatePrecision"`
		VerifiedByNameassemblyorder                          string `json:"VerifiedByNameassemblyorder"`
		VerifiedByEffDTYear                                  string `json:"VerifiedByEffDTYear"`
		VerifiedByEffDTMonth                                 string `json:"VerifiedByEffDTMonth"`
		VerifiedByEffDTDay                                   string `json:"VerifiedByEffDTDay"`
		VerifiedByEffDTHours                                 string `json:"VerifiedByEffDTHours"`
		VerifiedByEffDTMinutes                               string `json:"VerifiedByEffDTMinutes"`
		VerifiedByEffDTSeconds                               string `json:"VerifiedByEffDTSeconds"`
		VerifiedByEffDTMillis                                string `json:"VerifiedByEffDTMillis"`
		VerifiedByEffDTGmtOffset                             string `json:"VerifiedByEffDTGmtOffset"`
		VerifiedByEffDTPrecision                             string `json:"VerifiedByEffDTPrecision"`
		VerifiedByExpDTYear                                  string `json:"VerifiedByExpDTYear"`
		VerifiedByExpDTMonth                                 string `json:"VerifiedByExpDTMonth"`
		VerifiedByExpDTDay                                   string `json:"VerifiedByExpDTDay"`
		VerifiedByExpDTHours                                 string `json:"VerifiedByExpDTHours"`
		VerifiedByExpDTMinutes                               string `json:"VerifiedByExpDTMinutes"`
		VerifiedByExpDTSeconds                               string `json:"VerifiedByExpDTSeconds"`
		VerifiedByExpDTMillis                                string `json:"VerifiedByExpDTMillis"`
		VerifiedByExpDTGmtOffset                             string `json:"VerifiedByExpDTGmtOffset"`
		VerifiedByExpDTPrecision                             string `json:"VerifiedByExpDTPrecision"`
		VerifiedByExpDTProfessionalSuffix                    string `json:"VerifiedByExpDTProfessionalSuffix"`
		VerifiedByAJIdentifier                               string `json:"VerifiedByAJIdentifier"`
		VerifiedByAJText                                     string `json:"VerifiedByAJText"`
		VerifiedByAJNameOfCodingSystem                       string `json:"VerifiedByAJNameOfCodingSystem"`
		VerifiedByAJAlternateIdentifier                      string `json:"VerifiedByAJAlternateIdentifier"`
		VerifiedByAJAlternateText                            string `json:"VerifiedByAJAlternateText"`
		VerifiedByAJNameOfAlternateCodingSystem              string `json:"VerifiedByAJNameOfAlternateCodingSystem"`
		VerifiedByAJCodingSystemVersionID                    string `json:"VerifiedByAJCodingSystemVersionID"`
		VerifiedByAJAlternateCodingSystemVersionID           string `json:"VerifiedByAJAlternateCodingSystemVersionID"`
		VerifiedByAJOriginalText                             string `json:"VerifiedByAJOriginalText"`
		VerifiedByAADIdentifier                              string `json:"VerifiedByAADIdentifier"`
		VerifiedByAADText                                    string `json:"VerifiedByAADText"`
		VerifiedByAADNameOfCodingSystem                      string `json:"VerifiedByAADNameOfCodingSystem"`
		VerifiedByAADAlternateIdentifier                     string `json:"VerifiedByAADAlternateIdentifier"`
		VerifiedByAADAlternateText                           string `json:"VerifiedByAADAlternateText"`
		VerifiedByAADNameOfAlternateCodingSystem             string `json:"VerifiedByAADNameOfAlternateCodingSystem"`
		VerifiedByAADCodingSystemVersionID                   string `json:"VerifiedByAADCodingSystemVersionID"`
		VerifiedByAADAlternateCodingSystemVersionID          string `json:"VerifiedByAADAlternateCodingSystemVersionID"`
		VerifiedByAADOriginalText                            string `json:"VerifiedByAADOriginalText"`
		VerifiedByNVStartDateTime                            string `json:"VerifiedByNVStartDateTime"`
		VerifiedByNVEndDateTime                              string `json:"VerifiedByNVEndDateTime"`
		VerifiedByEffDTTime                                  string `json:"VerifiedByEffDTTime"`
		VerifiedByExpDTTime                                  string `json:"VerifiedByExpDTTime"`
	} `json:"ORCVerifiedBy"`
	ORCCallBackPhoneNumber struct {
		Class                                             string `json:"$class"`
		CallBackPhoneNumberST                             string `json:"CallBackPhoneNumberST"`
		CallBackPhoneNumberTelecommunicationUseCode       string `json:"CallBackPhoneNumberTelecommunicationUseCode"`
		CallBackPhoneNumberTelecommunicationEquipmentType string `json:"CallBackPhoneNumberTelecommunicationEquipmentType"`
		CallBackPhoneNumberEmailAddress                   string `json:"CallBackPhoneNumberEmailAddress"`
		CallBackPhoneNumberCountryCode                    string `json:"CallBackPhoneNumberCountryCode"`
		CallBackPhoneNumberAreaOrCityCode                 string `json:"CallBackPhoneNumberAreaOrCityCode"`
		CallBackPhoneNumberPhoneNumber                    string `json:"CallBackPhoneNumberPhoneNumber"`
		CallBackPhoneNumberExtension                      string `json:"CallBackPhoneNumberExtension"`
		CallBackPhoneNumberAnyText                        string `json:"CallBackPhoneNumberAnyText"`
		CallBackPhoneNumberExtensionPrefix                string `json:"CallBackPhoneNumberExtensionPrefix"`
		CallBackPhoneNumberSpeedDialCode                  string `json:"CallBackPhoneNumberSpeedDialCode"`
		CallBackPhoneNumberUnformattedTelephonenumber     string `json:"CallBackPhoneNumberUnformattedTelephonenumber"`
	} `json:"ORCCallBackPhoneNumber"`
	ORCOrderingFacilityAddress struct {
		Class                                      string `json:"$class"`
		OrderingFacilityStreetaddress              string `json:"OrderingFacilityStreetaddress"`
		OrderingFacilityStreetname                 string `json:"OrderingFacilityStreetname"`
		OrderingFacilityDwellingnumber             string `json:"OrderingFacilityDwellingnumber"`
		OrderingFacilityOtherDesignation           string `json:"OrderingFacilityOtherDesignation"`
		OrderingFacilityCity                       string `json:"OrderingFacilityCity"`
		OrderingFacilityStateOrProvince            string `json:"OrderingFacilityStateOrProvince"`
		OrderingFacilityZipOrPostalCode            string `json:"OrderingFacilityZipOrPostalCode"`
		OrderingFacilityCountry                    string `json:"OrderingFacilityCountry"`
		OrderingFacilityType                       string `json:"OrderingFacilityType"`
		OrderingFacilityOtherGeographicDesignation string `json:"OrderingFacilityOtherGeographicDesignation"`
		OrderingFacilityCountyOrParishCode         string `json:"OrderingFacilityCountyOrParishCode"`
		OrderingFacilityCensusTract                string `json:"OrderingFacilityCensusTract"`
		OrderingFacilityRepresentationcode         string `json:"OrderingFacilityRepresentationcode"`
		OrderingFacilityValidityStartDateYear      string `json:"OrderingFacilityValidityStartDateYear"`
		OrderingFacilityValidityStartDateMonth     string `json:"OrderingFacilityValidityStartDateMonth"`
		OrderingFacilityValidityStartDateDay       string `json:"OrderingFacilityValidityStartDateDay"`
		OrderingFacilityValidityStartDateHours     string `json:"OrderingFacilityValidityStartDateHours"`
		OrderingFacilityValidityStartDateMinutes   string `json:"OrderingFacilityValidityStartDateMinutes"`
		OrderingFacilityValidityStartDateSeconds   string `json:"OrderingFacilityValidityStartDateSeconds"`
		OrderingFacilityValidityStartDateMillis    string `json:"OrderingFacilityValidityStartDateMillis"`
		OrderingFacilityValidityStartDateGmtOffset string `json:"OrderingFacilityValidityStartDateGmtOffset"`
		OrderingFacilityValidityStartDatePrecision string `json:"OrderingFacilityValidityStartDatePrecision"`
		OrderingFacilityValidityEndDateYear        string `json:"OrderingFacilityValidityEndDateYear"`
		OrderingFacilityValidityEndDateMonth       string `json:"OrderingFacilityValidityEndDateMonth"`
		OrderingFacilityValidityEndDateDay         string `json:"OrderingFacilityValidityEndDateDay"`
		OrderingFacilityValidityEndDateHours       string `json:"OrderingFacilityValidityEndDateHours"`
		OrderingFacilityValidityEndDateMinutes     string `json:"OrderingFacilityValidityEndDateMinutes"`
		OrderingFacilityValidityEndDateSeconds     string `json:"OrderingFacilityValidityEndDateSeconds"`
		OrderingFacilityValidityEndDateMillis      string `json:"OrderingFacilityValidityEndDateMillis"`
		OrderingFacilityValidityEndDateGmtOffset   string `json:"OrderingFacilityValidityEndDateGmtOffset"`
		OrderingFacilityValidityEndDatePrecision   string `json:"OrderingFacilityValidityEndDatePrecision"`
		OrderingFacilityEffDTYear                  string `json:"OrderingFacilityEffDTYear"`
		OrderingFacilityEffDTMonth                 string `json:"OrderingFacilityEffDTMonth"`
		OrderingFacilityEffDTDay                   string `json:"OrderingFacilityEffDTDay"`
		OrderingFacilityEffDTHours                 string `json:"OrderingFacilityEffDTHours"`
		OrderingFacilityEffDTMinutes               string `json:"OrderingFacilityEffDTMinutes"`
		OrderingFacilityEffDTSeconds               string `json:"OrderingFacilityEffDTSeconds"`
		OrderingFacilityEffDTMillis                string `json:"OrderingFacilityEffDTMillis"`
		OrderingFacilityEffDTGmtOffset             string `json:"OrderingFacilityEffDTGmtOffset"`
		OrderingFacilityEffDTPrecision             string `json:"OrderingFacilityEffDTPrecision"`
		OrderingFacilityExpDTYear                  string `json:"OrderingFacilityExpDTYear"`
		OrderingFacilityExpDTMonth                 string `json:"OrderingFacilityExpDTMonth"`
		OrderingFacilityExpDTDay                   string `json:"OrderingFacilityExpDTDay"`
		OrderingFacilityExpDTHours                 string `json:"OrderingFacilityExpDTHours"`
		OrderingFacilityExpDTMinutes               string `json:"OrderingFacilityExpDTMinutes"`
		OrderingFacilityExpDTSeconds               string `json:"OrderingFacilityExpDTSeconds"`
		OrderingFacilityExpDTMillis                string `json:"OrderingFacilityExpDTMillis"`
		OrderingFacilityExpDTGmtOffset             string `json:"OrderingFacilityExpDTGmtOffset"`
		OrderingFacilityExpDTPrecision             string `json:"OrderingFacilityExpDTPrecision"`
		OrderingFacilityValidityStartDateTime      string `json:"OrderingFacilityValidityStartDateTime"`
		OrderingFacilityValidityEndDateTime        string `json:"OrderingFacilityValidityEndDateTime"`
		OrderingFacilityEffDTTime                  string `json:"OrderingFacilityEffDTTime"`
		OrderingFacilityExpDTTime                  string `json:"OrderingFacilityExpDTTime"`
	} `json:"ORCOrderingFacilityAddress"`
	ORCOrderingFacilityName struct {
		Class                                                      string `json:"$class"`
		OrderingFacilityName                                       string `json:"OrderingFacilityName"`
		OrderingFacilityNameTypeCode                               string `json:"OrderingFacilityNameTypeCode"`
		OrderingFacilityIDNumber                                   string `json:"OrderingFacilityIDNumber"`
		OrderingFacilityCheckDigit                                 string `json:"OrderingFacilityCheckDigit"`
		OrderingFacilityCodeIdentifyingTheCheckDigitSchemeEmployed string `json:"OrderingFacilityCodeIdentifyingTheCheckDigitSchemeEmployed"`
		OrderingFacilityAANamespaceID                              string `json:"OrderingFacilityAANamespaceID"`
		OrderingFacilityAAUniversalID                              string `json:"OrderingFacilityAAUniversalID"`
		OrderingFacilityAAUniversalIDType                          string `json:"OrderingFacilityAAUniversalIDType"`
		OrderingFacilityIdentifierTypeCode                         string `json:"OrderingFacilityIdentifierTypeCode"`
		OrderingFacilityAFNamespaceID                              string `json:"OrderingFacilityAFNamespaceID"`
		OrderingFacilityAFUniversalID                              string `json:"OrderingFacilityAFUniversalID"`
		OrderingFacilityAFUniversalIDType                          string `json:"OrderingFacilityAFUniversalIDType"`
		OrderingFacilityNameRepresentationCode                     string `json:"OrderingFacilityNameRepresentationCode"`
		OrderingFacilityOrganizationIdentifier                     string `json:"OrderingFacilityOrganizationIdentifier"`
	} `json:"ORCOrderingFacilityName"`
	ORCOrderingFacilityPhNum struct {
		Class                                               string `json:"$class"`
		OrderingFacilityPhNumST                             string `json:"OrderingFacilityPhNumST"`
		OrderingFacilityPhNumTelecommunicationUseCode       string `json:"OrderingFacilityPhNumTelecommunicationUseCode"`
		OrderingFacilityPhNumTelecommunicationEquipmentType string `json:"OrderingFacilityPhNumTelecommunicationEquipmentType"`
		OrderingFacilityPhNumEmailAddress                   string `json:"OrderingFacilityPhNumEmailAddress"`
		OrderingFacilityPhNumCountryCode                    string `json:"OrderingFacilityPhNumCountryCode"`
		OrderingFacilityPhNumAreaOrCityCode                 string `json:"OrderingFacilityPhNumAreaOrCityCode"`
		OrderingFacilityPhNumPhoneNumber                    string `json:"OrderingFacilityPhNumPhoneNumber"`
		OrderingFacilityPhNumExtension                      string `json:"OrderingFacilityPhNumExtension"`
		OrderingFacilityPhNumAnyText                        string `json:"OrderingFacilityPhNumAnyText"`
		OrderingFacilityPhNumExtensionPrefix                string `json:"OrderingFacilityPhNumExtensionPrefix"`
		OrderingFacilityPhNumSpeedDialCode                  string `json:"OrderingFacilityPhNumSpeedDialCode"`
		OrderingFacilityPhNumUnformattedTelephonenumber     string `json:"OrderingFacilityPhNumUnformattedTelephonenumber"`
	} `json:"ORCOrderingFacilityPhNum"`
	ORCOrderingProvider struct {
		Class                                                      string `json:"$class"`
		OrderingProviderIDNumber                                   string `json:"OrderingProviderIDNumber"`
		OrderingProviderFamilyName                                 string `json:"OrderingProviderFamilyName"`
		OrderingProviderFNPrefix                                   string `json:"OrderingProviderFNPrefix"`
		OrderingProviderFNOwnFamilyName                            string `json:"OrderingProviderFNOwnFamilyName"`
		OrderingProviderFNPrefixFromPartnerSpouse                  string `json:"OrderingProviderFNPrefixFromPartnerSpouse"`
		OrderingProviderFNFrompartnerspouse                        string `json:"OrderingProviderFNFrompartnerspouse"`
		OrderingProviderGivenName                                  string `json:"OrderingProviderGivenName"`
		OrderingProviderMiddleinitialorname                        string `json:"OrderingProviderMiddleinitialorname"`
		OrderingProviderSuffix                                     string `json:"OrderingProviderSuffix"`
		OrderingProviderPrefix                                     string `json:"OrderingProviderPrefix"`
		OrderingProviderDegree                                     string `json:"OrderingProviderDegree"`
		OrderingProviderSourcetable                                string `json:"OrderingProviderSourcetable"`
		OrderingProviderAANamespaceID                              string `json:"OrderingProviderAANamespaceID"`
		OrderingProviderAAUniversalID                              string `json:"OrderingProviderAAUniversalID"`
		OrderingProviderAAUniversalIDtype                          string `json:"OrderingProviderAAUniversalIDtype"`
		OrderingProviderNametypecode                               string `json:"OrderingProviderNametypecode"`
		OrderingProviderIdentifiercheckdigit                       string `json:"OrderingProviderIdentifiercheckdigit"`
		OrderingProviderCodeidentifyingthecheckdigitschemeemployed string `json:"OrderingProviderCodeidentifyingthecheckdigitschemeemployed"`
		OrderingProviderIdentifiertypecode                         string `json:"OrderingProviderIdentifiertypecode"`
		OrderingProviderAFNamespaceID                              string `json:"OrderingProviderAFNamespaceID"`
		OrderingProviderAFUniversalID                              string `json:"OrderingProviderAFUniversalID"`
		OrderingProviderAFUniversalIDtype                          string `json:"OrderingProviderAFUniversalIDtype"`
		OrderingProviderNamerepresentationcode                     string `json:"OrderingProviderNamerepresentationcode"`
		OrderingProviderNCIdentifier                               string `json:"OrderingProviderNCIdentifier"`
		OrderingProviderNCText                                     string `json:"OrderingProviderNCText"`
		OrderingProviderNCNameOfCodingSystem                       string `json:"OrderingProviderNCNameOfCodingSystem"`
		OrderingProviderNCAlternateIdentifier                      string `json:"OrderingProviderNCAlternateIdentifier"`
		OrderingProviderNCAlternateText                            string `json:"OrderingProviderNCAlternateText"`
		OrderingProviderNCAlternateCodingSystem                    string `json:"OrderingProviderNCAlternateCodingSystem"`
		OrderingProviderNVStartDateYear                            string `json:"OrderingProviderNVStartDateYear"`
		OrderingProviderNVStartDateMonth                           string `json:"OrderingProviderNVStartDateMonth"`
		OrderingProviderNVStartDateDay                             string `json:"OrderingProviderNVStartDateDay"`
		OrderingProviderNVStartDateHours                           string `json:"OrderingProviderNVStartDateHours"`
		OrderingProviderNVStartDateMinutes                         string `json:"OrderingProviderNVStartDateMinutes"`
		OrderingProviderNVStartDateSeconds                         string `json:"OrderingProviderNVStartDateSeconds"`
		OrderingProviderNVStartDateMillis                          string `json:"OrderingProviderNVStartDateMillis"`
		OrderingProviderNVStartDateGmtOffset                       string `json:"OrderingProviderNVStartDateGmtOffset"`
		OrderingProviderNVStartDatePrecision                       string `json:"OrderingProviderNVStartDatePrecision"`
		OrderingProviderNVEndDateYear                              string `json:"OrderingProviderNVEndDateYear"`
		OrderingProviderNVEndDateMonth                             string `json:"OrderingProviderNVEndDateMonth"`
		OrderingProviderNVEndDateDay                               string `json:"OrderingProviderNVEndDateDay"`
		OrderingProviderNVEndDateHours                             string `json:"OrderingProviderNVEndDateHours"`
		OrderingProviderNVEndDateMinutes                           string `json:"OrderingProviderNVEndDateMinutes"`
		OrderingProviderNVEndDateSeconds                           string `json:"OrderingProviderNVEndDateSeconds"`
		OrderingProviderNVEndDateMillis                            string `json:"OrderingProviderNVEndDateMillis"`
		OrderingProviderNVEndDateGmtOffset                         string `json:"OrderingProviderNVEndDateGmtOffset"`
		OrderingProviderNVEndDatePrecision                         string `json:"OrderingProviderNVEndDatePrecision"`
		OrderingProviderNameassemblyorder                          string `json:"OrderingProviderNameassemblyorder"`
		OrderingProviderEffDTYear                                  string `json:"OrderingProviderEffDTYear"`
		OrderingProviderEffDTMonth                                 string `json:"OrderingProviderEffDTMonth"`
		OrderingProviderEffDTDay                                   string `json:"OrderingProviderEffDTDay"`
		OrderingProviderEffDTHours                                 string `json:"OrderingProviderEffDTHours"`
		OrderingProviderEffDTMinutes                               string `json:"OrderingProviderEffDTMinutes"`
		OrderingProviderEffDTSeconds                               string `json:"OrderingProviderEffDTSeconds"`
		OrderingProviderEffDTMillis                                string `json:"OrderingProviderEffDTMillis"`
		OrderingProviderEffDTGmtOffset                             string `json:"OrderingProviderEffDTGmtOffset"`
		OrderingProviderEffDTPrecision                             string `json:"OrderingProviderEffDTPrecision"`
		OrderingProviderExpDTYear                                  string `json:"OrderingProviderExpDTYear"`
		OrderingProviderExpDTMonth                                 string `json:"OrderingProviderExpDTMonth"`
		OrderingProviderExpDTDay                                   string `json:"OrderingProviderExpDTDay"`
		OrderingProviderExpDTHours                                 string `json:"OrderingProviderExpDTHours"`
		OrderingProviderExpDTMinutes                               string `json:"OrderingProviderExpDTMinutes"`
		OrderingProviderExpDTSeconds                               string `json:"OrderingProviderExpDTSeconds"`
		OrderingProviderExpDTMillis                                string `json:"OrderingProviderExpDTMillis"`
		OrderingProviderExpDTGmtOffset                             string `json:"OrderingProviderExpDTGmtOffset"`
		OrderingProviderExpDTPrecision                             string `json:"OrderingProviderExpDTPrecision"`
		OrderingProviderExpDTProfessionalSuffix                    string `json:"OrderingProviderExpDTProfessionalSuffix"`
		OrderingProviderAJIdentifier                               string `json:"OrderingProviderAJIdentifier"`
		OrderingProviderAJText                                     string `json:"OrderingProviderAJText"`
		OrderingProviderAJNameOfCodingSystem                       string `json:"OrderingProviderAJNameOfCodingSystem"`
		OrderingProviderAJAlternateIdentifier                      string `json:"OrderingProviderAJAlternateIdentifier"`
		OrderingProviderAJAlternateText                            string `json:"OrderingProviderAJAlternateText"`
		OrderingProviderAJNameOfAlternateCodingSystem              string `json:"OrderingProviderAJNameOfAlternateCodingSystem"`
		OrderingProviderAJCodingSystemVersionID                    string `json:"OrderingProviderAJCodingSystemVersionID"`
		OrderingProviderAJAlternateCodingSystemVersionID           string `json:"OrderingProviderAJAlternateCodingSystemVersionID"`
		OrderingProviderAJOriginalText                             string `json:"OrderingProviderAJOriginalText"`
		OrderingProviderAADIdentifier                              string `json:"OrderingProviderAADIdentifier"`
		OrderingProviderAADText                                    string `json:"OrderingProviderAADText"`
		OrderingProviderAADNameOfCodingSystem                      string `json:"OrderingProviderAADNameOfCodingSystem"`
		OrderingProviderAADAlternateIdentifier                     string `json:"OrderingProviderAADAlternateIdentifier"`
		OrderingProviderAADAlternateText                           string `json:"OrderingProviderAADAlternateText"`
		OrderingProviderAADNameOfAlternateCodingSystem             string `json:"OrderingProviderAADNameOfAlternateCodingSystem"`
		OrderingProviderAADCodingSystemVersionID                   string `json:"OrderingProviderAADCodingSystemVersionID"`
		OrderingProviderAADAlternateCodingSystemVersionID          string `json:"OrderingProviderAADAlternateCodingSystemVersionID"`
		OrderingProviderAADOriginalText                            string `json:"OrderingProviderAADOriginalText"`
		OrderingProviderNVStartDateTime                            string `json:"OrderingProviderNVStartDateTime"`
		OrderingProviderNVEndDateTime                              string `json:"OrderingProviderNVEndDateTime"`
		OrderingProviderEffDTTime                                  string `json:"OrderingProviderEffDTTime"`
		OrderingProviderExpDTTime                                  string `json:"OrderingProviderExpDTTime"`
	} `json:"ORCOrderingProvider"`
	ORCOrderingProviderAddress struct {
		Class                                             string `json:"$class"`
		OrderingProviderStreetaddress                     string `json:"OrderingProviderStreetaddress"`
		OrderingProviderStreetname                        string `json:"OrderingProviderStreetname"`
		OrderingProviderDwellingnumber                    string `json:"OrderingProviderDwellingnumber"`
		OrderingProviderOtherDesignation                  string `json:"OrderingProviderOtherDesignation"`
		OrderingProviderCity                              string `json:"OrderingProviderCity"`
		OrderingProviderStateOrProvince                   string `json:"OrderingProviderStateOrProvince"`
		OrderingProviderZipOrPostalCode                   string `json:"OrderingProviderZipOrPostalCode"`
		OrderingProviderCountry                           string `json:"OrderingProviderCountry"`
		OrderingProviderAddressType                       string `json:"OrderingProviderAddressType"`
		OrderingProviderOtherGeographicDesignation        string `json:"OrderingProviderOtherGeographicDesignation"`
		OrderingProviderCountyOrParishCode                string `json:"OrderingProviderCountyOrParishCode"`
		OrderingProviderCensusTract                       string `json:"OrderingProviderCensusTract"`
		OrderingProviderAddressRepresentationcode         string `json:"OrderingProviderAddressRepresentationcode"`
		OrderingProviderAddressValidityStartDateYear      string `json:"OrderingProviderAddressValidityStartDateYear"`
		OrderingProviderAddressValidityStartDateMonth     string `json:"OrderingProviderAddressValidityStartDateMonth"`
		OrderingProviderAddressValidityStartDateDay       string `json:"OrderingProviderAddressValidityStartDateDay"`
		OrderingProviderAddressValidityStartDateHours     string `json:"OrderingProviderAddressValidityStartDateHours"`
		OrderingProviderAddressValidityStartDateMinutes   string `json:"OrderingProviderAddressValidityStartDateMinutes"`
		OrderingProviderAddressValidityStartDateSeconds   string `json:"OrderingProviderAddressValidityStartDateSeconds"`
		OrderingProviderAddressValidityStartDateMillis    string `json:"OrderingProviderAddressValidityStartDateMillis"`
		OrderingProviderAddressValidityStartDateGmtOffset string `json:"OrderingProviderAddressValidityStartDateGmtOffset"`
		OrderingProviderAddressValidityStartDatePrecision string `json:"OrderingProviderAddressValidityStartDatePrecision"`
		OrderingProviderAddressValidityEndDateYear        string `json:"OrderingProviderAddressValidityEndDateYear"`
		OrderingProviderAddressValidityEndDateMonth       string `json:"OrderingProviderAddressValidityEndDateMonth"`
		OrderingProviderAddressValidityEndDateDay         string `json:"OrderingProviderAddressValidityEndDateDay"`
		OrderingProviderAddressValidityEndDateHours       string `json:"OrderingProviderAddressValidityEndDateHours"`
		OrderingProviderAddressValidityEndDateMinutes     string `json:"OrderingProviderAddressValidityEndDateMinutes"`
		OrderingProviderAddressValidityEndDateSeconds     string `json:"OrderingProviderAddressValidityEndDateSeconds"`
		OrderingProviderAddressValidityEndDateMillis      string `json:"OrderingProviderAddressValidityEndDateMillis"`
		OrderingProviderAddressValidityEndDateGmtOffset   string `json:"OrderingProviderAddressValidityEndDateGmtOffset"`
		OrderingProviderAddressValidityEndDatePrecision   string `json:"OrderingProviderAddressValidityEndDatePrecision"`
		OrderingProviderEffDTYear                         string `json:"OrderingProviderEffDTYear"`
		OrderingProviderEffDTMonth                        string `json:"OrderingProviderEffDTMonth"`
		OrderingProviderEffDTDay                          string `json:"OrderingProviderEffDTDay"`
		OrderingProviderEffDTHours                        string `json:"OrderingProviderEffDTHours"`
		OrderingProviderEffDTMinutes                      string `json:"OrderingProviderEffDTMinutes"`
		OrderingProviderEffDTSeconds                      string `json:"OrderingProviderEffDTSeconds"`
		OrderingProviderEffDTMillis                       string `json:"OrderingProviderEffDTMillis"`
		OrderingProviderEffDTGmtOffset                    string `json:"OrderingProviderEffDTGmtOffset"`
		OrderingProviderEffDTPrecision                    string `json:"OrderingProviderEffDTPrecision"`
		OrderingProviderExpDTYear                         string `json:"OrderingProviderExpDTYear"`
		OrderingProviderExpDTMonth                        string `json:"OrderingProviderExpDTMonth"`
		OrderingProviderExpDTDay                          string `json:"OrderingProviderExpDTDay"`
		OrderingProviderExpDTHours                        string `json:"OrderingProviderExpDTHours"`
		OrderingProviderExpDTMinutes                      string `json:"OrderingProviderExpDTMinutes"`
		OrderingProviderExpDTSeconds                      string `json:"OrderingProviderExpDTSeconds"`
		OrderingProviderExpDTMillis                       string `json:"OrderingProviderExpDTMillis"`
		OrderingProviderExpDTGmtOffset                    string `json:"OrderingProviderExpDTGmtOffset"`
		OrderingProviderExpDTPrecision                    string `json:"OrderingProviderExpDTPrecision"`
		OrderingProviderAddressValidityStartDateTime      string `json:"OrderingProviderAddressValidityStartDateTime"`
		OrderingProviderAddressValidityEndDateTime        string `json:"OrderingProviderAddressValidityEndDateTime"`
		OrderingProviderEffDTTime                         string `json:"OrderingProviderEffDTTime"`
		OrderingProviderExpDTTime                         string `json:"OrderingProviderExpDTTime"`
	} `json:"ORCOrderingProviderAddress"`
	ORCQuantityTiming struct {
		Class                                               string `json:"$class"`
		Quantity                                            string `json:"Quantity"`
		UnitsIdentifier                                     string `json:"UnitsIdentifier"`
		UnitsText                                           string `json:"UnitsText"`
		UnitsNameOfCodingSystem                             string `json:"UnitsNameOfCodingSystem"`
		UnitsAlternateIdentifier                            string `json:"UnitsAlternateIdentifier"`
		UnitsAlternateText                                  string `json:"UnitsAlternateText"`
		UnitsAlternateCodingSystem                          string `json:"UnitsAlternateCodingSystem"`
		Interval                                            string `json:"Interval"`
		Duration                                            string `json:"duration"`
		StartDTYear                                         string `json:"StartDTYear"`
		StartDTMonth                                        string `json:"StartDTMonth"`
		StartDTDay                                          string `json:"StartDTDay"`
		StartDTHours                                        string `json:"StartDTHours"`
		StartDTMinutes                                      string `json:"StartDTMinutes"`
		StartDTSeconds                                      string `json:"StartDTSeconds"`
		StartDTMillis                                       string `json:"StartDTMillis"`
		StartDTGmtOffset                                    string `json:"StartDTGmtOffset"`
		StartDTPrecision                                    string `json:"StartDTPrecision"`
		EndDTYear                                           string `json:"EndDTYear"`
		EndDTMonth                                          string `json:"EndDTMonth"`
		EndDTDay                                            string `json:"EndDTDay"`
		EndDTHours                                          string `json:"EndDTHours"`
		EndDTMinutes                                        string `json:"EndDTMinutes"`
		EndDTSeconds                                        string `json:"EndDTSeconds"`
		EndDTMillis                                         string `json:"EndDTMillis"`
		EndDTGmtOffset                                      string `json:"EndDTGmtOffset"`
		EndDTPrecision                                      string `json:"EndDTPrecision"`
		Priority                                            string `json:"Priority"`
		Condition                                           string `json:"Condition"`
		Text                                                string `json:"Text"`
		Conjunction                                         string `json:"Conjunction"`
		OrderingSequence                                    string `json:"OrderingSequence"`
		OrderQuantityIdentifier                             string `json:"OrderQuantityIdentifier"`
		OrderQuantityText                                   string `json:"OrderQuantityText"`
		OrderQuantityNameOfCodingSystem                     string `json:"OrderQuantityNameOfCodingSystem"`
		OrderQuantityAlternateIdentifier                    string `json:"OrderQuantityAlternateIdentifier"`
		OrderQuantityAlternateText                          string `json:"OrderQuantityAlternateText"`
		OrderQuantityAlternateCodingSystem                  string `json:"OrderQuantityAlternateCodingSystem"`
		OrderQuantityTotalOccurrences                       string `json:"OrderQuantityTotalOccurrences"`
		StartDTTime                                         string `json:"StartDTTime"`
		EndDTTime                                           string `json:"EndDTTime"`
		OrderingSequencing                                  string `json:"OrderingSequencing"`
		OrderingSequencingSequenceResultsFlag               string `json:"OrderingSequencingSequenceResultsFlag"`
		OrderingSequencingPlacerOrderNumberEntityIdentifier string `json:"OrderingSequencingPlacerOrderNumberEntityIdentifier"`
		OrderingSequencingPlacerOrderNumberNamespaceID      string `json:"OrderingSequencingPlacerOrderNumberNamespaceID"`
		OrderingSequencingFillerOrderNumberEntityIdentifier string `json:"OrderingSequencingFillerOrderNumberEntityIdentifier"`
		OrderingSequencingFillerOrderNumberNamespaceID      string `json:"OrderingSequencingFillerOrderNumberNamespaceID"`
		OrderingSequencingSequenceConditionValue            string `json:"OrderingSequencingSequenceConditionValue"`
		OrderingSequencingMaximumNumberofRepeats            string `json:"OrderingSequencingMaximumNumberofRepeats"`
		OrderingSequencingPlacerOrderNumberUniversalID      string `json:"OrderingSequencingPlacerOrderNumberUniversalID"`
		OrderingSequencingPlacerOrderNumberUniversalIDType  string `json:"OrderingSequencingPlacerOrderNumberUniversalIDType"`
		OrderingSequencingFillerOrderNumberUniversalID      string `json:"OrderingSequencingFillerOrderNumberUniversalID"`
		OrderingSequencingFillerOrderNumberUniversalIDType  string `json:"OrderingSequencingFillerOrderNumberUniversalIDType"`
	} `json:"ORCQuantityTiming"`
}

func (mo *Hl7OrcFormat) fnAddOrc(ctx contractapi.TransactionContextInterface) error {

	err := FnValidationCheckStruct(mo)
	if err != nil {
		return err
	}
	fmt.Println(mo.MSHORC, "orc key value")
	mo.MSHORC = mo.MSHKEY + "_" + "ORC"
	obrBytes, err := ctx.GetStub().GetState(mo.MSHORC)
	if obrBytes != nil || err != nil {
		return fmt.Errorf("Key Already Exists in the Network")
	}
	obrBytes, _ = json.Marshal(mo)
	return ctx.GetStub().PutState(mo.MSHORC, obrBytes)
}
