package main

import (
	"encoding/json"
	"fmt"

	"github.com/hyperledger/fabric-contract-api-go/contractapi"
)

//Hl7ObxFormat ..
type Hl7ObxFormat struct {
	Class                                                                    string `json:"$class"`
	OBXKEY                                                                   string `json:"OBXKEY"`
	MSHKEY                                                                   string `json:"MSHKEY" validate:"required"`
	MSHOBX                                                                   string `json:"MSH_OBX" validate:"required"`
	SetID                                                                    string `json:"SetID"`
	ValueType                                                                string `json:"ValueType"`
	ObservationIdentifier                                                    string `json:"ObservationIdentifier"`
	ObservationText                                                          string `json:"ObservationText"`
	ObservationNameOfCodingSystem                                            string `json:"ObservationNameOfCodingSystem"`
	ObservationAlternateIdentifier                                           string `json:"ObservationAlternateIdentifier"`
	ObservationAlternateText                                                 string `json:"ObservationAlternateText"`
	ObservationNameOfAlternateCodingSystem                                   string `json:"ObservationNameOfAlternateCodingSystem"`
	ObservationSubID                                                         string `json:"ObservationSubID"`
	ReferencesRange                                                          string `json:"ReferencesRange"`
	Probability                                                              int    `json:"Probability"`
	ObservResultStatus                                                       string `json:"ObservResultStatus"`
	LastObsNormalValuesTime                                                  string `json:"LastObsNormalValuesTime"`
	LastObsNormalValuesYear                                                  string `json:"LastObsNormalValuesYear"`
	LastObsNormalValuesMonth                                                 string `json:"LastObsNormalValuesMonth"`
	LastObsNormalValuesDay                                                   string `json:"LastObsNormalValuesDay"`
	LastObsNormalValuesHours                                                 string `json:"LastObsNormalValuesHours"`
	LastObsNormalValuesMinutes                                               string `json:"LastObsNormalValuesMinutes"`
	LastObsNormalValuesSeconds                                               string `json:"LastObsNormalValuesSeconds"`
	LastObsNormalValuesMills                                                 string `json:"LastObsNormalValuesMills"`
	LastObsNormalValuesGmtOffset                                             string `json:"LastObsNormalValuesGmtOffset"`
	LastObsNormalValuesPrecision                                             string `json:"LastObsNormalValuesPrecision"`
	UserDefinedAccessChecks                                                  string `json:"UserDefinedAccessChecks"`
	ObservationTime                                                          string `json:"ObservationTime"`
	ObservationYear                                                          string `json:"ObservationYear"`
	ObservationMonth                                                         string `json:"ObservationMonth"`
	ObservationDay                                                           string `json:"ObservationDay"`
	ObservationHours                                                         string `json:"ObservationHours"`
	ObservationMinutes                                                       string `json:"ObservationMinutes"`
	ObservationSeconds                                                       string `json:"ObservationSeconds"`
	ObservationMills                                                         string `json:"ObservationMills"`
	ObservationGmtOffset                                                     string `json:"ObservationGmtOffset"`
	ObservationPrecision                                                     string `json:"ObservationPrecision"`
	ProducersIdentifier                                                      string `json:"ProducersIdentifier"`
	ProducersText                                                            string `json:"ProducersText"`
	ProducersNameOfCodingSystem                                              string `json:"ProducersNameOfCodingSystem"`
	ProducersAlternateIdentifier                                             string `json:"ProducersAlternateIdentifier"`
	ProducersAlternateText                                                   string `json:"ProducersAlternateText"`
	ProducersNameOfAlternateCodingSystem                                     string `json:"ProducersNameOfAlternateCodingSystem"`
	AnalysisTime                                                             string `json:"AnalysisTime"`
	AnalysisYear                                                             string `json:"AnalysisYear"`
	AnalysisMonth                                                            string `json:"AnalysisMonth"`
	AnalysisDay                                                              string `json:"AnalysisDay"`
	AnalysisHours                                                            string `json:"AnalysisHours"`
	AnalysisMinutes                                                          string `json:"AnalysisMinutes"`
	AnalysisSeconds                                                          string `json:"AnalysisSeconds"`
	AnalysisMills                                                            string `json:"AnalysisMills"`
	AnalysisGmtOffset                                                        string `json:"AnalysisGmtOffset"`
	AnalysisPrecision                                                        string `json:"AnalysisPrecision"`
	ReservedForHarmonizationWithV261                                         string `json:"ReservedForHarmonizationWithV261"`
	ReservedForHarmonizationWithV262                                         string `json:"ReservedForHarmonizationWithV262"`
	ReservedForHarmonizationWithV263                                         string `json:"ReservedForHarmonizationWithV263"`
	OrganizationName                                                         string `json:"OrganizationName"`
	OrganizationNameTypeCode                                                 string `json:"OrganizationNameTypeCode"`
	IDNumberDEPRECATED                                                       int    `json:"IDNumber_DEPRECATED"`
	CheckDigit                                                               int    `json:"CheckDigit"`
	CheckDigitScheme                                                         string `json:"CheckDigitScheme"`
	AANamespaceID                                                            string `json:"AANamespaceID"`
	AAUniversalID                                                            string `json:"AAUniversalID"`
	AAUniversalIDType                                                        string `json:"AAUniversalIDType"`
	IdentifierTypeCode                                                       string `json:"IdentifierTypeCode"`
	AFNamespaceID                                                            string `json:"AFNamespaceID"`
	AFUniversalID                                                            string `json:"AFUniversalID"`
	AFUniversalIDType                                                        string `json:"AFUniversalIDType"`
	NameRepresentationCode                                                   string `json:"NameRepresentationCode"`
	OrganizationIdentifier                                                   string `json:"OrganizationIdentifier"`
	PerformingOrganizatioStreetOrMailingAddress                              string `json:"PerformingOrganizatioStreetOrMailingAddress"`
	PerformingOrganizatioStreetName                                          string `json:"PerformingOrganizatioStreetName"`
	PerformingOrganizatioDwellingNumber                                      string `json:"PerformingOrganizatioDwellingNumber"`
	PerformingOrganizatioOtherDesignation                                    string `json:"PerformingOrganizatioOtherDesignation"`
	PerformingOrganizatioCity                                                string `json:"PerformingOrganizatioCity"`
	PerformingOrganizatioStateOrProvince                                     string `json:"PerformingOrganizatioStateOrProvince"`
	PerformingOrganizatioZipOrPostalCode                                     string `json:"PerformingOrganizatioZipOrPostalCode"`
	PerformingOrganizatioCountry                                             string `json:"PerformingOrganizatioCountry"`
	PerformingOrganizatioAddressType                                         string `json:"PerformingOrganizatioAddressType"`
	PerformingOrganizatioOtherGeographicDesignation                          string `json:"PerformingOrganizatioOtherGeographicDesignation"`
	PerformingOrganizatioCountyParishCode                                    string `json:"PerformingOrganizatioCountyParishCode"`
	PerformingOrganizatioCensusTract                                         string `json:"PerformingOrganizatioCensusTract"`
	PerformingOrganizatioAddressRepresentationCode                           string `json:"PerformingOrganizatioAddressRepresentationCode"`
	PerformingOrganizatioValidityStartTime                                   string `json:"PerformingOrganizatioValidityStartTime"`
	PerformingOrganizatioValidityStartYear                                   string `json:"PerformingOrganizatioValidityStartYear"`
	PerformingOrganizatioValidityStartMonth                                  string `json:"PerformingOrganizatioValidityStartMonth"`
	PerformingOrganizatioValidityStartDay                                    string `json:"PerformingOrganizatioValidityStartDay"`
	PerformingOrganizatioValidityStartHours                                  string `json:"PerformingOrganizatioValidityStartHours"`
	PerformingOrganizatioValidityStartMinutes                                string `json:"PerformingOrganizatioValidityStartMinutes"`
	PerformingOrganizatioValidityStartSeconds                                string `json:"PerformingOrganizatioValidityStartSeconds"`
	PerformingOrganizatioValidityStartMillis                                 string `json:"PerformingOrganizatioValidityStartMillis"`
	PerformingOrganizatioValidityStartGmtOffset                              string `json:"PerformingOrganizatioValidityStartGmtOffset"`
	PerformingOrganizatioValidityStartPrecision                              string `json:"PerformingOrganizatioValidityStartPrecision"`
	PerformingOrganizatioValidityEndTime                                     string `json:"PerformingOrganizatioValidityEndTime"`
	PerformingOrganizatioValidityEndYear                                     string `json:"PerformingOrganizatioValidityEndYear"`
	PerformingOrganizatioValidityEndMonth                                    string `json:"PerformingOrganizatioValidityEndMonth"`
	PerformingOrganizatioValidityEndDay                                      string `json:"PerformingOrganizatioValidityEndDay"`
	PerformingOrganizatioValidityEndHours                                    string `json:"PerformingOrganizatioValidityEndHours"`
	PerformingOrganizatioValidityEndMinutes                                  string `json:"PerformingOrganizatioValidityEndMinutes"`
	PerformingOrganizatioValidityEndSeconds                                  string `json:"PerformingOrganizatioValidityEndSeconds"`
	PerformingOrganizatioValidityEndMillis                                   string `json:"PerformingOrganizatioValidityEndMillis"`
	PerformingOrganizatioValidityEndGmtOffset                                string `json:"PerformingOrganizatioValidityEndGmtOffset"`
	PerformingOrganizatioValidityEndPrecision                                string `json:"PerformingOrganizatioValidityEndPrecision"`
	PerformingOrganizatioValidityEndNameAssemblyOrder                        string `json:"PerformingOrganizatioValidityEndNameAssemblyOrder"`
	PerformingOrganizatioEffectiveTime                                       string `json:"PerformingOrganizatioEffectiveTime"`
	PerformingOrganizatioEffectiveYear                                       string `json:"PerformingOrganizatioEffectiveYear"`
	PerformingOrganizatioEffectiveMonth                                      string `json:"PerformingOrganizatioEffectiveMonth"`
	PerformingOrganizatioEffectiveDay                                        string `json:"PerformingOrganizatioEffectiveDay"`
	PerformingOrganizatioEffectiveHours                                      string `json:"PerformingOrganizatioEffectiveHours"`
	PerformingOrganizatioEffectiveMinutes                                    string `json:"PerformingOrganizatioEffectiveMinutes"`
	PerformingOrganizatioEffectiveSeconds                                    string `json:"PerformingOrganizatioEffectiveSeconds"`
	PerformingOrganizatioEffectiveMillis                                     string `json:"PerformingOrganizatioEffectiveMillis"`
	PerformingOrganizatioEffectiveGmtOffset                                  string `json:"PerformingOrganizatioEffectiveGmtOffset"`
	PerformingOrganizatioEffectivePrecision                                  string `json:"PerformingOrganizatioEffectivePrecision"`
	PerformingOrganizatioExpirationTime                                      string `json:"PerformingOrganizatioExpirationTime"`
	PerformingOrganizatioExpirationYear                                      string `json:"PerformingOrganizatioExpirationYear"`
	PerformingOrganizatioExpirationMonth                                     string `json:"PerformingOrganizatioExpirationMonth"`
	PerformingOrganizatioExpirationDay                                       string `json:"PerformingOrganizatioExpirationDay"`
	PerformingOrganizatioExpirationHours                                     string `json:"PerformingOrganizatioExpirationHours"`
	PerformingOrganizatioExpirationMinutes                                   string `json:"PerformingOrganizatioExpirationMinutes"`
	PerformingOrganizatioExpirationSeconds                                   string `json:"PerformingOrganizatioExpirationSeconds"`
	PerformingOrganizatioExpirationMillis                                    string `json:"PerformingOrganizatioExpirationMillis"`
	PerformingOrganizatioExpirationGmtOffset                                 string `json:"PerformingOrganizatioExpirationGmtOffset"`
	PerformingOrganizatioExpirationPrecision                                 string `json:"PerformingOrganizatioExpirationPrecision"`
	PerformingOrganizationMedicalDirectorIDNumber                            string `json:"PerformingOrganizationMedicalDirectorIDNumber"`
	PerformingOrganizationMedicalDirectorSurname                             string `json:"PerformingOrganizationMedicalDirectorSurname"`
	PerformingOrganizationMedicalDirectorOwnSurnamePrefix                    string `json:"PerformingOrganizationMedicalDirectorOwnSurnamePrefix"`
	PerformingOrganizationMedicalDirectorOwnSurname                          string `json:"PerformingOrganizationMedicalDirectorOwnSurname"`
	PerformingOrganizationMedicalDirectorSurnamePrefixFromPartner            string `json:"PerformingOrganizationMedicalDirectorSurnamePrefixFromPartner"`
	PerformingOrganizationMedicalDirectorSurnameFromPartner                  string `json:"PerformingOrganizationMedicalDirectorSurnameFromPartner"`
	PerformingOrganizationMedicalDirectorGivenName                           string `json:"PerformingOrganizationMedicalDirectorGivenName"`
	PerformingOrganizationMedicalDirectorMiddleInitialOrName                 string `json:"PerformingOrganizationMedicalDirectorMiddleInitialOrName"`
	PerformingOrganizationMedicalDirectorSuffix                              string `json:"PerformingOrganizationMedicalDirectorSuffix"`
	PerformingOrganizationMedicalDirectorPrefix                              string `json:"PerformingOrganizationMedicalDirectorPrefix"`
	PerformingOrganizationMedicalDirectorDegree                              string `json:"PerformingOrganizationMedicalDirectorDegree"`
	PerformingOrganizationMedicalDirectorSourceTable                         string `json:"PerformingOrganizationMedicalDirectorSourceTable"`
	PerformingOrganizationMedicalDirectorAANamespaceID                       string `json:"PerformingOrganizationMedicalDirectorAANamespaceID"`
	PerformingOrganizationMedicalDirectorAAUniversalID                       string `json:"PerformingOrganizationMedicalDirectorAAUniversalID"`
	PerformingOrganizationMedicalDirectorAAUniversalIDType                   string `json:"PerformingOrganizationMedicalDirectorAAUniversalIDType"`
	PerformingOrganizationMedicalDirectorNameTypeCode                        string `json:"PerformingOrganizationMedicalDirectorNameTypeCode"`
	PerformingOrganizationMedicalDirectorIdentifierCheckDigit                string `json:"PerformingOrganizationMedicalDirectorIdentifierCheckDigit"`
	PerformingOrganizationMedicalDirectorCheckDigitScheme                    string `json:"PerformingOrganizationMedicalDirectorCheckDigitScheme"`
	PerformingOrganizationMedicalDirectorIdentifierTypeCode                  string `json:"PerformingOrganizationMedicalDirectorIdentifierTypeCode"`
	PerformingOrganizationMedicalDirectorAFNamespaceID                       string `json:"PerformingOrganizationMedicalDirectorAFNamespaceID"`
	PerformingOrganizationMedicalDirectorAFUniversalID                       string `json:"PerformingOrganizationMedicalDirectorAFUniversalID"`
	PerformingOrganizationMedicalDirectorAFUniversalIDType                   string `json:"PerformingOrganizationMedicalDirectorAFUniversalIDType"`
	PerformingOrganizationMedicalDirectorNameRepresentationCode              string `json:"PerformingOrganizationMedicalDirectorNameRepresentationCode"`
	MedicalDirectorNameContextIdentifier                                     string `json:"MedicalDirectorNameContextIdentifier"`
	MedicalDirectorNameContextText                                           string `json:"MedicalDirectorNameContextText"`
	MedicalDirectorNameContextNameOfCodingSystem                             string `json:"MedicalDirectorNameContextNameOfCodingSystem"`
	MedicalDirectorNameContextAlternateIdentifier                            string `json:"MedicalDirectorNameContextAlternateIdentifier"`
	MedicalDirectorNameContextAlternateText                                  string `json:"MedicalDirectorNameContextAlternateText"`
	MedicalDirectorNameContextNameOfAlternateCodingSystem                    string `json:"MedicalDirectorNameContextNameOfAlternateCodingSystem"`
	MedicalDirectorValidityStartTime                                         string `json:"MedicalDirectorValidityStartTime"`
	MedicalDirectorValidityStartYear                                         string `json:"MedicalDirectorValidityStartYear"`
	MedicalDirectorValidityStartMonth                                        string `json:"MedicalDirectorValidityStartMonth"`
	MedicalDirectorValidityStartDay                                          string `json:"MedicalDirectorValidityStartDay"`
	MedicalDirectorValidityStartHours                                        string `json:"MedicalDirectorValidityStartHours"`
	MedicalDirectorValidityStartMinutes                                      string `json:"MedicalDirectorValidityStartMinutes"`
	MedicalDirectorValidityStartSeconds                                      string `json:"MedicalDirectorValidityStartSeconds"`
	MedicalDirectorValidityStartMillis                                       string `json:"MedicalDirectorValidityStartMillis"`
	MedicalDirectorValidityStartGmtOffset                                    string `json:"MedicalDirectorValidityStartGmtOffset"`
	MedicalDirectorValidityStartPrecision                                    string `json:"MedicalDirectorValidityStartPrecision"`
	MedicalDirectorValidityEndTime                                           string `json:"MedicalDirectorValidityEndTime"`
	MedicalDirectorValidityEndYear                                           string `json:"MedicalDirectorValidityEndYear"`
	MedicalDirectorValidityEndMonth                                          string `json:"MedicalDirectorValidityEndMonth"`
	MedicalDirectorValidityEndDay                                            string `json:"MedicalDirectorValidityEndDay"`
	MedicalDirectorValidityEndHours                                          string `json:"MedicalDirectorValidityEndHours"`
	MedicalDirectorValidityEndMinutes                                        string `json:"MedicalDirectorValidityEndMinutes"`
	MedicalDirectorValidityEndSeconds                                        string `json:"MedicalDirectorValidityEndSeconds"`
	MedicalDirectorValidityEndMillis                                         string `json:"MedicalDirectorValidityEndMillis"`
	MedicalDirectorValidityEndGmtOffset                                      string `json:"MedicalDirectorValidityEndGmtOffset"`
	MedicalDirectorValidityEndPrecision                                      string `json:"MedicalDirectorValidityEndPrecision"`
	MedicalDirectorNameAssemblyOrder                                         string `json:"MedicalDirectorNameAssemblyOrder"`
	MedicalDirectorEffectiveTime                                             string `json:"MedicalDirectorEffectiveTime"`
	MedicalDirectorEffectiveYear                                             string `json:"MedicalDirectorEffectiveYear"`
	MedicalDirectorEffectiveMonth                                            string `json:"MedicalDirectorEffectiveMonth"`
	MedicalDirectorEffectiveDay                                              string `json:"MedicalDirectorEffectiveDay"`
	MedicalDirectorEffectiveHours                                            string `json:"MedicalDirectorEffectiveHours"`
	MedicalDirectorEffectiveMinutes                                          string `json:"MedicalDirectorEffectiveMinutes"`
	MedicalDirectorEffectiveSeconds                                          string `json:"MedicalDirectorEffectiveSeconds"`
	MedicalDirectorEffectiveMillis                                           string `json:"MedicalDirectorEffectiveMillis"`
	MedicalDirectorEffectiveGmtOffset                                        string `json:"MedicalDirectorEffectiveGmtOffset"`
	MedicalDirectorEffectivePrecision                                        string `json:"MedicalDirectorEffectivePrecision"`
	MedicalDirectorExpirationTime                                            string `json:"MedicalDirectorExpirationTime"`
	MedicalDirectorExpirationYear                                            string `json:"MedicalDirectorExpirationYear"`
	MedicalDirectorExpirationMonth                                           string `json:"MedicalDirectorExpirationMonth"`
	MedicalDirectorExpirationDay                                             string `json:"MedicalDirectorExpirationDay"`
	MedicalDirectorExpirationHours                                           string `json:"MedicalDirectorExpirationHours"`
	MedicalDirectorExpirationMinutes                                         string `json:"MedicalDirectorExpirationMinutes"`
	MedicalDirectorExpirationSeconds                                         string `json:"MedicalDirectorExpirationSeconds"`
	MedicalDirectorExpirationMillis                                          string `json:"MedicalDirectorExpirationMillis"`
	MedicalDirectorExpirationGmtOffset                                       string `json:"MedicalDirectorExpirationGmtOffset"`
	MedicalDirectorExpirationPrecision                                       string `json:"MedicalDirectorExpirationPrecision"`
	MedicalDirectorExpirationProfessionalSuffix                              string `json:"MedicalDirectorExpirationProfessionalSuffix"`
	MedicalDirectorAssigningJurisdictionIdentifier                           string `json:"MedicalDirectorAssigningJurisdictionIdentifier"`
	MedicalDirectorAssigningJurisdictionText                                 string `json:"MedicalDirectorAssigningJurisdictionText"`
	MedicalDirectorAssigningJurisdictionNameOfCodingSystem                   string `json:"MedicalDirectorAssigningJurisdictionNameOfCodingSystem"`
	MedicalDirectorAssigningJurisdictionAlternateIdentifier                  string `json:"MedicalDirectorAssigningJurisdictionAlternateIdentifier"`
	MedicalDirectorAssigningJurisdictionAlternateText                        string `json:"MedicalDirectorAssigningJurisdictionAlternateText"`
	MedicalDirectorAssigningJurisdictionNameOfAlternateCodingSystem          string `json:"MedicalDirectorAssigningJurisdictionNameOfAlternateCodingSystem"`
	MedicalDirectorAssigningJurisdictionCodingSystemVersionID                string `json:"MedicalDirectorAssigningJurisdictionCodingSystemVersionID"`
	MedicalDirectorAssigningJurisdictionAlternateCodingSystemVersionID       string `json:"MedicalDirectorAssigningJurisdictionAlternateCodingSystemVersionID"`
	MedicalDirectorAssigningJurisdictionOriginalText                         string `json:"MedicalDirectorAssigningJurisdictionOriginalText"`
	MedicalDirectorAssigningAgencyorDepartmentIdentifier                     string `json:"MedicalDirectorAssigningAgencyorDepartmentIdentifier"`
	MedicalDirectorAssigningAgencyorDepartmentText                           string `json:"MedicalDirectorAssigningAgencyorDepartmentText"`
	MedicalDirectorAssigningAgencyorDepartmentNameOfCodingSystem             string `json:"MedicalDirectorAssigningAgencyorDepartmentNameOfCodingSystem"`
	MedicalDirectorAssigningAgencyorDepartmentAlternateIdentifier            string `json:"MedicalDirectorAssigningAgencyorDepartmentAlternateIdentifier"`
	MedicalDirectorAssigningAgencyorDepartmentAlternateText                  string `json:"MedicalDirectorAssigningAgencyorDepartmentAlternateText"`
	MedicalDirectorAssigningAgencyorDepartmentNameOfAlternateCodingSystem    string `json:"MedicalDirectorAssigningAgencyorDepartmentNameOfAlternateCodingSystem"`
	MedicalDirectorAssigningAgencyorDepartmentCodingSystemVersionID          string `json:"MedicalDirectorAssigningAgencyorDepartmentCodingSystemVersionID"`
	MedicalDirectorAssigningAgencyorDepartmentAlternateCodingSystemVersionID string `json:"MedicalDirectorAssigningAgencyorDepartmentAlternateCodingSystemVersionID"`
	MedicalDirectorAssigningAgencyorDepartmentOriginalText                   string `json:"MedicalDirectorAssigningAgencyorDepartmentOriginalText"`
	UnitsIdentifier                                                          string `json:"UnitsIdentifier"`
	UnitsText                                                                string `json:"UnitsText"`
	UnitsNameOfCodingSystem                                                  string `json:"UnitsNameOfCodingSystem"`
	UnitsAlternateIdentifier                                                 string `json:"UnitsAlternateIdentifier"`
	UnitsAlternateText                                                       string `json:"UnitsAlternateText"`
	UnitsNameOfAlternateCodingSystem                                         string `json:"UnitsNameOfAlternateCodingSystem"`
	Units                                                                    string `json:"Units"`
	OBRKey                                                                   string `json:"OBRKey"`
	OBXObservationValue                                                      string `json:"OBXObservationValue"`
	OBXAbnormalFlags                                                         struct {
		Class         string `json:"$class"`
		AbnormalFlags string `json:"AbnormalFlags"`
	} `json:"OBXAbnormalFlags"`
	OBXEquipmentInstanceID struct {
		Class                             string `json:"$class"`
		EquipmentInstanceEntityIdentifier string `json:"EquipmentInstanceEntityIdentifier"`
		EquipmentInstanceNamespaceID      string `json:"EquipmentInstanceNamespaceID"`
		EquipmentInstanceUniversalID      string `json:"EquipmentInstanceUniversalID"`
		EquipmentInstanceUniversalIDType  string `json:"EquipmentInstanceUniversalIDType"`
	} `json:"OBXEquipmentInstanceId"`
	OBXNatureOfAbnormalTest struct {
		Class                string `json:"$class"`
		NatureOfAbnormalTest string `json:"NatureOfAbnormalTest"`
	} `json:"OBXNatureOfAbnormalTest"`
	OBXObservationMethod struct {
		Class                                        string `json:"$class"`
		ObservationMethodIdentifier                  string `json:"ObservationMethodIdentifier"`
		ObservationMethodText                        string `json:"ObservationMethodText"`
		ObservationMethodNameOfCodingSystem          string `json:"ObservationMethodNameOfCodingSystem"`
		ObservationMethodAlternateIdentifier         string `json:"ObservationMethodAlternateIdentifier"`
		ObservationMethodAlternateText               string `json:"ObservationMethodAlternateText"`
		ObservationMethodNameOfAlternateCodingSystem string `json:"ObservationMethodNameOfAlternateCodingSystem"`
	} `json:"OBXObservationMethod"`
	OBXResponsibleObserver struct {
		Class                                                                        string `json:"$class"`
		ResponsibleObserverName                                                      string `json:"ResponsibleObserverName"`
		ResponsibleObserverIDNumber                                                  string `json:"ResponsibleObserverIDNumber"`
		ResponsibleObserverFamilySurname                                             string `json:"ResponsibleObserverFamilySurname"`
		ResponsibleObserverFamilyOwnSurnamePrefix                                    string `json:"ResponsibleObserverFamilyOwnSurnamePrefix"`
		ResponsibleObserverFamilyOwnSurname                                          string `json:"ResponsibleObserverFamilyOwnSurname"`
		ResponsibleObserverFamilySurnamePrefixFromPartner                            string `json:"ResponsibleObserverFamilySurnamePrefixFromPartner"`
		ResponsibleObserverFamilySurnameFromPartner                                  string `json:"ResponsibleObserverFamilySurnameFromPartner"`
		ResponsibleObserverGivenName                                                 string `json:"ResponsibleObserverGivenName"`
		ResponsibleObserverMiddleInitialOrName                                       string `json:"ResponsibleObserverMiddleInitialOrName"`
		ResponsibleObserverSuffix                                                    string `json:"ResponsibleObserverSuffix"`
		ResponsibleObserverPrefix                                                    string `json:"ResponsibleObserverPrefix"`
		ResponsibleObserverDegreeDEPRECATEDFROM25                                    string `json:"ResponsibleObserverDegree_DEPRECATED_FROM_2_5"`
		ResponsibleObserverSourceTable                                               string `json:"ResponsibleObserverSourceTable"`
		ResponsibleObserverAANamespaceID                                             string `json:"ResponsibleObserverAANamespaceID"`
		ResponsibleObserverAAUniversalID                                             string `json:"ResponsibleObserverAAUniversalID"`
		ResponsibleObserverAAUniversalIDType                                         string `json:"ResponsibleObserverAAUniversalIDType"`
		ResponsibleObserverNameTypeCode                                              string `json:"ResponsibleObserverNameTypeCode"`
		ResponsibleObserverIdentifierCheckDigit                                      string `json:"ResponsibleObserverIdentifierCheckDigit"`
		ResponsibleObserverCodeIdentifyingTheCheckDigitSchemeEmployed                string `json:"ResponsibleObserverCodeIdentifyingTheCheckDigitSchemeEmployed"`
		ResponsibleObserverIdentifierTypeCode                                        string `json:"ResponsibleObserverIdentifierTypeCode"`
		ResponsibleObserverAFNamespaceID                                             string `json:"ResponsibleObserverAFNamespaceID"`
		ResponsibleObserverAFUniversalID                                             string `json:"ResponsibleObserverAFUniversalID"`
		ResponsibleObserverAFUniversalIDType                                         string `json:"ResponsibleObserverAFUniversalIDType"`
		ResponsibleObserverNameRepresentationCode                                    string `json:"ResponsibleObserverNameRepresentationCode"`
		ResponsibleObserverNameContextIdentifier                                     string `json:"ResponsibleObserverNameContextIdentifier"`
		ResponsibleObserverNameContextText                                           string `json:"ResponsibleObserverNameContextText"`
		ResponsibleObserverNameContextNameOfCodingSystem                             string `json:"ResponsibleObserverNameContextNameOfCodingSystem"`
		ResponsibleObserverNameContextAlternateIdentifier                            string `json:"ResponsibleObserverNameContextAlternateIdentifier"`
		ResponsibleObserverNameContextAlternateText                                  string `json:"ResponsibleObserverNameContextAlternateText"`
		ResponsibleObserverNameContextNameOfAlternateCodingSystem                    string `json:"ResponsibleObserverNameContextNameOfAlternateCodingSystem"`
		ResponsibleObserverNameValidityRangeStartTime                                string `json:"ResponsibleObserverNameValidityRangeStartTime"`
		ResponsibleObserverNameValidityRangeStartYear                                string `json:"ResponsibleObserverNameValidityRangeStartYear"`
		ResponsibleObserverNameValidityRangeStartMonth                               string `json:"ResponsibleObserverNameValidityRangeStartMonth"`
		ResponsibleObserverNameValidityRangeStartDay                                 string `json:"ResponsibleObserverNameValidityRangeStartDay"`
		ResponsibleObserverNameValidityRangeStartHours                               string `json:"ResponsibleObserverNameValidityRangeStartHours"`
		ResponsibleObserverNameValidityRangeStartMinutes                             string `json:"ResponsibleObserverNameValidityRangeStartMinutes"`
		ResponsibleObserverNameValidityRangeStartSeconds                             string `json:"ResponsibleObserverNameValidityRangeStartSeconds"`
		ResponsibleObserverNameValidityRangeStartMills                               string `json:"ResponsibleObserverNameValidityRangeStartMills"`
		ResponsibleObserverNameValidityRangeStartGmtOffset                           string `json:"ResponsibleObserverNameValidityRangeStartGmtOffset"`
		ResponsibleObserverNameValidityRangeStartPrecision                           string `json:"ResponsibleObserverNameValidityRangeStartPrecision"`
		ResponsibleObserverNameValidityRangeEndTime                                  string `json:"ResponsibleObserverNameValidityRangeEndTime"`
		ResponsibleObserverNameValidityRangeEndYear                                  string `json:"ResponsibleObserverNameValidityRangeEndYear"`
		ResponsibleObserverNameValidityRangeEndMonth                                 string `json:"ResponsibleObserverNameValidityRangeEndMonth"`
		ResponsibleObserverNameValidityRangeEndDay                                   string `json:"ResponsibleObserverNameValidityRangeEndDay"`
		ResponsibleObserverNameValidityRangeEndHours                                 string `json:"ResponsibleObserverNameValidityRangeEndHours"`
		ResponsibleObserverNameValidityRangeEndMinutes                               string `json:"ResponsibleObserverNameValidityRangeEndMinutes"`
		ResponsibleObserverNameValidityRangeEndSeconds                               string `json:"ResponsibleObserverNameValidityRangeEndSeconds"`
		ResponsibleObserverNameValidityRangeEndMills                                 string `json:"ResponsibleObserverNameValidityRangeEndMills"`
		ResponsibleObserverNameValidityRangeEndGmtOffset                             string `json:"ResponsibleObserverNameValidityRangeEndGmtOffset"`
		ResponsibleObserverNameValidityRangeEndPrecision                             string `json:"ResponsibleObserverNameValidityRangeEndPrecision"`
		ResponsibleObserverNameAssemblyOrder                                         string `json:"ResponsibleObserverNameAssemblyOrder"`
		ResponsibleObserverEffectiveTime                                             string `json:"ResponsibleObserverEffectiveTime"`
		ResponsibleObserverEffectiveYear                                             string `json:"ResponsibleObserverEffectiveYear"`
		ResponsibleObserverEffectiveMonth                                            string `json:"ResponsibleObserverEffectiveMonth"`
		ResponsibleObserverEffectiveDay                                              string `json:"ResponsibleObserverEffectiveDay"`
		ResponsibleObserverEffectiveHours                                            string `json:"ResponsibleObserverEffectiveHours"`
		ResponsibleObserverEffectiveMinutes                                          string `json:"ResponsibleObserverEffectiveMinutes"`
		ResponsibleObserverEffectiveSeconds                                          string `json:"ResponsibleObserverEffectiveSeconds"`
		ResponsibleObserverEffectiveMills                                            string `json:"ResponsibleObserverEffectiveMills"`
		ResponsibleObserverEffectiveGmtOffset                                        string `json:"ResponsibleObserverEffectiveGmtOffset"`
		ResponsibleObserverEffectivePrecision                                        string `json:"ResponsibleObserverEffectivePrecision"`
		ResponsibleObserverExpirationTime                                            string `json:"ResponsibleObserverExpirationTime"`
		ResponsibleObserverExpirationYear                                            string `json:"ResponsibleObserverExpirationYear"`
		ResponsibleObserverExpirationMonth                                           string `json:"ResponsibleObserverExpirationMonth"`
		ResponsibleObserverExpirationDay                                             string `json:"ResponsibleObserverExpirationDay"`
		ResponsibleObserverExpirationHours                                           string `json:"ResponsibleObserverExpirationHours"`
		ResponsibleObserverExpirationMinutes                                         string `json:"ResponsibleObserverExpirationMinutes"`
		ResponsibleObserverExpirationSeconds                                         string `json:"ResponsibleObserverExpirationSeconds"`
		ResponsibleObserverExpirationMills                                           string `json:"ResponsibleObserverExpirationMills"`
		ResponsibleObserverExpirationGmtOffset                                       string `json:"ResponsibleObserverExpirationGmtOffset"`
		ResponsibleObserverExpirationPrecision                                       string `json:"ResponsibleObserverExpirationPrecision"`
		ResponsibleObserverProfessionalSuffix                                        string `json:"ResponsibleObserverProfessionalSuffix"`
		ResponsibleObserverAssigningJurisdictionIdentifier                           string `json:"ResponsibleObserverAssigningJurisdictionIdentifier"`
		ResponsibleObserverAssigningJurisdictionText                                 string `json:"ResponsibleObserverAssigningJurisdictionText"`
		ResponsibleObserverAssigningJurisdictionNameOfCodingSystem                   string `json:"ResponsibleObserverAssigningJurisdictionNameOfCodingSystem"`
		ResponsibleObserverAssigningJurisdictionAlternateIdentifier                  string `json:"ResponsibleObserverAssigningJurisdictionAlternateIdentifier"`
		ResponsibleObserverAssigningJurisdictionAlternateText                        string `json:"ResponsibleObserverAssigningJurisdictionAlternateText"`
		ResponsibleObserverAssigningJurisdictionNameOfAlternateCodingSystem          string `json:"ResponsibleObserverAssigningJurisdictionNameOfAlternateCodingSystem"`
		ResponsibleObserverAssigningJurisdictionCodingSystemVersionID                string `json:"ResponsibleObserverAssigningJurisdictionCodingSystemVersionID"`
		ResponsibleObserverAssigningJurisdictionAlternateCodingSystemVersionID       string `json:"ResponsibleObserverAssigningJurisdictionAlternateCodingSystemVersionID"`
		ResponsibleObserverAssigningJurisdictionOriginalText                         string `json:"ResponsibleObserverAssigningJurisdictionOriginalText"`
		ResponsibleObserverAssigningAgencyorDepartmentIdentifier                     string `json:"ResponsibleObserverAssigningAgencyorDepartmentIdentifier"`
		ResponsibleObserverAssigningAgencyorDepartmentText                           string `json:"ResponsibleObserverAssigningAgencyorDepartmentText"`
		ResponsibleObserverAssigningAgencyorDepartmentNameOfCodingSystem             string `json:"ResponsibleObserverAssigningAgencyorDepartmentNameOfCodingSystem"`
		ResponsibleObserverAssigningAgencyorDepartmentAlternateIdentifier            string `json:"ResponsibleObserverAssigningAgencyorDepartmentAlternateIdentifier"`
		ResponsibleObserverAssigningAgencyorDepartmentAlternateText                  string `json:"ResponsibleObserverAssigningAgencyorDepartmentAlternateText"`
		ResponsibleObserverAssigningAgencyorDepartmentNameOfAlternateCodingSystem    string `json:"ResponsibleObserverAssigningAgencyorDepartmentNameOfAlternateCodingSystem"`
		ResponsibleObserverAssigningAgencyorDepartmentCodingSystemVersionID          string `json:"ResponsibleObserverAssigningAgencyorDepartmentCodingSystemVersionID"`
		ResponsibleObserverAssigningAgencyorDepartmentAlternateCodingSystemVersionID string `json:"ResponsibleObserverAssigningAgencyorDepartmentAlternateCodingSystemVersionID"`
		ResponsibleObserverAssigningAgencyorDepartmentOriginalText                   string `json:"ResponsibleObserverAssigningAgencyorDepartmentOriginalText"`
		ResponsibleObserverFamilyName                                                string `json:"ResponsibleObserverFamilyName"`
	} `json:"OBXResponsibleObserver"`
}

func (mo *Hl7ObxFormat) fnAddObx(ctx contractapi.TransactionContextInterface) error {

	err := FnValidationCheckStruct(mo)
	if err != nil {
		return err
	}
	mo.MSHOBX = mo.MSHKEY + "_" + "OBX"
	fmt.Println(mo.MSHOBX, "obx key value")
	obrBytes, err := ctx.GetStub().GetState(mo.MSHOBX)
	if obrBytes != nil || err != nil {
		return fmt.Errorf("Key Already Exists in the Network")
	}
	obrBytes, _ = json.Marshal(mo)
	return ctx.GetStub().PutState(mo.MSHOBX, obrBytes)
}
