package main

import (
	"encoding/json"
	"fmt"

	"github.com/hyperledger/fabric-contract-api-go/contractapi"
)

//Hl7ObrFormat ..
type Hl7ObrFormat struct {
	Class                                                          string `json:"$class"`
	OBRKEY                                                         string `json:"OBRKEY"`
	MSHKEY                                                         string `json:"MSHKEY" validate:"required"`
	MSHOBR                                                         string `json:"MSH_OBR" validate:"required"`
	ObservationRequestSetID                                        string `json:"ObservationRequestSetID"`
	PlacerOrderNumberEntityIdentifier                              string `json:"PlacerOrderNumberEntityIdentifier"`
	PlacerOrderNumberNamespaceID                                   string `json:"PlacerOrderNumberNamespaceID"`
	PlacerOrderNumberUniversalID                                   string `json:"PlacerOrderNumberUniversalID"`
	PlacerOrderNumberUniversalIDtype                               string `json:"PlacerOrderNumberUniversalIDtype"`
	FillerOrderNumberEntityIdentifier                              string `json:"FillerOrderNumberEntityIdentifier"`
	FillerOrderNumberNamespaceID                                   string `json:"FillerOrderNumberNamespaceID"`
	FillerOrderNumberUniversalID                                   string `json:"FillerOrderNumberUniversalID"`
	FillerOrderNumberUniversalIDtype                               string `json:"FillerOrderNumberUniversalIDtype"`
	UniversalServiceIDIdentifier                                   string `json:"UniversalServiceIDIdentifier"`
	UniversalServiceIDText                                         string `json:"UniversalServiceIDText"`
	UniversalServiceIDNameOfCodingSystem                           string `json:"UniversalServiceIDNameOfCodingSystem"`
	UniversalServiceIDAlternateIdentifier                          string `json:"UniversalServiceIDAlternateIdentifier"`
	UniversalServiceIDAlternateText                                string `json:"UniversalServiceIDAlternateText"`
	UniversalServiceIDAlternateCodingSystem                        string `json:"UniversalServiceIDAlternateCodingSystem"`
	RequestedDTDTYear                                              string `json:"RequestedDTDTYear"`
	RequestedDTDTMonth                                             string `json:"RequestedDTDTMonth"`
	RequestedDTDTDay                                               string `json:"RequestedDTDTDay"`
	RequestedDTDTHours                                             string `json:"RequestedDTDTHours"`
	RequestedDTDTMinutes                                           string `json:"RequestedDTDTMinutes"`
	RequestedDTDTSeconds                                           string `json:"RequestedDTDTSeconds"`
	RequestedDTDTMillis                                            string `json:"RequestedDTDTMillis"`
	RequestedDTDTGmtOffset                                         string `json:"RequestedDTDTGmtOffset"`
	RequestedDTDTPrecision                                         string `json:"RequestedDTDTPrecision"`
	ObservationStartDTDTYear                                       string `json:"ObservationStartDTDTYear"`
	ObservationStartDTDTMonth                                      string `json:"ObservationStartDTDTMonth"`
	ObservationStartDTDTDay                                        string `json:"ObservationStartDTDTDay"`
	ObservationStartDTDTHours                                      string `json:"ObservationStartDTDTHours"`
	ObservationStartDTDTMinutes                                    string `json:"ObservationStartDTDTMinutes"`
	ObservationStartDTDTSeconds                                    string `json:"ObservationStartDTDTSeconds"`
	ObservationStartDTDTMillis                                     string `json:"ObservationStartDTDTMillis"`
	ObservationStartDTDTGmtOffset                                  string `json:"ObservationStartDTDTGmtOffset"`
	ObservationStartDTDTPrecision                                  string `json:"ObservationStartDTDTPrecision"`
	ObservationEndDTDTYear                                         string `json:"ObservationEndDTDTYear"`
	ObservationEndDTDTMonth                                        string `json:"ObservationEndDTDTMonth"`
	ObservationEndDTDTDay                                          string `json:"ObservationEndDTDTDay"`
	ObservationEndDTDTHours                                        string `json:"ObservationEndDTDTHours"`
	ObservationEndDTDTMinutes                                      string `json:"ObservationEndDTDTMinutes"`
	ObservationEndDTDTSeconds                                      string `json:"ObservationEndDTDTSeconds"`
	ObservationEndDTDTMillis                                       string `json:"ObservationEndDTDTMillis"`
	ObservationEndDTDTGmtOffset                                    string `json:"ObservationEndDTDTGmtOffset"`
	ObservationEndDTDTPrecision                                    string `json:"ObservationEndDTDTPrecision"`
	CVQuantity                                                     string `json:"CVQuantity"`
	CVUnitsIdentifier                                              string `json:"CVUnitsIdentifier"`
	CVUnitsText                                                    string `json:"CVUnitsText"`
	CVUnitsNameOfCodingSystem                                      string `json:"CVUnitsNameOfCodingSystem"`
	CVUnitsAlternateIdentifier                                     string `json:"CVUnitsAlternateIdentifier"`
	CVUnitsAlternateText                                           string `json:"CVUnitsAlternateText"`
	CVUnitsAlternateCodingSystem                                   string `json:"CVUnitsAlternateCodingSystem"`
	SpecimenActionCode                                             string `json:"SpecimenActionCode"`
	DangerCodeIdentifier                                           string `json:"DangerCodeIdentifier"`
	DangerCodeText                                                 string `json:"DangerCodeText"`
	DangerCodeNameOfCodingSystem                                   string `json:"DangerCodeNameOfCodingSystem"`
	DangerCodeAlternateIdentifier                                  string `json:"DangerCodeAlternateIdentifier"`
	DangerCodeAlternateText                                        string `json:"DangerCodeAlternateText"`
	DangerCodeAlternateCodingSystem                                string `json:"DangerCodeAlternateCodingSystem"`
	RelevantClinicalInfo                                           string `json:"RelevantClinicalInfo"`
	SpecimenRcvdDTYear                                             string `json:"SpecimenRcvdDTYear"`
	SpecimenRcvdDTMonth                                            string `json:"SpecimenRcvdDTMonth"`
	SpecimenRcvdDTDay                                              string `json:"SpecimenRcvdDTDay"`
	SpecimenRcvdDTHours                                            string `json:"SpecimenRcvdDTHours"`
	SpecimenRcvdDTMinutes                                          string `json:"SpecimenRcvdDTMinutes"`
	SpecimenRcvdDTSeconds                                          string `json:"SpecimenRcvdDTSeconds"`
	SpecimenRcvdDTMillis                                           string `json:"SpecimenRcvdDTMillis"`
	SpecimenRcvdDTGmtOffset                                        string `json:"SpecimenRcvdDTGmtOffset"`
	SpecimenRcvdDTPrecision                                        string `json:"SpecimenRcvdDTPrecision"`
	SpecimenSource                                                 string `json:"SpecimenSource"`
	PlacersField1                                                  string `json:"PlacersField1"`
	PlacersField2                                                  string `json:"PlacersField2"`
	FillerField1                                                   string `json:"FillerField1"`
	FillerField2                                                   string `json:"FillerField2"`
	ResultsRptDTYear                                               string `json:"ResultsRptDTYear"`
	ResultsRptDTMonth                                              string `json:"ResultsRptDTMonth"`
	ResultsRptDTDay                                                string `json:"ResultsRptDTDay"`
	ResultsRptDTHours                                              string `json:"ResultsRptDTHours"`
	ResultsRptDTMinutes                                            string `json:"ResultsRptDTMinutes"`
	ResultsRptDTSeconds                                            string `json:"ResultsRptDTSeconds"`
	ResultsRptDTMillis                                             string `json:"ResultsRptDTMillis"`
	ResultsRptDTGmtOffset                                          string `json:"ResultsRptDTGmtOffset"`
	ResultsRptDTPrecision                                          string `json:"ResultsRptDTPrecision"`
	Quantity                                                       string `json:"Quantity"`
	Denomination                                                   string `json:"Denomination"`
	ChargeCodeIdentifier                                           string `json:"ChargeCodeIdentifier"`
	ChargeCodeText                                                 string `json:"ChargeCodeText"`
	ChargeCodeNameOfCodingSystem                                   string `json:"ChargeCodeNameOfCodingSystem"`
	ChargeCodeAlternateIdentifier                                  string `json:"ChargeCodeAlternateIdentifier"`
	ChargeCodeAlternateText                                        string `json:"ChargeCodeAlternateText"`
	AlternateCodingSystem                                          string `json:"AlternateCodingSystem"`
	DiagnosticServiceSectID                                        string `json:"DiagnosticServiceSectID"`
	ResultStatus                                                   string `json:"ResultStatus"`
	ParentResult                                                   string `json:"ParentResult"`
	ParentObservationIdentifier                                    string `json:"ParentObservationIdentifier"`
	ParentObservationText                                          string `json:"ParentObservationText"`
	ParentObservationNameOfCodingSystem                            string `json:"ParentObservationNameOfCodingSystem"`
	ParentObservationAlternateIdentifier                           string `json:"ParentObservationAlternateIdentifier"`
	ParentObservationAlternateText                                 string `json:"ParentObservationAlternateText"`
	ParentObservationAlternateCodingSystem                         string `json:"ParentObservationAlternateCodingSystem"`
	ParentObservationSubidentifier                                 string `json:"ParentObservationSubidentifier"`
	ParentObservationValueDescriptor                               string `json:"ParentObservationValueDescriptor"`
	PNPlacerAssignedEntityIdentifier                               string `json:"PNPlacerAssignedEntityIdentifier"`
	PNPlacerAssignedNamespaceID                                    string `json:"PNPlacerAssignedNamespaceID"`
	PNPlacerAssignedUniversalID                                    string `json:"PNPlacerAssignedUniversalID"`
	PNPlacerAssignedUniversalIDType                                string `json:"PNPlacerAssignedUniversalIDType"`
	PNFillerAssignedEntityIdentifier                               string `json:"PNFillerAssignedEntityIdentifier"`
	PNFillerAssignedNamespaceID                                    string `json:"PNFillerAssignedNamespaceID"`
	PNFillerAssignedUniversalID                                    string `json:"PNFillerAssignedUniversalID"`
	PNFillerAssignedUniversalIDType                                string `json:"PNFillerAssignedUniversalIDType"`
	TransportationMode                                             string `json:"TransportationMode"`
	PrincipalResultInterpreter                                     string `json:"PrincipalResultInterpreter"`
	PrincipalResultInterpreterName                                 string `json:"PrincipalResultInterpreterName"`
	PrincipalResultInterpreterIDNumber                             string `json:"PrincipalResultInterpreterIDNumber"`
	PrincipalResultInterpreterFamilyName                           string `json:"PrincipalResultInterpreterFamilyName"`
	PrincipalResultInterpreterGivenName                            string `json:"PrincipalResultInterpreterGivenName"`
	PrincipalResultInterpreterMiddleinitialorname                  string `json:"PrincipalResultInterpreterMiddleinitialorname"`
	PrincipalResultInterpreterSuffix                               string `json:"PrincipalResultInterpreterSuffix"`
	PrincipalResultInterpreterPrefix                               string `json:"PrincipalResultInterpreterPrefix"`
	PrincipalResultInterpreterDegree                               string `json:"PrincipalResultInterpreterDegree"`
	PrincipalResultInterpreterSourcetable                          string `json:"PrincipalResultInterpreterSourcetable"`
	PrincipalResultInterpreterAANamespaceID                        string `json:"PrincipalResultInterpreterAANamespaceID"`
	PrincipalResultInterpreterAAUniversalID                        string `json:"PrincipalResultInterpreterAAUniversalID"`
	PrincipalResultInterpreterAAUniversalIDtype                    string `json:"PrincipalResultInterpreterAAUniversalIDtype"`
	PrincipalResultInterpreterStartDTYear                          string `json:"PrincipalResultInterpreterStartDTYear"`
	PrincipalResultInterpreterStartDTMonth                         string `json:"PrincipalResultInterpreterStartDTMonth"`
	PrincipalResultInterpreterStartDTDay                           string `json:"PrincipalResultInterpreterStartDTDay"`
	PrincipalResultInterpreterStartDTHours                         string `json:"PrincipalResultInterpreterStartDTHours"`
	PrincipalResultInterpreterStartDTMinutes                       string `json:"PrincipalResultInterpreterStartDTMinutes"`
	PrincipalResultInterpreterStartDTSeconds                       string `json:"PrincipalResultInterpreterStartDTSeconds"`
	PrincipalResultInterpreterStartDTMillis                        string `json:"PrincipalResultInterpreterStartDTMillis"`
	PrincipalResultInterpreterStartDTGmtOffset                     string `json:"PrincipalResultInterpreterStartDTGmtOffset"`
	PrincipalResultInterpreterStartDTPrecision                     string `json:"PrincipalResultInterpreterStartDTPrecision"`
	PrincipalResultInterpreterEndDTYear                            string `json:"PrincipalResultInterpreterEndDTYear"`
	PrincipalResultInterpreterEndDTMonth                           string `json:"PrincipalResultInterpreterEndDTMonth"`
	PrincipalResultInterpreterEndDTDay                             string `json:"PrincipalResultInterpreterEndDTDay"`
	PrincipalResultInterpreterEndDTHours                           string `json:"PrincipalResultInterpreterEndDTHours"`
	PrincipalResultInterpreterEndDTMinutes                         string `json:"PrincipalResultInterpreterEndDTMinutes"`
	PrincipalResultInterpreterEndDTSeconds                         string `json:"PrincipalResultInterpreterEndDTSeconds"`
	PrincipalResultInterpreterEndDTMillis                          string `json:"PrincipalResultInterpreterEndDTMillis"`
	PrincipalResultInterpreterEndDTGmtOffset                       string `json:"PrincipalResultInterpreterEndDTGmtOffset"`
	PrincipalResultInterpreterPrecision                            string `json:"PrincipalResultInterpreterPrecision"`
	PrincipalResultInterpreterpointofcare                          string `json:"PrincipalResultInterpreterpointofcare"`
	PrincipalResultInterpreterroom                                 string `json:"PrincipalResultInterpreterroom"`
	PrincipalResultInterpreterbed                                  string `json:"PrincipalResultInterpreterbed"`
	PrincipalResultInterpreterFacilitynamespaceID                  string `json:"PrincipalResultInterpreterFacilitynamespaceID"`
	PrincipalResultInterpreterFacilityuniversalID                  string `json:"PrincipalResultInterpreterFacilityuniversalID"`
	PrincipalResultInterpreterFacilityuniversalIDtype              string `json:"PrincipalResultInterpreterFacilityuniversalIDtype"`
	PrincipalResultInterpreterlocationstatus                       string `json:"PrincipalResultInterpreterlocationstatus"`
	PrincipalResultInterpreterpersonlocationtype                   string `json:"PrincipalResultInterpreterpersonlocationtype"`
	PrincipalResultInterpreterbuilding                             string `json:"PrincipalResultInterpreterbuilding"`
	PrincipalResultInterpreterfloor                                string `json:"PrincipalResultInterpreterfloor"`
	ScheduledDTDTYear                                              string `json:"ScheduledDTDTYear"`
	ScheduledDTDTMonth                                             string `json:"ScheduledDTDTMonth"`
	ScheduledDTDTDay                                               string `json:"ScheduledDTDTDay"`
	ScheduledDTDTHours                                             string `json:"ScheduledDTDTHours"`
	ScheduledDTDTMinutes                                           string `json:"ScheduledDTDTMinutes"`
	ScheduledDTDTSeconds                                           string `json:"ScheduledDTDTSeconds"`
	ScheduledDTDTMillis                                            string `json:"ScheduledDTDTMillis"`
	ScheduledDTDTGmtOffset                                         string `json:"ScheduledDTDTGmtOffset"`
	ScheduledDTDTPrecision                                         string `json:"ScheduledDTDTPrecision"`
	TransportArranResponsibilityIdentifier                         string `json:"TransportArranResponsibilityIdentifier"`
	TransportArranResponsibilityText                               string `json:"TransportArranResponsibilityText"`
	TransportArranResponsibilityNameOfCodingSystem                 string `json:"TransportArranResponsibilityNameOfCodingSystem"`
	TransportArranResponsibilityAlternateIdentifier                string `json:"TransportArranResponsibilityAlternateIdentifier"`
	TransportArranResponsibilityAlternateText                      string `json:"TransportArranResponsibilityAlternateText"`
	TransportArranResponsibilityAlternateCodingSystem              string `json:"TransportArranResponsibilityAlternateCodingSystem"`
	TransportArranged                                              string `json:"TransportArranged"`
	EscortRequired                                                 string `json:"EscortRequired"`
	ProcedureCodeIdentifier                                        string `json:"ProcedureCodeIdentifier"`
	ProcedureCodeText                                              string `json:"ProcedureCodeText"`
	ProcedureCodeNameOfCodingSystem                                string `json:"ProcedureCodeNameOfCodingSystem"`
	ProcedureCodeAlternateIdentifier                               string `json:"ProcedureCodeAlternateIdentifier"`
	ProcedureCodeAlternateText                                     string `json:"ProcedureCodeAlternateText"`
	ProcedureCodeAlternateCodingSystem                             string `json:"ProcedureCodeAlternateCodingSystem"`
	DuplicateProcedureReasonIdentifier                             string `json:"DuplicateProcedureReasonIdentifier"`
	DuplicateProcedureReasonText                                   string `json:"DuplicateProcedureReasonText"`
	DuplicateProcedureReasonNameOfCodingSystem                     string `json:"DuplicateProcedureReasonNameOfCodingSystem"`
	DuplicateProcedureReasonAlternateIdentifier                    string `json:"DuplicateProcedureReasonAlternateIdentifier"`
	DuplicateProcedureReasonAlternateText                          string `json:"DuplicateProcedureReasonAlternateText"`
	DuplicateProcedureReasonNameOfAlternateCodingSystem            string `json:"DuplicateProcedureReasonNameOfAlternateCodingSystem"`
	DuplicateProcedureReasonCodingSystemVersionID                  string `json:"DuplicateProcedureReasonCodingSystemVersionID"`
	DuplicateProcedureReasonAlternateCodingSystemVersionID         string `json:"DuplicateProcedureReasonAlternateCodingSystemVersionID"`
	DuplicateProcedureReasonOriginalText                           string `json:"DuplicateProcedureReasonOriginalText"`
	ChargetoPractice                                               string `json:"ChargetoPractice"`
	ParentNumber                                                   string `json:"ParentNumber"`
	ResultHandling                                                 string `json:"ResultHandling"`
	Priority                                                       string `json:"Priority"`
	RequestedDTDTTime                                              string `json:"RequestedDTDTTime"`
	ObservationStartDTDTTime                                       string `json:"ObservationStartDTDTTime"`
	ObservationEndDTDTTime                                         string `json:"ObservationEndDTDTTime"`
	SpecimenRcvdDTTime                                             string `json:"SpecimenRcvdDTTime"`
	ResultsRptDTTime                                               string `json:"ResultsRptDTTime"`
	PrincipalResultInterpreterStartDTTime                          string `json:"PrincipalResultInterpreterStartDTTime"`
	PrincipalResultInterpreterEndDTTime                            string `json:"PrincipalResultInterpreterEndDTTime"`
	ScheduledDTDTTime                                              string `json:"ScheduledDTDTTime"`
	ParentUniversalServiceIdentifier                               string `json:"ParentUniversalServiceIdentifier"`
	ParentUniversalServiceIdentifierText                           string `json:"ParentUniversalServiceIdentifierText"`
	ParentUniversalServiceIdentifierNameOfCodingSystem             string `json:"ParentUniversalServiceIdentifierNameOfCodingSystem"`
	ParentUniversalServiceIdentifierAlternateIdentifier            string `json:"ParentUniversalServiceIdentifierAlternateIdentifier"`
	ParentUniversalServiceIdentifierAlternateText                  string `json:"ParentUniversalServiceIdentifierAlternateText"`
	ParentUniversalServiceIdentifierNameOfAlternateCodingSystem    string `json:"ParentUniversalServiceIdentifierNameOfAlternateCodingSystem"`
	ParentUniversalServiceIdentifierCodingSystemVersionID          string `json:"ParentUniversalServiceIdentifierCodingSystemVersionID"`
	ParentUniversalServiceIdentifierAlternateCodingSystemVersionID string `json:"ParentUniversalServiceIdentifierAlternateCodingSystemVersionID"`
	ParentUniversalServiceIdentifierOriginalText                   string `json:"ParentUniversalServiceIdentifierOriginalText"`
	SpecimenSourceNameorCodeIdentifier                             string `json:"SpecimenSourceNameorCodeIdentifier"`
	SpecimenSourceNameorCodeText                                   string `json:"SpecimenSourceNameorCodeText"`
	SpecimenSourceNameorCodeNameOfCodingSystem                     string `json:"SpecimenSourceNameorCodeNameOfCodingSystem"`
	SpecimenSourceNameorCodeAlternateIdentifier                    string `json:"SpecimenSourceNameorCodeAlternateIdentifier"`
	SpecimenSourceNameorCodeAlternateText                          string `json:"SpecimenSourceNameorCodeAlternateText"`
	SpecimenSourceNameorCodeNameOfAlternateCodingSystem            string `json:"SpecimenSourceNameorCodeNameOfAlternateCodingSystem"`
	SpecimenSourceNameorCodeCodingSystemVersionID                  string `json:"SpecimenSourceNameorCodeCodingSystemVersionID"`
	SpecimenSourceNameorCodeAlternateCodingSystemVersionID         string `json:"SpecimenSourceNameorCodeAlternateCodingSystemVersionID"`
	SpecimenSourceNameorCodeOriginalText                           string `json:"SpecimenSourceNameorCodeOriginalText"`
	AdditivesIdentifier                                            string `json:"AdditivesIdentifier"`
	AdditivesText                                                  string `json:"AdditivesText"`
	AdditivesNameOfCodingSystem                                    string `json:"AdditivesNameOfCodingSystem"`
	AdditivesAlternateIdentifier                                   string `json:"AdditivesAlternateIdentifier"`
	AdditivesAlternateText                                         string `json:"AdditivesAlternateText"`
	AdditivesNameOfAlternateCodingSystem                           string `json:"AdditivesNameOfAlternateCodingSystem"`
	AdditivesCodingSystemVersionID                                 string `json:"AdditivesCodingSystemVersionID"`
	AdditivesAlternateCodingSystemVersionID                        string `json:"AdditivesAlternateCodingSystemVersionID"`
	AdditivesOriginalText                                          string `json:"AdditivesOriginalText"`
	SpecimenCollectionMethod                                       string `json:"SpecimenCollectionMethod"`
	BodySiteIdentifier                                             string `json:"BodySiteIdentifier"`
	BodySiteText                                                   string `json:"BodySiteText"`
	BodySiteNameOfCodingSystem                                     string `json:"BodySiteNameOfCodingSystem"`
	BodySiteAlternateIdentifier                                    string `json:"BodySiteAlternateIdentifier"`
	BodySiteAlternateText                                          string `json:"BodySiteAlternateText"`
	BodySiteNameOfAlternateCodingSystem                            string `json:"BodySiteNameOfAlternateCodingSystem"`
	BodySiteCodingSystemVersionID                                  string `json:"BodySiteCodingSystemVersionID"`
	BodySiteAlternateCodingSystemVersionID                         string `json:"BodySiteAlternateCodingSystemVersionID"`
	BodySiteOriginalText                                           string `json:"BodySiteOriginalText"`
	SiteModifierIdentifier                                         string `json:"SiteModifierIdentifier"`
	SiteModifierText                                               string `json:"SiteModifierText"`
	SiteModifierNameOfCodingSystem                                 string `json:"SiteModifierNameOfCodingSystem"`
	SiteModifierAlternateIdentifier                                string `json:"SiteModifierAlternateIdentifier"`
	SiteModifierAlternateText                                      string `json:"SiteModifierAlternateText"`
	SiteModifierNameOfAlternateCodingSystem                        string `json:"SiteModifierNameOfAlternateCodingSystem"`
	SiteModifierCodingSystemVersionID                              string `json:"SiteModifierCodingSystemVersionID"`
	SiteModifierAlternateCodingSystemVersionID                     string `json:"SiteModifierAlternateCodingSystemVersionID"`
	SiteModifierOriginalText                                       string `json:"SiteModifierOriginalText"`
	CollectionMethodModifierCodeIdentifier                         string `json:"CollectionMethodModifierCodeIdentifier"`
	CollectionMethodModifierCodeText                               string `json:"CollectionMethodModifierCodeText"`
	CollectionMethodModifierCodeNameOfCodingSystem                 string `json:"CollectionMethodModifierCodeNameOfCodingSystem"`
	CollectionMethodModifierCodeAlternateIdentifier                string `json:"CollectionMethodModifierCodeAlternateIdentifier"`
	CollectionMethodModifierCodeAlternateText                      string `json:"CollectionMethodModifierCodeAlternateText"`
	CollectionMethodModifierCodeNameOfAlternateCodingSystem        string `json:"CollectionMethodModifierCodeNameOfAlternateCodingSystem"`
	CollectionMethodModifierCodeCodingSystemVersionID              string `json:"CollectionMethodModifierCodeCodingSystemVersionID"`
	CollectionMethodModifierCodeAlternateCodingSystemVersionID     string `json:"CollectionMethodModifierCodeAlternateCodingSystemVersionID"`
	CollectionMethodModifierCodeOriginalText                       string `json:"CollectionMethodModifierCodeOriginalText"`
	SpecimenRoleIdentifier                                         string `json:"SpecimenRoleIdentifier"`
	SpecimenRoleText                                               string `json:"SpecimenRoleText"`
	SpecimenRoleNameOfCodingSystem                                 string `json:"SpecimenRoleNameOfCodingSystem"`
	SpecimenRoleAlternateIdentifier                                string `json:"SpecimenRoleAlternateIdentifier"`
	SpecimenRoleAlternateText                                      string `json:"SpecimenRoleAlternateText"`
	SpecimenRoleNameOfAlternateCodingSystem                        string `json:"SpecimenRoleNameOfAlternateCodingSystem"`
	SpecimenRoleCodingSystemVersionID                              string `json:"SpecimenRoleCodingSystemVersionID"`
	SpecimenRoleAlternateCodingSystemVersionID                     string `json:"SpecimenRoleAlternateCodingSystemVersionID"`
	SpecimenRoleOriginalText                                       string `json:"SpecimenRoleOriginalText"`
	Additives                                                      string `json:"Additives"`
	ORCKey                                                         string `json:"ORCKey"`
	OBRAssistantResultInterpreter                                  struct {
		Class                                             string `json:"$class"`
		AssistantResultInterpreterIDNumber                string `json:"AssistantResultInterpreterIDNumber"`
		AssistantResultInterpreterFamilyName              string `json:"AssistantResultInterpreterFamilyName"`
		AssistantResultInterpreterGivenName               string `json:"AssistantResultInterpreterGivenName"`
		AssistantResultInterpreterMiddleinitialorname     string `json:"AssistantResultInterpreterMiddleinitialorname"`
		AssistantResultInterpreterSuffix                  string `json:"AssistantResultInterpreterSuffix"`
		AssistantResultInterpreterPrefix                  string `json:"AssistantResultInterpreterPrefix"`
		AssistantResultInterpreterDegree                  string `json:"AssistantResultInterpreterDegree"`
		AssistantResultInterpreterSourcetable             string `json:"AssistantResultInterpreterSourcetable"`
		AssistantResultInterpreterAANamespaceID           string `json:"AssistantResultInterpreterAANamespaceID"`
		AssistantResultInterpreterAAUniversalID           string `json:"AssistantResultInterpreterAAUniversalID"`
		AssistantResultInterpreterAAUniversalIDtype       string `json:"AssistantResultInterpreterAAUniversalIDtype"`
		AssistantResultInterpreterStartDTYear             string `json:"AssistantResultInterpreterStartDTYear"`
		AssistantResultInterpreterStartDTMonth            string `json:"AssistantResultInterpreterStartDTMonth"`
		AssistantResultInterpreterStartDTDay              string `json:"AssistantResultInterpreterStartDTDay"`
		AssistantResultInterpreterStartDTHours            string `json:"AssistantResultInterpreterStartDTHours"`
		AssistantResultInterpreterStartDTMinutes          string `json:"AssistantResultInterpreterStartDTMinutes"`
		AssistantResultInterpreterStartDTSeconds          string `json:"AssistantResultInterpreterStartDTSeconds"`
		AssistantResultInterpreterStartDTMillis           string `json:"AssistantResultInterpreterStartDTMillis"`
		AssistantResultInterpreterStartDTGmtOffset        string `json:"AssistantResultInterpreterStartDTGmtOffset"`
		AssistantResultInterpreterStartDTPrecision        string `json:"AssistantResultInterpreterStartDTPrecision"`
		AssistantResultInterpreterEndDTYear               string `json:"AssistantResultInterpreterEndDTYear"`
		AssistantResultInterpreterEndDTMonth              string `json:"AssistantResultInterpreterEndDTMonth"`
		AssistantResultInterpreterEndDTDay                string `json:"AssistantResultInterpreterEndDTDay"`
		AssistantResultInterpreterEndDTHours              string `json:"AssistantResultInterpreterEndDTHours"`
		AssistantResultInterpreterEndDTMinutes            string `json:"AssistantResultInterpreterEndDTMinutes"`
		AssistantResultInterpreterEndDTSeconds            string `json:"AssistantResultInterpreterEndDTSeconds"`
		AssistantResultInterpreterEndDTMillis             string `json:"AssistantResultInterpreterEndDTMillis"`
		AssistantResultInterpreterEndDTGmtOffset          string `json:"AssistantResultInterpreterEndDTGmtOffset"`
		AssistantResultInterpreterPrecision               string `json:"AssistantResultInterpreterPrecision"`
		AssistantResultInterpreterpointofcare             string `json:"AssistantResultInterpreterpointofcare"`
		AssistantResultInterpreterroom                    string `json:"AssistantResultInterpreterroom"`
		AssistantResultInterpreterbed                     string `json:"AssistantResultInterpreterbed"`
		AssistantResultInterpreterFacilitynamespaceID     string `json:"AssistantResultInterpreterFacilitynamespaceID"`
		AssistantResultInterpreterFacilityuniversalID     string `json:"AssistantResultInterpreterFacilityuniversalID"`
		AssistantResultInterpreterFacilityuniversalIDtype string `json:"AssistantResultInterpreterFacilityuniversalIDtype"`
		AssistantResultInterpreterlocationstatus          string `json:"AssistantResultInterpreterlocationstatus"`
		AssistantResultInterpreterpersonlocationtype      string `json:"AssistantResultInterpreterpersonlocationtype"`
		AssistantResultInterpreterbuilding                string `json:"AssistantResultInterpreterbuilding"`
		AssistantResultInterpreterfloor                   string `json:"AssistantResultInterpreterfloor"`
		AssistantResultInterpreter                        string `json:"AssistantResultInterpreter"`
		AssistantResultInterpreterStartDTTime             string `json:"AssistantResultInterpreterStartDTTime"`
		AssistantResultInterpreterEndDTTime               string `json:"AssistantResultInterpreterEndDTTime"`
	} `json:"OBRAssistantResultInterpreter"`
	OBRCollectorComment struct {
		Class                                 string `json:"$class"`
		CollectorCommentIdentifier            string `json:"CollectorCommentIdentifier"`
		CollectorCommentText                  string `json:"CollectorCommentText"`
		CollectorCommentNameOfCodingSystem    string `json:"CollectorCommentNameOfCodingSystem"`
		CollectorCommentAlternateIdentifier   string `json:"CollectorCommentAlternateIdentifier"`
		CollectorCommentAlternateText         string `json:"CollectorCommentAlternateText"`
		CollectorCommentAlternateCodingSystem string `json:"CollectorCommentAlternateCodingSystem"`
	} `json:"OBRCollectorComment"`
	OBRCollectorIdentifier struct {
		Class                                                         string `json:"$class"`
		CollectorIdentifierIDNumber                                   string `json:"CollectorIdentifierIDNumber"`
		CollectorIdentifierFamilyName                                 string `json:"CollectorIdentifierFamilyName"`
		CollectorIdentifierFNPrefix                                   string `json:"CollectorIdentifierFNPrefix"`
		CollectorIdentifierFNOwnFamilyName                            string `json:"CollectorIdentifierFNOwnFamilyName"`
		CollectorIdentifierFNPrefixFromPartnerSpouse                  string `json:"CollectorIdentifierFNPrefixFromPartnerSpouse"`
		CollectorIdentifierFNFrompartnerspouse                        string `json:"CollectorIdentifierFNFrompartnerspouse"`
		CollectorIdentifierGivenName                                  string `json:"CollectorIdentifierGivenName"`
		CollectorIdentifierMiddleinitialorname                        string `json:"CollectorIdentifierMiddleinitialorname"`
		CollectorIdentifierSuffix                                     string `json:"CollectorIdentifierSuffix"`
		CollectorIdentifierPrefix                                     string `json:"CollectorIdentifierPrefix"`
		CollectorIdentifierDegree                                     string `json:"CollectorIdentifierDegree"`
		CollectorIdentifierSourcetable                                string `json:"CollectorIdentifierSourcetable"`
		CollectorIdentifierAANamespaceID                              string `json:"CollectorIdentifierAANamespaceID"`
		CollectorIdentifierAAUniversalID                              string `json:"CollectorIdentifierAAUniversalID"`
		CollectorIdentifierAAUniversalIDtype                          string `json:"CollectorIdentifierAAUniversalIDtype"`
		CollectorIdentifierNametypecode                               string `json:"CollectorIdentifierNametypecode"`
		CollectorIdentifierIdentifiercheckdigit                       string `json:"CollectorIdentifierIdentifiercheckdigit"`
		CollectorIdentifierCodeidentifyingthecheckdigitschemeemployed string `json:"CollectorIdentifierCodeidentifyingthecheckdigitschemeemployed"`
		CollectorIdentifierIdentifiertypecode                         string `json:"CollectorIdentifierIdentifiertypecode"`
		CollectorIdentifierAFNamespaceID                              string `json:"CollectorIdentifierAFNamespaceID"`
		CollectorIdentifierAFUniversalID                              string `json:"CollectorIdentifierAFUniversalID"`
		CollectorIdentifierAFUniversalIDtype                          string `json:"CollectorIdentifierAFUniversalIDtype"`
		CollectorIdentifierNamerepresentationcode                     string `json:"CollectorIdentifierNamerepresentationcode"`
		CollectorIdentifierNCIdentifier                               string `json:"CollectorIdentifierNCIdentifier"`
		CollectorIdentifierNCText                                     string `json:"CollectorIdentifierNCText"`
		CollectorIdentifierNCNameOfCodingSystem                       string `json:"CollectorIdentifierNCNameOfCodingSystem"`
		CollectorIdentifierNCAlternateIdentifier                      string `json:"CollectorIdentifierNCAlternateIdentifier"`
		CollectorIdentifierNCAlternateText                            string `json:"CollectorIdentifierNCAlternateText"`
		CollectorIdentifierNCAlternateCodingSystem                    string `json:"CollectorIdentifierNCAlternateCodingSystem"`
		CollectorIdentifierNVStartDateYear                            string `json:"CollectorIdentifierNVStartDateYear"`
		CollectorIdentifierNVStartDateMonth                           string `json:"CollectorIdentifierNVStartDateMonth"`
		CollectorIdentifierNVStartDateDay                             string `json:"CollectorIdentifierNVStartDateDay"`
		CollectorIdentifierNVStartDateHours                           string `json:"CollectorIdentifierNVStartDateHours"`
		CollectorIdentifierNVStartDateMinutes                         string `json:"CollectorIdentifierNVStartDateMinutes"`
		CollectorIdentifierNVStartDateSeconds                         string `json:"CollectorIdentifierNVStartDateSeconds"`
		CollectorIdentifierNVStartDateMillis                          string `json:"CollectorIdentifierNVStartDateMillis"`
		CollectorIdentifierNVStartDateGmtOffset                       string `json:"CollectorIdentifierNVStartDateGmtOffset"`
		CollectorIdentifierNVStartDatePrecision                       string `json:"CollectorIdentifierNVStartDatePrecision"`
		CollectorIdentifierNVEndDateYear                              string `json:"CollectorIdentifierNVEndDateYear"`
		CollectorIdentifierNVEndDateMonth                             string `json:"CollectorIdentifierNVEndDateMonth"`
		CollectorIdentifierNVEndDateDay                               string `json:"CollectorIdentifierNVEndDateDay"`
		CollectorIdentifierNVEndDateHours                             string `json:"CollectorIdentifierNVEndDateHours"`
		CollectorIdentifierNVEndDateMinutes                           string `json:"CollectorIdentifierNVEndDateMinutes"`
		CollectorIdentifierNVEndDateSeconds                           string `json:"CollectorIdentifierNVEndDateSeconds"`
		CollectorIdentifierNVEndDateMillis                            string `json:"CollectorIdentifierNVEndDateMillis"`
		CollectorIdentifierNVEndDateGmtOffset                         string `json:"CollectorIdentifierNVEndDateGmtOffset"`
		CollectorIdentifierNVEndDatePrecision                         string `json:"CollectorIdentifierNVEndDatePrecision"`
		CollectorIdentifierNameassemblyorder                          string `json:"CollectorIdentifierNameassemblyorder"`
		CollectorIdentifierEffDTYear                                  string `json:"CollectorIdentifierEffDTYear"`
		CollectorIdentifierEffDTMonth                                 string `json:"CollectorIdentifierEffDTMonth"`
		CollectorIdentifierEffDTDay                                   string `json:"CollectorIdentifierEffDTDay"`
		CollectorIdentifierEffDTHours                                 string `json:"CollectorIdentifierEffDTHours"`
		CollectorIdentifierEffDTMinutes                               string `json:"CollectorIdentifierEffDTMinutes"`
		CollectorIdentifierEffDTSeconds                               string `json:"CollectorIdentifierEffDTSeconds"`
		CollectorIdentifierEffDTMillis                                string `json:"CollectorIdentifierEffDTMillis"`
		CollectorIdentifierEffDTGmtOffset                             string `json:"CollectorIdentifierEffDTGmtOffset"`
		CollectorIdentifierEffDTPrecision                             string `json:"CollectorIdentifierEffDTPrecision"`
		CollectorIdentifierExpDTYear                                  string `json:"CollectorIdentifierExpDTYear"`
		CollectorIdentifierExpDTMonth                                 string `json:"CollectorIdentifierExpDTMonth"`
		CollectorIdentifierExpDTDay                                   string `json:"CollectorIdentifierExpDTDay"`
		CollectorIdentifierExpDTHours                                 string `json:"CollectorIdentifierExpDTHours"`
		CollectorIdentifierExpDTMinutes                               string `json:"CollectorIdentifierExpDTMinutes"`
		CollectorIdentifierExpDTSeconds                               string `json:"CollectorIdentifierExpDTSeconds"`
		CollectorIdentifierExpDTMillis                                string `json:"CollectorIdentifierExpDTMillis"`
		CollectorIdentifierExpDTGmtOffset                             string `json:"CollectorIdentifierExpDTGmtOffset"`
		CollectorIdentifierExpDTPrecision                             string `json:"CollectorIdentifierExpDTPrecision"`
		CollectorIdentifierExpDTProfessionalSuffix                    string `json:"CollectorIdentifierExpDTProfessionalSuffix"`
		CollectorIdentifierAJIdentifier                               string `json:"CollectorIdentifierAJIdentifier"`
		CollectorIdentifierAJText                                     string `json:"CollectorIdentifierAJText"`
		CollectorIdentifierAJNameOfCodingSystem                       string `json:"CollectorIdentifierAJNameOfCodingSystem"`
		CollectorIdentifierAJAlternateIdentifier                      string `json:"CollectorIdentifierAJAlternateIdentifier"`
		CollectorIdentifierAJAlternateText                            string `json:"CollectorIdentifierAJAlternateText"`
		CollectorIdentifierAJNameOfAlternateCodingSystem              string `json:"CollectorIdentifierAJNameOfAlternateCodingSystem"`
		CollectorIdentifierAJCodingSystemVersionID                    string `json:"CollectorIdentifierAJCodingSystemVersionID"`
		CollectorIdentifierAJAlternateCodingSystemVersionID           string `json:"CollectorIdentifierAJAlternateCodingSystemVersionID"`
		CollectorIdentifierAJOriginalText                             string `json:"CollectorIdentifierAJOriginalText"`
		CollectorIdentifierAADIdentifier                              string `json:"CollectorIdentifierAADIdentifier"`
		CollectorIdentifierAADText                                    string `json:"CollectorIdentifierAADText"`
		CollectorIdentifierAADNameOfCodingSystem                      string `json:"CollectorIdentifierAADNameOfCodingSystem"`
		CollectorIdentifierAADAlternateIdentifier                     string `json:"CollectorIdentifierAADAlternateIdentifier"`
		CollectorIdentifierAADAlternateText                           string `json:"CollectorIdentifierAADAlternateText"`
		CollectorIdentifierAADNameOfAlternateCodingSystem             string `json:"CollectorIdentifierAADNameOfAlternateCodingSystem"`
		CollectorIdentifierAADCodingSystemVersionID                   string `json:"CollectorIdentifierAADCodingSystemVersionID"`
		CollectorIdentifierAADAlternateCodingSystemVersionID          string `json:"CollectorIdentifierAADAlternateCodingSystemVersionID"`
		CollectorIdentifierAADOriginalText                            string `json:"CollectorIdentifierAADOriginalText"`
		CollectorIdentifierNVStartDateTime                            string `json:"CollectorIdentifierNVStartDateTime"`
		CollectorIdentifierNVEndDateTime                              string `json:"CollectorIdentifierNVEndDateTime"`
		CollectorIdentifierEffDTTime                                  string `json:"CollectorIdentifierEffDTTime"`
		CollectorIdentifierExpDTTime                                  string `json:"CollectorIdentifierExpDTTime"`
	} `json:"OBRCollectorIdentifier"`
	OBRFillerSupServiceInfo struct {
		Class                                         string `json:"$class"`
		FillerSupServiceInfoCodeIdentifier            string `json:"FillerSupServiceInfoCodeIdentifier"`
		FillerSupServiceInfoCodeText                  string `json:"FillerSupServiceInfoCodeText"`
		FillerSupServiceInfoCodeNameOfCodingSystem    string `json:"FillerSupServiceInfoCodeNameOfCodingSystem"`
		FillerSupServiceInfoCodeAlternateIdentifier   string `json:"FillerSupServiceInfoCodeAlternateIdentifier"`
		FillerSupServiceInfoCodeAlternateText         string `json:"FillerSupServiceInfoCodeAlternateText"`
		FillerSupServiceInfoCodeAlternateCodingSystem string `json:"FillerSupServiceInfoCodeAlternateCodingSystem"`
	} `json:"OBRFillerSupServiceInfo"`
	OBROrderCallbackPhNum struct {
		Class                                                  string `json:"$class"`
		OrderCallBackPhoneNumberST                             string `json:"OrderCallBackPhoneNumberST"`
		OrderCallBackPhoneNumberTelecommunicationUseCode       string `json:"OrderCallBackPhoneNumberTelecommunicationUseCode"`
		OrderCallBackPhoneNumberTelecommunicationEquipmentType string `json:"OrderCallBackPhoneNumberTelecommunicationEquipmentType"`
		OrderCallBackPhoneNumberEmailAddress                   string `json:"OrderCallBackPhoneNumberEmailAddress"`
		OrderCallBackPhoneNumberCountryCode                    string `json:"OrderCallBackPhoneNumberCountryCode"`
		OrderCallBackPhoneNumberAreaOrCityCode                 string `json:"OrderCallBackPhoneNumberAreaOrCityCode"`
		OrderCallBackPhoneNumberPhoneNumber                    string `json:"OrderCallBackPhoneNumberPhoneNumber"`
		OrderCallBackPhoneNumberExtension                      string `json:"OrderCallBackPhoneNumberExtension"`
		OrderCallBackPhoneNumberAnyText                        string `json:"OrderCallBackPhoneNumberAnyText"`
		OrderCallBackPhoneNumberExtensionPrefix                string `json:"OrderCallBackPhoneNumberExtensionPrefix"`
		OrderCallBackPhoneNumberSpeedDialCode                  string `json:"OrderCallBackPhoneNumberSpeedDialCode"`
		OrderCallBackPhoneNumberUnformattedTelephonenumber     string `json:"OrderCallBackPhoneNumberUnformattedTelephonenumber"`
	} `json:"OBROrderCallbackPhNum"`
	OBRProcedureCodeModifier struct {
		Class                                          string `json:"$class"`
		ProcedureCodeModifierCodeIdentifier            string `json:"ProcedureCodeModifierCodeIdentifier"`
		ProcedureCodeModifierCodeText                  string `json:"ProcedureCodeModifierCodeText"`
		ProcedureCodeModifierCodeNameOfCodingSystem    string `json:"ProcedureCodeModifierCodeNameOfCodingSystem"`
		ProcedureCodeModifierCodeAlternateIdentifier   string `json:"ProcedureCodeModifierCodeAlternateIdentifier"`
		ProcedureCodeModifierCodeAlternateText         string `json:"ProcedureCodeModifierCodeAlternateText"`
		ProcedureCodeModifierCodeAlternateCodingSystem string `json:"ProcedureCodeModifierCodeAlternateCodingSystem"`
	} `json:"OBRProcedureCodeModifier"`
	OBRQuantity struct {
		Class                              string `json:"$class"`
		Quantity                           string `json:"Quantity"`
		UnitsIdentifier                    string `json:"UnitsIdentifier"`
		UnitsText                          string `json:"UnitsText"`
		UnitsNameOfCodingSystem            string `json:"UnitsNameOfCodingSystem"`
		UnitsAlternateIdentifier           string `json:"UnitsAlternateIdentifier"`
		UnitsAlternateText                 string `json:"UnitsAlternateText"`
		UnitsAlternateCodingSystem         string `json:"UnitsAlternateCodingSystem"`
		Interval                           string `json:"Interval"`
		Duration                           string `json:"duration"`
		StartDTYear                        string `json:"StartDTYear"`
		StartDTMonth                       string `json:"StartDTMonth"`
		StartDTDay                         string `json:"StartDTDay"`
		StartDTHours                       string `json:"StartDTHours"`
		StartDTMinutes                     string `json:"StartDTMinutes"`
		StartDTSeconds                     string `json:"StartDTSeconds"`
		StartDTMillis                      string `json:"StartDTMillis"`
		StartDTGmtOffset                   string `json:"StartDTGmtOffset"`
		StartDTPrecision                   string `json:"StartDTPrecision"`
		EndDTYear                          string `json:"EndDTYear"`
		EndDTMonth                         string `json:"EndDTMonth"`
		EndDTDay                           string `json:"EndDTDay"`
		EndDTHours                         string `json:"EndDTHours"`
		EndDTMinutes                       string `json:"EndDTMinutes"`
		EndDTSeconds                       string `json:"EndDTSeconds"`
		EndDTMillis                        string `json:"EndDTMillis"`
		EndDTGmtOffset                     string `json:"EndDTGmtOffset"`
		EndDTPrecision                     string `json:"EndDTPrecision"`
		Priority                           string `json:"Priority"`
		Condition                          string `json:"Condition"`
		Text                               string `json:"Text"`
		Conjunction                        string `json:"Conjunction"`
		OrderingSequence                   string `json:"OrderingSequence"`
		OrderQuantityIdentifier            string `json:"OrderQuantityIdentifier"`
		OrderQuantityText                  string `json:"OrderQuantityText"`
		OrderQuantityNameOfCodingSystem    string `json:"OrderQuantityNameOfCodingSystem"`
		OrderQuantityAlternateIdentifier   string `json:"OrderQuantityAlternateIdentifier"`
		OrderQuantityAlternateText         string `json:"OrderQuantityAlternateText"`
		OrderQuantityAlternateCodingSystem string `json:"OrderQuantityAlternateCodingSystem"`
		OrderQuantityTotalOccurrences      string `json:"OrderQuantityTotalOccurrences"`
		StartDTTime                        string `json:"StartDTTime"`
		EndDTTime                          string `json:"EndDTTime"`
		SequenceResultsFlag                string `json:"SequenceResultsFlag"`
		PlacerOrderNumberEntityIdentifier  string `json:"PlacerOrderNumberEntityIdentifier"`
		PlacerOrderNumberNamespaceID       string `json:"PlacerOrderNumberNamespaceID"`
		FillerOrderNumberEntityIdentifier  string `json:"FillerOrderNumberEntityIdentifier"`
		FillerOrderNumberNamespaceID       string `json:"FillerOrderNumberNamespaceID"`
		SequenceConditionValue             string `json:"SequenceConditionValue"`
		MaximumNumberofRepeats             string `json:"MaximumNumberofRepeats"`
		PlacerOrderNumberUniversalID       string `json:"PlacerOrderNumberUniversalID"`
		PlacerOrderNumberUniversalIDType   string `json:"PlacerOrderNumberUniversalIDType"`
		FillerOrderNumberUniversalID       string `json:"FillerOrderNumberUniversalID"`
		FillerOrderNumberUniversalIDType   string `json:"FillerOrderNumberUniversalIDType"`
	} `json:"OBRQuantity"`
	OBRTransportLogistics struct {
		Class                                  string `json:"$class"`
		TransportLogisticIdentifier            string `json:"TransportLogisticIdentifier"`
		TransportLogisticText                  string `json:"TransportLogisticText"`
		TransportLogisticNameOfCodingSystem    string `json:"TransportLogisticNameOfCodingSystem"`
		TransportLogisticAlternateIdentifier   string `json:"TransportLogisticAlternateIdentifier"`
		TransportLogisticAlternateText         string `json:"TransportLogisticAlternateText"`
		TransportLogisticAlternateCodingSystem string `json:"TransportLogisticAlternateCodingSystem"`
	} `json:"OBRTransportLogistics"`
	OBROrderingProvider struct {
		Class                                                      string `json:"$class"`
		OrderingProviderIDNumber                                   string `json:"OrderingProviderIDNumber"`
		OrderingProviderFamilyName                                 string `json:"OrderingProviderFamilyName"`
		OrderingProviderFNPrefix                                   string `json:"OrderingProviderFNPrefix"`
		OrderingProviderFNOwnFamilyName                            string `json:"OrderingProviderFNOwnFamilyName"`
		OrderingProviderFNPrefixFromPartnerSpouse                  string `json:"OrderingProviderFNPrefixFromPartnerSpouse"`
		OrderingProviderFNFrompartnerspouse                        string `json:"OrderingProviderFNFrompartnerspouse"`
		OrderingProviderGivenName                                  string `json:"OrderingProviderGivenName"`
		OrderingProviderMiddleinitialorname                        string `json:"OrderingProviderMiddleinitialorname"`
		OrderingProviderSuffix                                     string `json:"OrderingProviderSuffix"`
		OrderingProviderPrefix                                     string `json:"OrderingProviderPrefix"`
		OrderingProviderDegree                                     string `json:"OrderingProviderDegree"`
		OrderingProviderSourcetable                                string `json:"OrderingProviderSourcetable"`
		OrderingProviderAANamespaceID                              string `json:"OrderingProviderAANamespaceID"`
		OrderingProviderAAUniversalID                              string `json:"OrderingProviderAAUniversalID"`
		OrderingProviderAAUniversalIDtype                          string `json:"OrderingProviderAAUniversalIDtype"`
		OrderingProviderNametypecode                               string `json:"OrderingProviderNametypecode"`
		OrderingProviderIdentifiercheckdigit                       string `json:"OrderingProviderIdentifiercheckdigit"`
		OrderingProviderCodeidentifyingthecheckdigitschemeemployed string `json:"OrderingProviderCodeidentifyingthecheckdigitschemeemployed"`
		OrderingProviderIdentifiertypecode                         string `json:"OrderingProviderIdentifiertypecode"`
		OrderingProviderAFNamespaceID                              string `json:"OrderingProviderAFNamespaceID"`
		OrderingProviderAFUniversalID                              string `json:"OrderingProviderAFUniversalID"`
		OrderingProviderAFUniversalIDtype                          string `json:"OrderingProviderAFUniversalIDtype"`
		OrderingProviderNamerepresentationcode                     string `json:"OrderingProviderNamerepresentationcode"`
		OrderingProviderNCIdentifier                               string `json:"OrderingProviderNCIdentifier"`
		OrderingProviderNCText                                     string `json:"OrderingProviderNCText"`
		OrderingProviderNCNameOfCodingSystem                       string `json:"OrderingProviderNCNameOfCodingSystem"`
		OrderingProviderNCAlternateIdentifier                      string `json:"OrderingProviderNCAlternateIdentifier"`
		OrderingProviderNCAlternateText                            string `json:"OrderingProviderNCAlternateText"`
		OrderingProviderNCAlternateCodingSystem                    string `json:"OrderingProviderNCAlternateCodingSystem"`
		OrderingProviderNVStartDateYear                            string `json:"OrderingProviderNVStartDateYear"`
		OrderingProviderNVStartDateMonth                           string `json:"OrderingProviderNVStartDateMonth"`
		OrderingProviderNVStartDateDay                             string `json:"OrderingProviderNVStartDateDay"`
		OrderingProviderNVStartDateHours                           string `json:"OrderingProviderNVStartDateHours"`
		OrderingProviderNVStartDateMinutes                         string `json:"OrderingProviderNVStartDateMinutes"`
		OrderingProviderNVStartDateSeconds                         string `json:"OrderingProviderNVStartDateSeconds"`
		OrderingProviderNVStartDateMillis                          string `json:"OrderingProviderNVStartDateMillis"`
		OrderingProviderNVStartDateGmtOffset                       string `json:"OrderingProviderNVStartDateGmtOffset"`
		OrderingProviderNVStartDatePrecision                       string `json:"OrderingProviderNVStartDatePrecision"`
		OrderingProviderNVEndDateYear                              string `json:"OrderingProviderNVEndDateYear"`
		OrderingProviderNVEndDateMonth                             string `json:"OrderingProviderNVEndDateMonth"`
		OrderingProviderNVEndDateDay                               string `json:"OrderingProviderNVEndDateDay"`
		OrderingProviderNVEndDateHours                             string `json:"OrderingProviderNVEndDateHours"`
		OrderingProviderNVEndDateMinutes                           string `json:"OrderingProviderNVEndDateMinutes"`
		OrderingProviderNVEndDateSeconds                           string `json:"OrderingProviderNVEndDateSeconds"`
		OrderingProviderNVEndDateMillis                            string `json:"OrderingProviderNVEndDateMillis"`
		OrderingProviderNVEndDateGmtOffset                         string `json:"OrderingProviderNVEndDateGmtOffset"`
		OrderingProviderNVEndDatePrecision                         string `json:"OrderingProviderNVEndDatePrecision"`
		OrderingProviderNameassemblyorder                          string `json:"OrderingProviderNameassemblyorder"`
		OrderingProviderEffDTYear                                  string `json:"OrderingProviderEffDTYear"`
		OrderingProviderEffDTMonth                                 string `json:"OrderingProviderEffDTMonth"`
		OrderingProviderEffDTDay                                   string `json:"OrderingProviderEffDTDay"`
		OrderingProviderEffDTHours                                 string `json:"OrderingProviderEffDTHours"`
		OrderingProviderEffDTMinutes                               string `json:"OrderingProviderEffDTMinutes"`
		OrderingProviderEffDTSeconds                               string `json:"OrderingProviderEffDTSeconds"`
		OrderingProviderEffDTMillis                                string `json:"OrderingProviderEffDTMillis"`
		OrderingProviderEffDTGmtOffset                             string `json:"OrderingProviderEffDTGmtOffset"`
		OrderingProviderEffDTPrecision                             string `json:"OrderingProviderEffDTPrecision"`
		OrderingProviderExpDTYear                                  string `json:"OrderingProviderExpDTYear"`
		OrderingProviderExpDTMonth                                 string `json:"OrderingProviderExpDTMonth"`
		OrderingProviderExpDTDay                                   string `json:"OrderingProviderExpDTDay"`
		OrderingProviderExpDTHours                                 string `json:"OrderingProviderExpDTHours"`
		OrderingProviderExpDTMinutes                               string `json:"OrderingProviderExpDTMinutes"`
		OrderingProviderExpDTSeconds                               string `json:"OrderingProviderExpDTSeconds"`
		OrderingProviderExpDTMillis                                string `json:"OrderingProviderExpDTMillis"`
		OrderingProviderExpDTGmtOffset                             string `json:"OrderingProviderExpDTGmtOffset"`
		OrderingProviderExpDTPrecision                             string `json:"OrderingProviderExpDTPrecision"`
		OrderingProviderExpDTProfessionalSuffix                    string `json:"OrderingProviderExpDTProfessionalSuffix"`
		OrderingProviderAJIdentifier                               string `json:"OrderingProviderAJIdentifier"`
		OrderingProviderAJText                                     string `json:"OrderingProviderAJText"`
		OrderingProviderAJNameOfCodingSystem                       string `json:"OrderingProviderAJNameOfCodingSystem"`
		OrderingProviderAJAlternateIdentifier                      string `json:"OrderingProviderAJAlternateIdentifier"`
		OrderingProviderAJAlternateText                            string `json:"OrderingProviderAJAlternateText"`
		OrderingProviderAJNameOfAlternateCodingSystem              string `json:"OrderingProviderAJNameOfAlternateCodingSystem"`
		OrderingProviderAJCodingSystemVersionID                    string `json:"OrderingProviderAJCodingSystemVersionID"`
		OrderingProviderAJAlternateCodingSystemVersionID           string `json:"OrderingProviderAJAlternateCodingSystemVersionID"`
		OrderingProviderAJOriginalText                             string `json:"OrderingProviderAJOriginalText"`
		OrderingProviderAADIdentifier                              string `json:"OrderingProviderAADIdentifier"`
		OrderingProviderAADText                                    string `json:"OrderingProviderAADText"`
		OrderingProviderAADNameOfCodingSystem                      string `json:"OrderingProviderAADNameOfCodingSystem"`
		OrderingProviderAADAlternateIdentifier                     string `json:"OrderingProviderAADAlternateIdentifier"`
		OrderingProviderAADAlternateText                           string `json:"OrderingProviderAADAlternateText"`
		OrderingProviderAADNameOfAlternateCodingSystem             string `json:"OrderingProviderAADNameOfAlternateCodingSystem"`
		OrderingProviderAADCodingSystemVersionID                   string `json:"OrderingProviderAADCodingSystemVersionID"`
		OrderingProviderAADAlternateCodingSystemVersionID          string `json:"OrderingProviderAADAlternateCodingSystemVersionID"`
		OrderingProviderAADOriginalText                            string `json:"OrderingProviderAADOriginalText"`
		OrderingProviderNVStartDateTime                            string `json:"OrderingProviderNVStartDateTime"`
		OrderingProviderNVEndDateTime                              string `json:"OrderingProviderNVEndDateTime"`
		OrderingProviderEffDTTime                                  string `json:"OrderingProviderEffDTTime"`
		OrderingProviderExpDTTime                                  string `json:"OrderingProviderExpDTTime"`
	} `json:"OBROrderingProvider"`
	OBRResultCopiesTo struct {
		Class                                                    string `json:"$class"`
		ResultCopiesToIDNumber                                   string `json:"ResultCopiesToIDNumber"`
		ResultCopiesToFamilyName                                 string `json:"ResultCopiesToFamilyName"`
		ResultCopiesToFNPrefix                                   string `json:"ResultCopiesToFNPrefix"`
		ResultCopiesToFNOwnFamilyName                            string `json:"ResultCopiesToFNOwnFamilyName"`
		ResultCopiesToFNPrefixFromPartnerSpouse                  string `json:"ResultCopiesToFNPrefixFromPartnerSpouse"`
		ResultCopiesToFNFrompartnerspouse                        string `json:"ResultCopiesToFNFrompartnerspouse"`
		ResultCopiesToGivenName                                  string `json:"ResultCopiesToGivenName"`
		ResultCopiesToMiddleinitialorname                        string `json:"ResultCopiesToMiddleinitialorname"`
		ResultCopiesToSuffix                                     string `json:"ResultCopiesToSuffix"`
		ResultCopiesToPrefix                                     string `json:"ResultCopiesToPrefix"`
		ResultCopiesToDegree                                     string `json:"ResultCopiesToDegree"`
		ResultCopiesToSourcetable                                string `json:"ResultCopiesToSourcetable"`
		ResultCopiesToAANamespaceID                              string `json:"ResultCopiesToAANamespaceID"`
		ResultCopiesToAAUniversalID                              string `json:"ResultCopiesToAAUniversalID"`
		ResultCopiesToAAUniversalIDtype                          string `json:"ResultCopiesToAAUniversalIDtype"`
		ResultCopiesToNametypecode                               string `json:"ResultCopiesToNametypecode"`
		ResultCopiesToIdentifiercheckdigit                       string `json:"ResultCopiesToIdentifiercheckdigit"`
		ResultCopiesToCodeidentifyingthecheckdigitschemeemployed string `json:"ResultCopiesToCodeidentifyingthecheckdigitschemeemployed"`
		ResultCopiesToIdentifiertypecode                         string `json:"ResultCopiesToIdentifiertypecode"`
		ResultCopiesToAFNamespaceID                              string `json:"ResultCopiesToAFNamespaceID"`
		ResultCopiesToAFUniversalID                              string `json:"ResultCopiesToAFUniversalID"`
		ResultCopiesToAFUniversalIDtype                          string `json:"ResultCopiesToAFUniversalIDtype"`
		ResultCopiesToNamerepresentationcode                     string `json:"ResultCopiesToNamerepresentationcode"`
		ResultCopiesToNCIdentifier                               string `json:"ResultCopiesToNCIdentifier"`
		ResultCopiesToNCText                                     string `json:"ResultCopiesToNCText"`
		ResultCopiesToNCNameOfCodingSystem                       string `json:"ResultCopiesToNCNameOfCodingSystem"`
		ResultCopiesToNCAlternateIdentifier                      string `json:"ResultCopiesToNCAlternateIdentifier"`
		ResultCopiesToNCAlternateText                            string `json:"ResultCopiesToNCAlternateText"`
		ResultCopiesToNCAlternateCodingSystem                    string `json:"ResultCopiesToNCAlternateCodingSystem"`
		ResultCopiesToNVStartDateYear                            string `json:"ResultCopiesToNVStartDateYear"`
		ResultCopiesToNVStartDateMonth                           string `json:"ResultCopiesToNVStartDateMonth"`
		ResultCopiesToNVStartDateDay                             string `json:"ResultCopiesToNVStartDateDay"`
		ResultCopiesToNVStartDateHours                           string `json:"ResultCopiesToNVStartDateHours"`
		ResultCopiesToNVStartDateMinutes                         string `json:"ResultCopiesToNVStartDateMinutes"`
		ResultCopiesToNVStartDateSeconds                         string `json:"ResultCopiesToNVStartDateSeconds"`
		ResultCopiesToNVStartDateMillis                          string `json:"ResultCopiesToNVStartDateMillis"`
		ResultCopiesToNVStartDateGmtOffset                       string `json:"ResultCopiesToNVStartDateGmtOffset"`
		ResultCopiesToNVStartDatePrecision                       string `json:"ResultCopiesToNVStartDatePrecision"`
		ResultCopiesToNVEndDateYear                              string `json:"ResultCopiesToNVEndDateYear"`
		ResultCopiesToNVEndDateMonth                             string `json:"ResultCopiesToNVEndDateMonth"`
		ResultCopiesToNVEndDateDay                               string `json:"ResultCopiesToNVEndDateDay"`
		ResultCopiesToNVEndDateHours                             string `json:"ResultCopiesToNVEndDateHours"`
		ResultCopiesToNVEndDateMinutes                           string `json:"ResultCopiesToNVEndDateMinutes"`
		ResultCopiesToNVEndDateSeconds                           string `json:"ResultCopiesToNVEndDateSeconds"`
		ResultCopiesToNVEndDateMillis                            string `json:"ResultCopiesToNVEndDateMillis"`
		ResultCopiesToNVEndDateGmtOffset                         string `json:"ResultCopiesToNVEndDateGmtOffset"`
		ResultCopiesToNVEndDatePrecision                         string `json:"ResultCopiesToNVEndDatePrecision"`
		ResultCopiesToNameassemblyorder                          string `json:"ResultCopiesToNameassemblyorder"`
		ResultCopiesToEffDTYear                                  string `json:"ResultCopiesToEffDTYear"`
		ResultCopiesToEffDTMonth                                 string `json:"ResultCopiesToEffDTMonth"`
		ResultCopiesToEffDTDay                                   string `json:"ResultCopiesToEffDTDay"`
		ResultCopiesToEffDTHours                                 string `json:"ResultCopiesToEffDTHours"`
		ResultCopiesToEffDTMinutes                               string `json:"ResultCopiesToEffDTMinutes"`
		ResultCopiesToEffDTSeconds                               string `json:"ResultCopiesToEffDTSeconds"`
		ResultCopiesToEffDTMillis                                string `json:"ResultCopiesToEffDTMillis"`
		ResultCopiesToEffDTGmtOffset                             string `json:"ResultCopiesToEffDTGmtOffset"`
		ResultCopiesToEffDTPrecision                             string `json:"ResultCopiesToEffDTPrecision"`
		ResultCopiesToExpDTYear                                  string `json:"ResultCopiesToExpDTYear"`
		ResultCopiesToExpDTMonth                                 string `json:"ResultCopiesToExpDTMonth"`
		ResultCopiesToExpDTDay                                   string `json:"ResultCopiesToExpDTDay"`
		ResultCopiesToExpDTHours                                 string `json:"ResultCopiesToExpDTHours"`
		ResultCopiesToExpDTMinutes                               string `json:"ResultCopiesToExpDTMinutes"`
		ResultCopiesToExpDTSeconds                               string `json:"ResultCopiesToExpDTSeconds"`
		ResultCopiesToExpDTMillis                                string `json:"ResultCopiesToExpDTMillis"`
		ResultCopiesToExpDTGmtOffset                             string `json:"ResultCopiesToExpDTGmtOffset"`
		ResultCopiesToExpDTPrecision                             string `json:"ResultCopiesToExpDTPrecision"`
		ResultCopiesToExpDTProfessionalSuffix                    string `json:"ResultCopiesToExpDTProfessionalSuffix"`
		ResultCopiesToAJIdentifier                               string `json:"ResultCopiesToAJIdentifier"`
		ResultCopiesToAJText                                     string `json:"ResultCopiesToAJText"`
		ResultCopiesToAJNameOfCodingSystem                       string `json:"ResultCopiesToAJNameOfCodingSystem"`
		ResultCopiesToAJAlternateIdentifier                      string `json:"ResultCopiesToAJAlternateIdentifier"`
		ResultCopiesToAJAlternateText                            string `json:"ResultCopiesToAJAlternateText"`
		ResultCopiesToAJNameOfAlternateCodingSystem              string `json:"ResultCopiesToAJNameOfAlternateCodingSystem"`
		ResultCopiesToAJCodingSystemVersionID                    string `json:"ResultCopiesToAJCodingSystemVersionID"`
		ResultCopiesToAJAlternateCodingSystemVersionID           string `json:"ResultCopiesToAJAlternateCodingSystemVersionID"`
		ResultCopiesToAJOriginalText                             string `json:"ResultCopiesToAJOriginalText"`
		ResultCopiesToAADIdentifier                              string `json:"ResultCopiesToAADIdentifier"`
		ResultCopiesToAADText                                    string `json:"ResultCopiesToAADText"`
		ResultCopiesToAADNameOfCodingSystem                      string `json:"ResultCopiesToAADNameOfCodingSystem"`
		ResultCopiesToAADAlternateIdentifier                     string `json:"ResultCopiesToAADAlternateIdentifier"`
		ResultCopiesToAADAlternateText                           string `json:"ResultCopiesToAADAlternateText"`
		ResultCopiesToAADNameOfAlternateCodingSystem             string `json:"ResultCopiesToAADNameOfAlternateCodingSystem"`
		ResultCopiesToAADCodingSystemVersionID                   string `json:"ResultCopiesToAADCodingSystemVersionID"`
		ResultCopiesToAADAlternateCodingSystemVersionID          string `json:"ResultCopiesToAADAlternateCodingSystemVersionID"`
		ResultCopiesToAADOriginalText                            string `json:"ResultCopiesToAADOriginalText"`
		ResultCopiesToNVStartDateTime                            string `json:"ResultCopiesToNVStartDateTime"`
		ResultCopiesToNVEndDateTime                              string `json:"ResultCopiesToNVEndDateTime"`
		ResultCopiesToEffDTTime                                  string `json:"ResultCopiesToEffDTTime"`
		ResultCopiesToExpDTTime                                  string `json:"ResultCopiesToExpDTTime"`
	} `json:"OBRResultCopiesTo"`
	OBRPlacerSupServiceInfo struct {
		Class                                         string `json:"$class"`
		PlacerSupServiceInfoCodeIdentifier            string `json:"PlacerSupServiceInfoCodeIdentifier"`
		PlacerSupServiceInfoCodeText                  string `json:"PlacerSupServiceInfoCodeText"`
		PlacerSupServiceInfoCodeNameOfCodingSystem    string `json:"PlacerSupServiceInfoCodeNameOfCodingSystem"`
		PlacerSupServiceInfoCodeAlternateIdentifier   string `json:"PlacerSupServiceInfoCodeAlternateIdentifier"`
		PlacerSupServiceInfoCodeAlternateText         string `json:"PlacerSupServiceInfoCodeAlternateText"`
		PlacerSupServiceInfoCodeAlternateCodingSystem string `json:"PlacerSupServiceInfoCodeAlternateCodingSystem"`
	} `json:"OBRPlacerSupServiceInfo"`
	OBRPlannedPatTransportComment struct {
		Class                                           string `json:"$class"`
		PlannedPatTransportCommentIdentifier            string `json:"PlannedPatTransportCommentIdentifier"`
		PlannedPatTransportCommentText                  string `json:"PlannedPatTransportCommentText"`
		PlannedPatTransportCommentNameOfCodingSystem    string `json:"PlannedPatTransportCommentNameOfCodingSystem"`
		PlannedPatTransportCommentAlternateIdentifier   string `json:"PlannedPatTransportCommentAlternateIdentifier"`
		PlannedPatTransportCommentAlternateText         string `json:"PlannedPatTransportCommentAlternateText"`
		PlannedPatTransportCommentAlternateCodingSystem string `json:"PlannedPatTransportCommentAlternateCodingSystem"`
	} `json:"OBRPlannedPatTransportComment"`
	OBRReasonforStudy struct {
		Class                               string `json:"$class"`
		ReasonForStudyIdentifier            string `json:"ReasonForStudyIdentifier"`
		ReasonForStudyText                  string `json:"ReasonForStudyText"`
		ReasonForStudyNameOfCodingSystem    string `json:"ReasonForStudyNameOfCodingSystem"`
		ReasonForStudyAlternateIdentifier   string `json:"ReasonForStudyAlternateIdentifier"`
		ReasonForStudyAlternateText         string `json:"ReasonForStudyAlternateText"`
		ReasonForStudyAlternateCodingSystem string `json:"ReasonForStudyAlternateCodingSystem"`
	} `json:"OBRReasonforStudy"`
	OBRTechnician struct {
		Class                             string `json:"$class"`
		TechnicianIDNumber                string `json:"TechnicianIDNumber"`
		TechnicianFamilyName              string `json:"TechnicianFamilyName"`
		TechnicianGivenName               string `json:"TechnicianGivenName"`
		TechnicianMiddleinitialorname     string `json:"TechnicianMiddleinitialorname"`
		TechnicianSuffix                  string `json:"TechnicianSuffix"`
		TechnicianPrefix                  string `json:"TechnicianPrefix"`
		TechnicianDegree                  string `json:"TechnicianDegree"`
		TechnicianSourcetable             string `json:"TechnicianSourcetable"`
		TechnicianAANamespaceID           string `json:"TechnicianAANamespaceID"`
		TechnicianAAUniversalID           string `json:"TechnicianAAUniversalID"`
		TechnicianAAUniversalIDtype       string `json:"TechnicianAAUniversalIDtype"`
		TechnicianStartDTYear             string `json:"TechnicianStartDTYear"`
		TechnicianStartDTMonth            string `json:"TechnicianStartDTMonth"`
		TechnicianStartDTDay              string `json:"TechnicianStartDTDay"`
		TechnicianStartDTHours            string `json:"TechnicianStartDTHours"`
		TechnicianStartDTMinutes          string `json:"TechnicianStartDTMinutes"`
		TechnicianStartDTSeconds          string `json:"TechnicianStartDTSeconds"`
		TechnicianStartDTMillis           string `json:"TechnicianStartDTMillis"`
		TechnicianStartDTGmtOffset        string `json:"TechnicianStartDTGmtOffset"`
		TechnicianStartDTPrecision        string `json:"TechnicianStartDTPrecision"`
		TechnicianEndDTYear               string `json:"TechnicianEndDTYear"`
		TechnicianEndDTMonth              string `json:"TechnicianEndDTMonth"`
		TechnicianEndDTDay                string `json:"TechnicianEndDTDay"`
		TechnicianEndDTHours              string `json:"TechnicianEndDTHours"`
		TechnicianEndDTMinutes            string `json:"TechnicianEndDTMinutes"`
		TechnicianEndDTSeconds            string `json:"TechnicianEndDTSeconds"`
		TechnicianEndDTMillis             string `json:"TechnicianEndDTMillis"`
		TechnicianEndDTGmtOffset          string `json:"TechnicianEndDTGmtOffset"`
		TechnicianPrecision               string `json:"TechnicianPrecision"`
		Technicianpointofcare             string `json:"Technicianpointofcare"`
		Technicianroom                    string `json:"Technicianroom"`
		Technicianbed                     string `json:"Technicianbed"`
		TechnicianFacilitynamespaceID     string `json:"TechnicianFacilitynamespaceID"`
		TechnicianFacilityuniversalID     string `json:"TechnicianFacilityuniversalID"`
		TechnicianFacilityuniversalIDtype string `json:"TechnicianFacilityuniversalIDtype"`
		Technicianlocationstatus          string `json:"Technicianlocationstatus"`
		Technicianpersonlocationtype      string `json:"Technicianpersonlocationtype"`
		Technicianbuilding                string `json:"Technicianbuilding"`
		Technicianfloor                   string `json:"Technicianfloor"`
		Technician                        string `json:"Technician"`
		TechnicianStartDTTime             string `json:"TechnicianStartDTTime"`
		TechnicianEndDTTime               string `json:"TechnicianEndDTTime"`
	} `json:"OBRTechnician"`
	OBRTranscriptionist struct {
		Class                                   string `json:"$class"`
		TranscriptionistIDNumber                string `json:"TranscriptionistIDNumber"`
		TranscriptionistFamilyName              string `json:"TranscriptionistFamilyName"`
		TranscriptionistGivenName               string `json:"TranscriptionistGivenName"`
		TranscriptionistMiddleinitialorname     string `json:"TranscriptionistMiddleinitialorname"`
		TranscriptionistSuffix                  string `json:"TranscriptionistSuffix"`
		TranscriptionistPrefix                  string `json:"TranscriptionistPrefix"`
		TranscriptionistDegree                  string `json:"TranscriptionistDegree"`
		TranscriptionistSourcetable             string `json:"TranscriptionistSourcetable"`
		TranscriptionistAANamespaceID           string `json:"TranscriptionistAANamespaceID"`
		TranscriptionistAAUniversalID           string `json:"TranscriptionistAAUniversalID"`
		TranscriptionistAAUniversalIDtype       string `json:"TranscriptionistAAUniversalIDtype"`
		TranscriptionistStartDTYear             string `json:"TranscriptionistStartDTYear"`
		TranscriptionistStartDTMonth            string `json:"TranscriptionistStartDTMonth"`
		TranscriptionistStartDTDay              string `json:"TranscriptionistStartDTDay"`
		TranscriptionistStartDTHours            string `json:"TranscriptionistStartDTHours"`
		TranscriptionistStartDTMinutes          string `json:"TranscriptionistStartDTMinutes"`
		TranscriptionistStartDTSeconds          string `json:"TranscriptionistStartDTSeconds"`
		TranscriptionistStartDTMillis           string `json:"TranscriptionistStartDTMillis"`
		TranscriptionistStartDTGmtOffset        string `json:"TranscriptionistStartDTGmtOffset"`
		TranscriptionistStartDTPrecision        string `json:"TranscriptionistStartDTPrecision"`
		TranscriptionistEndDTYear               string `json:"TranscriptionistEndDTYear"`
		TranscriptionistEndDTMonth              string `json:"TranscriptionistEndDTMonth"`
		TranscriptionistEndDTDay                string `json:"TranscriptionistEndDTDay"`
		TranscriptionistEndDTHours              string `json:"TranscriptionistEndDTHours"`
		TranscriptionistEndDTMinutes            string `json:"TranscriptionistEndDTMinutes"`
		TranscriptionistEndDTSeconds            string `json:"TranscriptionistEndDTSeconds"`
		TranscriptionistEndDTMillis             string `json:"TranscriptionistEndDTMillis"`
		TranscriptionistEndDTGmtOffset          string `json:"TranscriptionistEndDTGmtOffset"`
		TranscriptionistPrecision               string `json:"TranscriptionistPrecision"`
		Transcriptionistpointofcare             string `json:"Transcriptionistpointofcare"`
		Transcriptionistroom                    string `json:"Transcriptionistroom"`
		Transcriptionistbed                     string `json:"Transcriptionistbed"`
		TranscriptionistFacilitynamespaceID     string `json:"TranscriptionistFacilitynamespaceID"`
		TranscriptionistFacilityuniversalID     string `json:"TranscriptionistFacilityuniversalID"`
		TranscriptionistFacilityuniversalIDtype string `json:"TranscriptionistFacilityuniversalIDtype"`
		Transcriptionistlocationstatus          string `json:"Transcriptionistlocationstatus"`
		Transcriptionistpersonlocationtype      string `json:"Transcriptionistpersonlocationtype"`
		Transcriptionistbuilding                string `json:"Transcriptionistbuilding"`
		Transcriptionistfloor                   string `json:"Transcriptionistfloor"`
		Transcriptionist                        string `json:"Transcriptionist"`
		TranscriptionistStartDTTime             string `json:"TranscriptionistStartDTTime"`
		TranscriptionistEndDTTime               string `json:"TranscriptionistEndDTTime"`
	} `json:"OBRTranscriptionist"`
}

func (mo *Hl7ObrFormat) fnAddObr(ctx contractapi.TransactionContextInterface) error {

	err := FnValidationCheckStruct(mo)
	if err != nil {
		return err
	}
	mo.MSHOBR = mo.MSHKEY + "_" + "OBR"
	fmt.Println(mo.MSHOBR, "obr key value")
	obrBytes, err := ctx.GetStub().GetState(mo.MSHOBR)
	if obrBytes != nil || err != nil {
		return fmt.Errorf("Key Already Exists in the Network")
	}
	obrBytes, _ = json.Marshal(mo)
	fmt.Println("Writing to channel")
	//messagekey <- mo.MSHKEY
	return ctx.GetStub().PutState(mo.MSHOBR, obrBytes)
}
