package main

import (
	"encoding/json"
	"fmt"

	"github.com/hyperledger/fabric-contract-api-go/contractapi"
)

//Hl7Pv1Format ..
type Hl7Pv1Format struct {
	Class                                                                   string `json:"$class"`
	MSHPV1                                                                  string `json:"MSH_PV1"`
	PV1KEY                                                                  string `json:"PV1KEY"`
	MSHKEY                                                                  string `json:"MSHKEY"`
	SetID                                                                   string `json:"SetID"`
	PatientClass                                                            string `json:"PatientClass"`
	AssignedPatientPointOfCare                                              string `json:"AssignedPatientPointOfCare"`
	AssignedPatientRoom                                                     string `json:"AssignedPatientRoom"`
	AssignedPatientBed                                                      string `json:"AssignedPatientBed"`
	AssignedPatientFacilityNamespaceID                                      string `json:"AssignedPatientFacilityNamespaceID"`
	AssignedPatientFacilityUniversalID                                      string `json:"AssignedPatientFacilityUniversalID"`
	AssignedPatientFacilityUniversalIDType                                  string `json:"AssignedPatientFacilityUniversalIDType"`
	AssignedPatientLocationStatus                                           string `json:"AssignedPatientLocationStatus"`
	AssignedPatientPatientLocationType                                      string `json:"AssignedPatientPatientLocationType"`
	AssignedPatientBuilding                                                 string `json:"AssignedPatientBuilding"`
	AssignedPatientFloor                                                    string `json:"AssignedPatientFloor"`
	AssignedPatientLocationDescription                                      string `json:"AssignedPatientLocationDescription"`
	AssignedPatientComprehensiveEntityIdentifier                            string `json:"AssignedPatientComprehensiveEntityIdentifier"`
	AssignedPatientComprehensiveNamespaceID                                 string `json:"AssignedPatientComprehensiveNamespaceID"`
	AssignedPatientComprehensiveUniversalID                                 string `json:"AssignedPatientComprehensiveUniversalID"`
	AssignedPatientComprehensiveUniversalIDType                             string `json:"AssignedPatientComprehensiveUniversalIDType"`
	AssignedPatientAANamespaceID                                            string `json:"AssignedPatientAANamespaceID"`
	AssignedPatientAAUniversalID                                            string `json:"AssignedPatientAAUniversalID"`
	AssignedPatientAAUniversalIDType                                        string `json:"AssignedPatientAAUniversalIDType"`
	AdmissionType                                                           string `json:"AdmissionType"`
	PriorPatientLocationPointOfCare                                         string `json:"PriorPatientLocationPointOfCare"`
	PriorPatientLocationRoom                                                string `json:"PriorPatientLocationRoom"`
	PriorPatientLocationBed                                                 string `json:"PriorPatientLocationBed"`
	PriorPatientLocationFacilityNamespaceID                                 string `json:"PriorPatientLocationFacilityNamespaceID"`
	PriorPatientLocationFacilityUniversalID                                 string `json:"PriorPatientLocationFacilityUniversalID"`
	PriorPatientLocationFacilityUniversalIDType                             string `json:"PriorPatientLocationFacilityUniversalIDType"`
	PriorPatientLocationLocationStatus                                      string `json:"PriorPatientLocationLocationStatus"`
	PriorPatientLocationPatientLocationType                                 string `json:"PriorPatientLocationPatientLocationType"`
	PriorPatientLocationBuilding                                            string `json:"PriorPatientLocationBuilding"`
	PriorPatientLocationFloor                                               string `json:"PriorPatientLocationFloor"`
	PriorPatientLocationLocationDescription                                 string `json:"PriorPatientLocationLocationDescription"`
	PriorPatientLocationComprehensiveEntityIdentifier                       string `json:"PriorPatientLocationComprehensiveEntityIdentifier"`
	PriorPatientLocationComprehensiveNamespaceID                            string `json:"PriorPatientLocationComprehensiveNamespaceID"`
	PriorPatientLocationComprehensiveUniversalID                            string `json:"PriorPatientLocationComprehensiveUniversalID"`
	MPriorPatientLocationComprehensiveUniversalIDType                       string `json:"MPriorPatientLocationComprehensiveUniversalIDType"`
	CPriorPatientLocationAANamespaceID                                      string `json:"CPriorPatientLocationAANamespaceID"`
	LPriorPatientLocationAAUniversalID                                      string `json:"LPriorPatientLocationAAUniversalID"`
	UPriorPatientLocationAAUniversalIDType                                  string `json:"UPriorPatientLocationAAUniversalIDType"`
	SHospitalService                                                        string `json:"SHospitalService"`
	PTemporaryLocationPointOfCare                                           string `json:"PTemporaryLocationPointOfCare"`
	ATemporaryLocationRoom                                                  string `json:"ATemporaryLocationRoom"`
	ATemporaryLocationBed                                                   string `json:"ATemporaryLocationBed"`
	ATemporaryLocationFacilityNamespaceID                                   string `json:"ATemporaryLocationFacilityNamespaceID"`
	ATemporaryLocationFacilityUniversalID                                   string `json:"ATemporaryLocationFacilityUniversalID"`
	ATemporaryLocationFacilityUniversalIDType                               string `json:"ATemporaryLocationFacilityUniversalIDType"`
	ATemporaryLocationLocationStatus                                        string `json:"ATemporaryLocationLocationStatus"`
	ATemporaryLocationPatientLocationType                                   string `json:"ATemporaryLocationPatientLocationType"`
	ATemporaryLocationBuilding                                              string `json:"ATemporaryLocationBuilding"`
	ATemporaryLocationFloor                                                 string `json:"ATemporaryLocationFloor"`
	ATemporaryLocationLocationDescription                                   string `json:"ATemporaryLocationLocationDescription"`
	TemporaryComprehensiveLocationEntityIdentifier                          string `json:"TemporaryComprehensiveLocationEntityIdentifier"`
	TemporaryComprehensiveLocationNamespaceID                               string `json:"TemporaryComprehensiveLocationNamespaceID"`
	TemporaryComprehensiveLocationUniversalID                               string `json:"TemporaryComprehensiveLocationUniversalID"`
	TemporaryComprehensiveLocationUniversalIDType                           string `json:"TemporaryComprehensiveLocationUniversalIDType"`
	TemporaryLocationAANamespaceID                                          string `json:"TemporaryLocationAANamespaceID"`
	TemporaryLocationAAUniversalID                                          string `json:"TemporaryLocationAAUniversalID"`
	TemporaryLocationAAUniversalIDType                                      string `json:"TemporaryLocationAAUniversalIDType"`
	PreadmitTestIndicator                                                   string `json:"PreadmitTestIndicator"`
	ReadmissionIndicator                                                    string `json:"ReadmissionIndicator"`
	AdmitSource                                                             string `json:"AdmitSource"`
	VIPIndicator                                                            string `json:"VIPIndicator"`
	PatientType                                                             string `json:"PatientType"`
	VisitNumberIDNumber                                                     string `json:"VisitNumberIDNumber"`
	VisitNumberCheckDigit                                                   string `json:"VisitNumberCheckDigit"`
	VisitNumberCheckDigitScheme                                             string `json:"VisitNumberCheckDigitScheme"`
	VisitNumberAANamespaceID                                                string `json:"VisitNumberAANamespaceID"`
	VisitNumberAAUniversalID                                                string `json:"VisitNumberAAUniversalID"`
	VisitNumberAAUniversalIDType                                            string `json:"VisitNumberAAUniversalIDType"`
	VisitNumberIdentifierTypeCode                                           string `json:"VisitNumberIdentifierTypeCode"`
	VisitNumberAFNamespaceID                                                string `json:"VisitNumberAFNamespaceID"`
	VisitNumberAFUniversalID                                                string `json:"VisitNumberAFUniversalID"`
	VisitNumberAFUniversalIDType                                            string `json:"VisitNumberAFUniversalIDType"`
	VisitNumberEffectiveYear                                                string `json:"VisitNumberEffectiveYear"`
	VisitNumberEffectiveMonth                                               string `json:"VisitNumberEffectiveMonth"`
	VisitNumberEffectiveDay                                                 string `json:"VisitNumberEffectiveDay"`
	VisitNumberExpirationTime                                               string `json:"VisitNumberExpirationTime"`
	VisitNumberExpirationYear                                               string `json:"VisitNumberExpirationYear"`
	VisitNumberExpirationMonth                                              string `json:"VisitNumberExpirationMonth"`
	VisitNumberExpirationDay                                                string `json:"VisitNumberExpirationDay"`
	VisitNumberAssigningJurisdictionIdentifier                              string `json:"VisitNumberAssigningJurisdictionIdentifier"`
	VisitNumberAssigningJurisdictionText                                    string `json:"VisitNumberAssigningJurisdictionText"`
	VisitNumberAssigningJurisdictionNameOfCodingSystem                      string `json:"VisitNumberAssigningJurisdictionNameOfCodingSystem"`
	VisitNumberAssigningJurisdictionAlternateIdentifier                     string `json:"VisitNumberAssigningJurisdictionAlternateIdentifier"`
	VisitNumberAssigningJurisdictionAlternateText                           string `json:"VisitNumberAssigningJurisdictionAlternateText"`
	VisitNumberAssigningJurisdictionNameOfAlternateCodingSystem             string `json:"VisitNumberAssigningJurisdictionNameOfAlternateCodingSystem"`
	VisitNumberAssigningJurisdictionCodingSystemVersionID                   string `json:"VisitNumberAssigningJurisdictionCodingSystemVersionID"`
	VisitNumberAssigningJurisdictionAlternateCodingSystemVersionID          string `json:"VisitNumberAssigningJurisdictionAlternateCodingSystemVersionID"`
	VisitNumberAssigningJurisdictionOriginalText                            string `json:"VisitNumberAssigningJurisdictionOriginalText"`
	VisitNumberAssigningAgencyorDepartmentIdentifier                        string `json:"VisitNumberAssigningAgencyorDepartmentIdentifier"`
	VisitNumberAssigningAgencyorDepartmentText                              string `json:"VisitNumberAssigningAgencyorDepartmentText"`
	VisitNumberAssigningAgencyorDepartmentNameOfCodingSystem                string `json:"VisitNumberAssigningAgencyorDepartmentNameOfCodingSystem"`
	VisitNumberAssigningAgencyorDepartmentAlternateIdentifier               string `json:"VisitNumberAssigningAgencyorDepartmentAlternateIdentifier"`
	VisitNumberAssigningAgencyorDepartmentAlternateText                     string `json:"VisitNumberAssigningAgencyorDepartmentAlternateText"`
	VisitNumberAssigningAgencyorDepartmentNameOfAlternateCodingSystem       string `json:"VisitNumberAssigningAgencyorDepartmentNameOfAlternateCodingSystem"`
	VisitNumberAssigningAgencyorDepartmentCodingSystemVersionID             string `json:"VisitNumberAssigningAgencyorDepartmentCodingSystemVersionID"`
	VisitNumberAssigningAgencyorDepartmentAlternateCodingSystemVersionID    string `json:"VisitNumberAssigningAgencyorDepartmentAlternateCodingSystemVersionID"`
	VisitNumberAssigningAgencyorDepartmentOriginalText                      string `json:"VisitNumberAssigningAgencyorDepartmentOriginalText"`
	CourtesyCode                                                            string `json:"CourtesyCode"`
	CreditRating                                                            string `json:"CreditRating"`
	InterestCode                                                            string `json:"InterestCode"`
	TransferToBadDebtCode                                                   string `json:"TransferToBadDebtCode"`
	TransferToBadDebtTime                                                   string `json:"TransferToBadDebtTime"`
	TransferToBadDebtYear                                                   string `json:"TransferToBadDebtYear"`
	TransferToBadDebtMonth                                                  string `json:"TransferToBadDebtMonth"`
	TransferToBadDebtDay                                                    string `json:"TransferToBadDebtDay"`
	BadDebtAgencyCode                                                       string `json:"BadDebtAgencyCode"`
	BadDebtTransferAmount                                                   int    `json:"BadDebtTransferAmount"`
	BadDebtRecoveryAmount                                                   int    `json:"BadDebtRecoveryAmount"`
	DeleteAccountIndicator                                                  string `json:"DeleteAccountIndicator"`
	DeleteAccountTime                                                       string `json:"DeleteAccountTime"`
	DeleteAccountYear                                                       string `json:"DeleteAccountYear"`
	DeleteAccountMonth                                                      string `json:"DeleteAccountMonth"`
	DeleteAccountDay                                                        string `json:"DeleteAccountDay"`
	DischargeDisposition                                                    string `json:"DischargeDisposition"`
	DischargeLocation                                                       string `json:"DischargeLocation"`
	DischargeLocationTime                                                   string `json:"DischargeLocationTime"`
	DischargeLocationYear                                                   string `json:"DischargeLocationYear"`
	DischargeLocationMonth                                                  string `json:"DischargeLocationMonth"`
	DischargeLocationDay                                                    string `json:"DischargeLocationDay"`
	DischargeLocationHours                                                  string `json:"DischargeLocationHours"`
	DischargeLocationMinutes                                                string `json:"DischargeLocationMinutes"`
	DischargeLocationSeconds                                                string `json:"DischargeLocationSeconds"`
	DischargeLocationMills                                                  string `json:"DischargeLocationMills"`
	DischargeLocationGmtOffset                                              string `json:"DischargeLocationGmtOffset"`
	DischargeLocationPrecision                                              string `json:"DischargeLocationPrecision"`
	DietTypeIdentifier                                                      string `json:"DietTypeIdentifier"`
	DietTypeText                                                            string `json:"DietTypeText"`
	DietTypeNameOfCodingSystem                                              string `json:"DietTypeNameOfCodingSystem"`
	DietTypeAlternateIdentifier                                             string `json:"DietTypeAlternateIdentifier"`
	DietTypeAlternateText                                                   string `json:"DietTypeAlternateText"`
	DietTypeNameOfAlternateCodingSystem                                     string `json:"DietTypeNameOfAlternateCodingSystem"`
	ServicingFacility                                                       string `json:"ServicingFacility"`
	BedStatus                                                               string `json:"BedStatus"`
	AccountStatus                                                           string `json:"AccountStatus"`
	PendingLocationPointOfCare                                              string `json:"PendingLocationPointOfCare"`
	PendingLocationRoom                                                     string `json:"PendingLocationRoom"`
	PendingLocationBed                                                      string `json:"PendingLocationBed"`
	PendingLocationAANamespaceID                                            string `json:"PendingLocationAANamespaceID"`
	PendingLocationAAUniversalID                                            string `json:"PendingLocationAAUniversalID"`
	PendingLocationAAUniversalIDType                                        string `json:"PendingLocationAAUniversalIDType"`
	PendingLocationLocationStatus                                           string `json:"PendingLocationLocationStatus"`
	PendingLocationPatientLocationType                                      string `json:"PendingLocationPatientLocationType"`
	PendingLocationBuilding                                                 string `json:"PendingLocationBuilding"`
	PendingLocationFloor                                                    string `json:"PendingLocationFloor"`
	PendingLocationLocationDescription                                      string `json:"PendingLocationLocationDescription"`
	PendingComprehensiveLocationEntityIdentifier                            string `json:"PendingComprehensiveLocationEntityIdentifier"`
	PendingComprehensiveLocationNamespaceID                                 string `json:"PendingComprehensiveLocationNamespaceID"`
	PendingComprehensiveLocationUniversalID                                 string `json:"PendingComprehensiveLocationUniversalID"`
	PendingComprehensiveLocationUniversalIDType                             string `json:"PendingComprehensiveLocationUniversalIDType"`
	PendingLocationAFNamespaceID                                            string `json:"PendingLocationAFNamespaceID"`
	PendingLocationAFUniversalID                                            string `json:"PendingLocationAFUniversalID"`
	PendingLocationAFUniversalIDType                                        string `json:"PendingLocationAFUniversalIDType"`
	PriorTemporaryLocationPointOfCare                                       string `json:"PriorTemporaryLocationPointOfCare"`
	PriorTemporaryLocationRoom                                              string `json:"PriorTemporaryLocationRoom"`
	PriorTemporaryLocationBed                                               string `json:"PriorTemporaryLocationBed"`
	PriorTemporaryLocationFacilityNamespaceID                               string `json:"PriorTemporaryLocationFacilityNamespaceID"`
	PriorTemporaryLocationFacilityUniversalID                               string `json:"PriorTemporaryLocationFacilityUniversalID"`
	PriorTemporaryLocationFacilityUniversalIDType                           string `json:"PriorTemporaryLocationFacilityUniversalIDType"`
	PriorTemporaryLocationLocationStatus                                    string `json:"PriorTemporaryLocationLocationStatus"`
	PriorTemporaryLocationPatientLocationType                               string `json:"PriorTemporaryLocationPatientLocationType"`
	PriorTemporaryLocationBuilding                                          string `json:"PriorTemporaryLocationBuilding"`
	PriorTemporaryLocationFloor                                             string `json:"PriorTemporaryLocationFloor"`
	PriorTemporaryLocationDescription                                       string `json:"PriorTemporaryLocationDescription"`
	PriorTemporaryComprehensiveEntityIdentifier                             string `json:"PriorTemporaryComprehensiveEntityIdentifier"`
	PriorTemporaryComprehensiveNamespaceID                                  string `json:"PriorTemporaryComprehensiveNamespaceID"`
	PriorTemporaryComprehensiveUniversalID                                  string `json:"PriorTemporaryComprehensiveUniversalID"`
	PriorTemporaryComprehensiveUniversalIDType                              string `json:"PriorTemporaryComprehensiveUniversalIDType"`
	PriorTemporaryAANamespaceID                                             string `json:"PriorTemporaryAANamespaceID"`
	PriorTemporaryAAUniversalID                                             string `json:"PriorTemporaryAAUniversalID"`
	PriorTemporaryAAUniversalIDType                                         string `json:"PriorTemporaryAAUniversalIDType"`
	AdmitTime                                                               string `json:"AdmitTime"`
	AdmitYear                                                               string `json:"AdmitYear"`
	AdmitMonth                                                              string `json:"AdmitMonth"`
	AdmitDay                                                                string `json:"AdmitDay"`
	AdmitHours                                                              string `json:"AdmitHours"`
	AdmitMinutes                                                            string `json:"AdmitMinutes"`
	AdmitSeconds                                                            string `json:"AdmitSeconds"`
	AdmitMills                                                              string `json:"AdmitMills"`
	AdmitGmtOffset                                                          string `json:"AdmitGmtOffset"`
	AdmitPrecision                                                          string `json:"AdmitPrecision"`
	CurrentPatientBalance                                                   int    `json:"CurrentPatientBalance"`
	TotalCharges                                                            int    `json:"TotalCharges"`
	TotalAdjustments                                                        int    `json:"TotalAdjustments"`
	TotalPayments                                                           int    `json:"TotalPayments"`
	AlternateVisitIDNumber                                                  string `json:"AlternateVisitIDNumber"`
	AlternateVisitCheckDigit                                                string `json:"AlternateVisitCheckDigit"`
	AlternateVisitCheckDigitScheme                                          string `json:"AlternateVisitCheckDigitScheme"`
	AlternateVisitAANamespaceID                                             string `json:"AlternateVisitAANamespaceID"`
	AlternateVisitAAUniversalID                                             string `json:"AlternateVisitAAUniversalID"`
	AlternateVisitAAUniversalIDType                                         string `json:"AlternateVisitAAUniversalIDType"`
	AlternateVisitIdentifierTypeCode                                        string `json:"AlternateVisitIdentifierTypeCode"`
	AlternateVisitAFNamespaceID                                             string `json:"AlternateVisitAFNamespaceID"`
	AlternateVisitAFUniversalID                                             string `json:"AlternateVisitAFUniversalID"`
	AlternateVisitAFUniversalIDType                                         string `json:"AlternateVisitAFUniversalIDType"`
	AlternateVisitEffectiveTime                                             string `json:"AlternateVisitEffectiveTime"`
	AlternateVisitEffectiveYear                                             string `json:"AlternateVisitEffectiveYear"`
	AlternateVisitEffectiveMonth                                            string `json:"AlternateVisitEffectiveMonth"`
	AlternateVisitEffectiveDay                                              string `json:"AlternateVisitEffectiveDay"`
	AlternateVisitExpirationTime                                            string `json:"AlternateVisitExpirationTime"`
	AlternateVisitExpirationYear                                            string `json:"AlternateVisitExpirationYear"`
	AlternateVisitExpirationMonth                                           string `json:"AlternateVisitExpirationMonth"`
	AlternateVisitExpirationDay                                             string `json:"AlternateVisitExpirationDay"`
	AlternateVisitAssigningJurisdictionIdentifier                           string `json:"AlternateVisitAssigningJurisdictionIdentifier"`
	AlternateVisitAssigningJurisdictionText                                 string `json:"AlternateVisitAssigningJurisdictionText"`
	AlternateVisitAssigningJurisdictionNameOfCodingSystem                   string `json:"AlternateVisitAssigningJurisdictionNameOfCodingSystem"`
	AlternateVisitAssigningJurisdictionAlternateIdentifier                  string `json:"AlternateVisitAssigningJurisdictionAlternateIdentifier"`
	AlternateVisitAssigningJurisdictionAlternateText                        string `json:"AlternateVisitAssigningJurisdictionAlternateText"`
	AlternateVisitAssigningJurisdictionNameOfAlternateCodingSystem          string `json:"AlternateVisitAssigningJurisdictionNameOfAlternateCodingSystem"`
	AlternateVisitAssigningJurisdictionCodingSystemVersionID                string `json:"AlternateVisitAssigningJurisdictionCodingSystemVersionID"`
	AlternateVisitAssigningJurisdictionAlternateCodingSystemVersionID       string `json:"AlternateVisitAssigningJurisdictionAlternateCodingSystemVersionID"`
	AlternateVisitAssigningJurisdictionOriginalText                         string `json:"AlternateVisitAssigningJurisdictionOriginalText"`
	AlternateVisitAssigningAgencyorDepartmentIdentifier                     string `json:"AlternateVisitAssigningAgencyorDepartmentIdentifier"`
	AlternateVisitAssigningAgencyorDepartmentText                           string `json:"AlternateVisitAssigningAgencyorDepartmentText"`
	AlternateVisitAssigningAgencyorDepartmentNameOfCodingSystem             string `json:"AlternateVisitAssigningAgencyorDepartmentNameOfCodingSystem"`
	AlternateVisitAssigningAgencyorDepartmentAlternateIdentifier            string `json:"AlternateVisitAssigningAgencyorDepartmentAlternateIdentifier"`
	AlternateVisitAssigningAgencyorDepartmentAlternateText                  string `json:"AlternateVisitAssigningAgencyorDepartmentAlternateText"`
	AlternateVisitAssigningAgencyorDepartmentNameOfAlternateCodingSystem    string `json:"AlternateVisitAssigningAgencyorDepartmentNameOfAlternateCodingSystem"`
	AlternateVisitAssigningAgencyorDepartmentCodingSystemVersionID          string `json:"AlternateVisitAssigningAgencyorDepartmentCodingSystemVersionID"`
	AlternateVisitAssigningAgencyorDepartmentAlternateCodingSystemVersionID string `json:"AlternateVisitAssigningAgencyorDepartmentAlternateCodingSystemVersionID"`
	AlternateVisitAssigningAgencyorDepartmentOriginalText                   string `json:"AlternateVisitAssigningAgencyorDepartmentOriginalText"`
	VisitIndicator                                                          string `json:"VisitIndicator"`
	ChargePriceIndicator                                                    string `json:"ChargePriceIndicator"`
	DischargedtoLocation                                                    string `json:"DischargedtoLocation"`
	DietType                                                                string `json:"DietType"`
	PreadmitNumberIDNumber                                                  string `json:"PreadmitNumberIDNumber"`
	PreadmitNumberCheckDigit                                                string `json:"PreadmitNumberCheckDigit"`
	PreadmitNumberCheckDigitScheme                                          string `json:"PreadmitNumberCheckDigitScheme"`
	PreadmitNumberAANamespaceID                                             string `json:"PreadmitNumberAANamespaceID"`
	PreadmitNumberAAUniversalID                                             string `json:"PreadmitNumberAAUniversalID"`
	PreadmitNumberAAUniversalIDType                                         string `json:"PreadmitNumberAAUniversalIDType"`
	PreadmitNumberIdentifierTypeCode                                        string `json:"PreadmitNumberIdentifierTypeCode"`
	PreadmitNumberAFNamespaceID                                             string `json:"PreadmitNumberAFNamespaceID"`
	PreadmitNumberAFUniversalID                                             string `json:"PreadmitNumberAFUniversalID"`
	PreadmitNumberAFUniversalIDType                                         string `json:"PreadmitNumberAFUniversalIDType"`
	PreadmitNumberEffectiveTime                                             string `json:"PreadmitNumberEffectiveTime"`
	PreadmitNumberEffectiveYear                                             string `json:"PreadmitNumberEffectiveYear"`
	PreadmitNumberEffectiveMonth                                            string `json:"PreadmitNumberEffectiveMonth"`
	PreadmitNumberEffectiveDay                                              string `json:"PreadmitNumberEffectiveDay"`
	PreadmitNumberExpirationTime                                            string `json:"PreadmitNumberExpirationTime"`
	PreadmitNumberExpirationYear                                            string `json:"PreadmitNumberExpirationYear"`
	PreadmitNumberExpirationMonth                                           string `json:"PreadmitNumberExpirationMonth"`
	PreadmitNumberExpirationDay                                             string `json:"PreadmitNumberExpirationDay"`
	PreadmitNumberAssigningJurisdictionIdentifier                           string `json:"PreadmitNumberAssigningJurisdictionIdentifier"`
	PreadmitNumberAssigningJurisdictionText                                 string `json:"PreadmitNumberAssigningJurisdictionText"`
	PreadmitNumberAssigningJurisdictionNameOfCodingSystem                   string `json:"PreadmitNumberAssigningJurisdictionNameOfCodingSystem"`
	PreadmitNumberAssigningJurisdictionAlternateIdentifier                  string `json:"PreadmitNumberAssigningJurisdictionAlternateIdentifier"`
	PreadmitNumberAssigningJurisdictionAlternateText                        string `json:"PreadmitNumberAssigningJurisdictionAlternateText"`
	PreadmitNumberAssigningJurisdictionNameOfAlternateCodingSystem          string `json:"PreadmitNumberAssigningJurisdictionNameOfAlternateCodingSystem"`
	PreadmitNumberAssigningJurisdictionCodingSystemVersionID                string `json:"PreadmitNumberAssigningJurisdictionCodingSystemVersionID"`
	PreadmitNumberAssigningJurisdictionAlternateCodingSystemVersionID       string `json:"PreadmitNumberAssigningJurisdictionAlternateCodingSystemVersionID"`
	PreadmitNumberAssigningJurisdictionOriginalText                         string `json:"PreadmitNumberAssigningJurisdictionOriginalText"`
	PreadmitNumberAssigningAgencyorDepartmentIdentifier                     string `json:"PreadmitNumberAssigningAgencyorDepartmentIdentifier"`
	PreadmitNumberAssigningAgencyorDepartmentText                           string `json:"PreadmitNumberAssigningAgencyorDepartmentText"`
	PreadmitNumberAssigningAgencyorDepartmentNameOfCodingSystem             string `json:"PreadmitNumberAssigningAgencyorDepartmentNameOfCodingSystem"`
	PreadmitNumberAssigningAgencyorDepartmentAlternateIdentifier            string `json:"PreadmitNumberAssigningAgencyorDepartmentAlternateIdentifier"`
	PreadmitNumberAssigningAgencyorDepartmentAlternateText                  string `json:"PreadmitNumberAssigningAgencyorDepartmentAlternateText"`
	PreadmitNumberAssigningAgencyorDepartmentNameOfAlternateCodingSystem    string `json:"PreadmitNumberAssigningAgencyorDepartmentNameOfAlternateCodingSystem"`
	PreadmitNumberAssigningAgencyorDepartmentCodingSystemVersionID          string `json:"PreadmitNumberAssigningAgencyorDepartmentCodingSystemVersionID"`
	PreadmitNumberAssigningAgencyorDepartmentAlternateCodingSystemVersionID string `json:"PreadmitNumberAssigningAgencyorDepartmentAlternateCodingSystemVersionID"`
	PreadmitNumberAssigningAgencyorDepartmentOriginalText                   string `json:"PreadmitNumberAssigningAgencyorDepartmentOriginalText"`
	PreadmitNumberAssigningAuthority                                        string `json:"PreadmitNumberAssigningAuthority"`
	PreadmitNumberAssigningFacilityID                                       string `json:"PreadmitNumberAssigningFacilityID"`
	PV1AdmittingDoctor                                                      struct {
		Class                                                                    string `json:"$class"`
		UpdatedByUsername                                                        string `json:"UpdatedByUsername"`
		AdmittingDoctorIDNumber                                                  string `json:"AdmittingDoctorIDNumber"`
		AdmittingDoctorFamilySurname                                             string `json:"AdmittingDoctorFamilySurname"`
		AdmittingDoctorFamilyOwnSurnamePrefix                                    string `json:"AdmittingDoctorFamilyOwnSurnamePrefix"`
		AdmittingDoctorFamilyOwnSurname                                          string `json:"AdmittingDoctorFamilyOwnSurname"`
		AdmittingDoctorFamilySurnamePrefixFromPartner                            string `json:"AdmittingDoctorFamilySurnamePrefixFromPartner"`
		AdmittingDoctorFamilySurnameFromPartner                                  string `json:"AdmittingDoctorFamilySurnameFromPartner"`
		AdmittingDoctorGivenName                                                 string `json:"AdmittingDoctorGivenName"`
		AdmittingDoctorMiddleInitialOrName                                       string `json:"AdmittingDoctorMiddleInitialOrName"`
		AdmittingDoctorSuffix                                                    string `json:"AdmittingDoctorSuffix"`
		AdmittingDoctorPrefix                                                    string `json:"AdmittingDoctorPrefix"`
		AdmittingDoctorDegree                                                    string `json:"AdmittingDoctorDegree"`
		AdmittingDoctorSourceTable                                               string `json:"AdmittingDoctorSourceTable"`
		AdmittingDoctorAANamespaceID                                             string `json:"AdmittingDoctorAANamespaceID"`
		AdmittingDoctorAAUniversalID                                             string `json:"AdmittingDoctorAAUniversalID"`
		AdmittingDoctorAAUniversalIDType                                         string `json:"AdmittingDoctorAAUniversalIDType"`
		AdmittingDoctorNameTypeCode                                              string `json:"AdmittingDoctorNameTypeCode"`
		AdmittingDoctorIdentifierCheckDigit                                      string `json:"AdmittingDoctorIdentifierCheckDigit"`
		AdmittingDoctorCheckDigitScheme                                          string `json:"AdmittingDoctorCheckDigitScheme"`
		AdmittingDoctorIdentifierTypeCode                                        string `json:"AdmittingDoctorIdentifierTypeCode"`
		AdmittingDoctorAFNamespaceID                                             string `json:"AdmittingDoctorAFNamespaceID"`
		AdmittingDoctorAFUniversalID                                             string `json:"AdmittingDoctorAFUniversalID"`
		AdmittingDoctorAFUniversalIDType                                         string `json:"AdmittingDoctorAFUniversalIDType"`
		AdmittingDoctorNameRepresentationCode                                    string `json:"AdmittingDoctorNameRepresentationCode"`
		AdmittingDoctorNameContextIdentifier                                     string `json:"AdmittingDoctorNameContextIdentifier"`
		AdmittingDoctorNameContextText                                           string `json:"AdmittingDoctorNameContextText"`
		AdmittingDoctorNameContextNameOfCodingSystem                             string `json:"AdmittingDoctorNameContextNameOfCodingSystem"`
		AdmittingDoctorNameContextAlternateIdentifier                            string `json:"AdmittingDoctorNameContextAlternateIdentifier"`
		AdmittingDoctorNameContextAlternateText                                  string `json:"AdmittingDoctorNameContextAlternateText"`
		AdmittingDoctorNameContextNameOfAlternateCodingSystem                    string `json:"AdmittingDoctorNameContextNameOfAlternateCodingSystem"`
		AdmittingDoctorNameValidityRangeStartTime                                string `json:"AdmittingDoctorNameValidityRangeStartTime"`
		AdmittingDoctorNameValidityRangeStartYear                                string `json:"AdmittingDoctorNameValidityRangeStartYear"`
		AdmittingDoctorNameValidityRangeStartMonth                               string `json:"AdmittingDoctorNameValidityRangeStartMonth"`
		AdmittingDoctorNameValidityRangeStartDay                                 string `json:"AdmittingDoctorNameValidityRangeStartDay"`
		AdmittingDoctorNameValidityRangeStartHours                               string `json:"AdmittingDoctorNameValidityRangeStartHours"`
		AdmittingDoctorNameValidityRangeStartMinutes                             string `json:"AdmittingDoctorNameValidityRangeStartMinutes"`
		AdmittingDoctorNameValidityRangeStartSeconds                             string `json:"AdmittingDoctorNameValidityRangeStartSeconds"`
		AdmittingDoctorNameValidityRangeStartMills                               string `json:"AdmittingDoctorNameValidityRangeStartMills"`
		AdmittingDoctorNameValidityRangeStartGmtOffset                           string `json:"AdmittingDoctorNameValidityRangeStartGmtOffset"`
		AdmittingDoctorNameValidityRangeStartPrecision                           string `json:"AdmittingDoctorNameValidityRangeStartPrecision"`
		AdmittingDoctorNameValidityRangeEndTime                                  string `json:"AdmittingDoctorNameValidityRangeEndTime"`
		AdmittingDoctorNameValidityRangeEndYear                                  string `json:"AdmittingDoctorNameValidityRangeEndYear"`
		AdmittingDoctorNameValidityRangeEndMonth                                 string `json:"AdmittingDoctorNameValidityRangeEndMonth"`
		AdmittingDoctorNameValidityRangeEndDay                                   string `json:"AdmittingDoctorNameValidityRangeEndDay"`
		AdmittingDoctorNameValidityRangeEndHours                                 string `json:"AdmittingDoctorNameValidityRangeEndHours"`
		AdmittingDoctorNameValidityRangeEndMinutes                               string `json:"AdmittingDoctorNameValidityRangeEndMinutes"`
		AdmittingDoctorNameValidityRangeEndSeconds                               string `json:"AdmittingDoctorNameValidityRangeEndSeconds"`
		AdmittingDoctorNameValidityRangeEndMills                                 string `json:"AdmittingDoctorNameValidityRangeEndMills"`
		AdmittingDoctorNameValidityRangeEndGmtOffset                             string `json:"AdmittingDoctorNameValidityRangeEndGmtOffset"`
		AdmittingDoctorNameValidityRangeEndPrecision                             string `json:"AdmittingDoctorNameValidityRangeEndPrecision"`
		AdmittingDoctorNameAssemblyOrder                                         string `json:"AdmittingDoctorNameAssemblyOrder"`
		AdmittingDoctorEffectiveTime                                             string `json:"AdmittingDoctorEffectiveTime"`
		AdmittingDoctorEffectiveYear                                             string `json:"AdmittingDoctorEffectiveYear"`
		AdmittingDoctorEffectiveMonth                                            string `json:"AdmittingDoctorEffectiveMonth"`
		AdmittingDoctorEffectiveDay                                              string `json:"AdmittingDoctorEffectiveDay"`
		AdmittingDoctorEffectiveHours                                            string `json:"AdmittingDoctorEffectiveHours"`
		AdmittingDoctorEffectiveMinutes                                          string `json:"AdmittingDoctorEffectiveMinutes"`
		AdmittingDoctorEffectiveSeconds                                          string `json:"AdmittingDoctorEffectiveSeconds"`
		AdmittingDoctorEffectiveMills                                            string `json:"AdmittingDoctorEffectiveMills"`
		AdmittingDoctorEffectiveGmtOffset                                        string `json:"AdmittingDoctorEffectiveGmtOffset"`
		AdmittingDoctorEffectivePrecision                                        string `json:"AdmittingDoctorEffectivePrecision"`
		AdmittingDoctorExpirationTime                                            string `json:"AdmittingDoctorExpirationTime"`
		AdmittingDoctorExpirationYear                                            string `json:"AdmittingDoctorExpirationYear"`
		AdmittingDoctorExpirationMonth                                           string `json:"AdmittingDoctorExpirationMonth"`
		AdmittingDoctorExpirationDay                                             string `json:"AdmittingDoctorExpirationDay"`
		AdmittingDoctorExpirationHours                                           string `json:"AdmittingDoctorExpirationHours"`
		AdmittingDoctorExpirationMinutes                                         string `json:"AdmittingDoctorExpirationMinutes"`
		AdmittingDoctorExpirationSeconds                                         string `json:"AdmittingDoctorExpirationSeconds"`
		AdmittingDoctorExpirationMills                                           string `json:"AdmittingDoctorExpirationMills"`
		AdmittingDoctorExpirationGmtOffset                                       string `json:"AdmittingDoctorExpirationGmtOffset"`
		AdmittingDoctorExpirationPrecision                                       string `json:"AdmittingDoctorExpirationPrecision"`
		AdmittingDoctorProfessionalSuffix                                        string `json:"AdmittingDoctorProfessionalSuffix"`
		AdmittingDoctorAssigningJurisdictionIdentifier                           string `json:"AdmittingDoctorAssigningJurisdictionIdentifier"`
		AdmittingDoctorAssigningJurisdictionText                                 string `json:"AdmittingDoctorAssigningJurisdictionText"`
		AdmittingDoctorAssigningJurisdictionNameOfCodingSystem                   string `json:"AdmittingDoctorAssigningJurisdictionNameOfCodingSystem"`
		AdmittingDoctorAssigningJurisdictionAlternateIdentifier                  string `json:"AdmittingDoctorAssigningJurisdictionAlternateIdentifier"`
		AdmittingDoctorAssigningJurisdictionAlternateText                        string `json:"AdmittingDoctorAssigningJurisdictionAlternateText"`
		AdmittingDoctorAssigningJurisdictionNameOfAlternateCodingSystem          string `json:"AdmittingDoctorAssigningJurisdictionNameOfAlternateCodingSystem"`
		AdmittingDoctorAssigningJurisdictionCodingSystemVersionID                string `json:"AdmittingDoctorAssigningJurisdictionCodingSystemVersionID"`
		AdmittingDoctorAssigningJurisdictionAlternateCodingSystemVersionID       string `json:"AdmittingDoctorAssigningJurisdictionAlternateCodingSystemVersionID"`
		AdmittingDoctorAssigningJurisdictionOriginalText                         string `json:"AdmittingDoctorAssigningJurisdictionOriginalText"`
		AdmittingDoctorAssigningAgencyorDepartmentIdentifier                     string `json:"AdmittingDoctorAssigningAgencyorDepartmentIdentifier"`
		AdmittingDoctorAssigningAgencyorDepartmentText                           string `json:"AdmittingDoctorAssigningAgencyorDepartmentText"`
		AdmittingDoctorAssigningAgencyorDepartmentNameOfCodingSystem             string `json:"AdmittingDoctorAssigningAgencyorDepartmentNameOfCodingSystem"`
		AdmittingDoctorAssigningAgencyorDepartmentAlternateIdentifier            string `json:"AdmittingDoctorAssigningAgencyorDepartmentAlternateIdentifier"`
		AdmittingDoctorAssigningAgencyorDepartmentAlternateText                  string `json:"AdmittingDoctorAssigningAgencyorDepartmentAlternateText"`
		AdmittingDoctorAssigningAgencyorDepartmentNameOfAlternateCodingSystem    string `json:"AdmittingDoctorAssigningAgencyorDepartmentNameOfAlternateCodingSystem"`
		AdmittingDoctorAssigningAgencyorDepartmentCodingSystemVersionID          string `json:"AdmittingDoctorAssigningAgencyorDepartmentCodingSystemVersionID"`
		AdmittingDoctorAssigningAgencyorDepartmentAlternateCodingSystemVersionID string `json:"AdmittingDoctorAssigningAgencyorDepartmentAlternateCodingSystemVersionID"`
		AdmittingDoctorAssigningAgencyorDepartmentOriginalText                   string `json:"AdmittingDoctorAssigningAgencyorDepartmentOriginalText"`
		AdmitDoctorFamilyName                                                    string `json:"AdmitDoctorFamilyName"`
	} `json:"PV1AdmittingDoctor"`
	PV1AmbulatoryStatus struct {
		Class            string `json:"$class"`
		AmbulatoryStatus string `json:"AmbulatoryStatus"`
	} `json:"PV1AmbulatoryStatus"`
	PV1AttendingDoctor struct {
		Class                                                              string `json:"$class"`
		AttendingDoctorIDNumber                                            string `json:"AttendingDoctorIDNumber"`
		AttendingDoctorFamilySurname                                       string `json:"AttendingDoctorFamilySurname"`
		AttendingDoctorFamilyOwnSurnamePrefix                              string `json:"AttendingDoctorFamilyOwnSurnamePrefix"`
		AttendingDoctorFamilyOwnSurname                                    string `json:"AttendingDoctorFamilyOwnSurname"`
		AttendingDoctorFamilySurnamePrefixFromPartner                      string `json:"AttendingDoctorFamilySurnamePrefixFromPartner"`
		AttendingDoctorFamilySurnameFromPartner                            string `json:"AttendingDoctorFamilySurnameFromPartner"`
		AttendingDoctorGivenName                                           string `json:"AttendingDoctorGivenName"`
		AttendingDoctorMiddleInitialOrName                                 string `json:"AttendingDoctorMiddleInitialOrName"`
		AttendingDoctorSuffix                                              string `json:"AttendingDoctorSuffix"`
		AttendingDoctorPrefix                                              string `json:"AttendingDoctorPrefix"`
		AttendingDoctorDegreeDEPRECATEDFROM25                              string `json:"AttendingDoctorDegree_DEPRECATED_FROM_2_5"`
		AttendingDoctorSourceTable                                         string `json:"AttendingDoctorSourceTable"`
		AttendingDoctorAANamespaceID                                       string `json:"AttendingDoctorAANamespaceID"`
		AttendingDoctorAAUniversalID                                       string `json:"AttendingDoctorAAUniversalID"`
		AttendingDoctorAAUniversalIDType                                   string `json:"AttendingDoctorAAUniversalIDType"`
		AttendingDoctorNameTypeCode                                        string `json:"AttendingDoctorNameTypeCode"`
		AttendingDoctorIdentifierCheckDigit                                string `json:"AttendingDoctorIdentifierCheckDigit"`
		AttendingDoctorCheckDigitScheme                                    string `json:"AttendingDoctorCheckDigitScheme"`
		AttendingDoctorIdentifierTypeCode                                  string `json:"AttendingDoctorIdentifierTypeCode"`
		AttendingDoctorAFNamespaceID                                       string `json:"AttendingDoctorAFNamespaceID"`
		AttendingDoctorAFUniversalID                                       string `json:"AttendingDoctorAFUniversalID"`
		AttendingDoctorAFUniversalIDType                                   string `json:"AttendingDoctorAFUniversalIDType"`
		AttendingDoctorNameRepresentationCode                              string `json:"AttendingDoctorNameRepresentationCode"`
		AttendingDoctorNameContextIdentifier                               string `json:"AttendingDoctorNameContextIdentifier"`
		AttendingDoctorNameContextText                                     string `json:"AttendingDoctorNameContextText"`
		AttendingDoctorNameContextNameOfCodingSystem                       string `json:"AttendingDoctorNameContextNameOfCodingSystem"`
		AttendingDoctorNameContextAlternateIdentifier                      string `json:"AttendingDoctorNameContextAlternateIdentifier"`
		AttendingDoctorNameContextAlternateText                            string `json:"AttendingDoctorNameContextAlternateText"`
		AttendingDoctorNameContextNameOfAlternateCodingSystem              string `json:"AttendingDoctorNameContextNameOfAlternateCodingSystem"`
		AttendingDoctorNameValidityRangeStartTime                          string `json:"AttendingDoctorNameValidityRangeStartTime"`
		AttendingDoctorNameValidityRangeStartYear                          string `json:"AttendingDoctorNameValidityRangeStartYear"`
		AttendingDoctorNameValidityRangeStartMonth                         string `json:"AttendingDoctorNameValidityRangeStartMonth"`
		AttendingDoctorNameValidityRangeStartDay                           string `json:"AttendingDoctorNameValidityRangeStartDay"`
		AttendingDoctorNameValidityRangeStartHours                         string `json:"AttendingDoctorNameValidityRangeStartHours"`
		AttendingDoctorNameValidityRangeStartMinutes                       string `json:"AttendingDoctorNameValidityRangeStartMinutes"`
		AttendingDoctorNameValidityRangeStartSeconds                       string `json:"AttendingDoctorNameValidityRangeStartSeconds"`
		AttendingDoctorNameValidityRangeStartMills                         string `json:"AttendingDoctorNameValidityRangeStartMills"`
		AttendingDoctorNameValidityRangeStartGmtOffset                     string `json:"AttendingDoctorNameValidityRangeStartGmtOffset"`
		AttendingDoctorNameValidityRangeStartPrecision                     string `json:"AttendingDoctorNameValidityRangeStartPrecision"`
		AttendingDoctorNameValidityRangeEndTime                            string `json:"AttendingDoctorNameValidityRangeEndTime"`
		AttendingDoctorNameValidityRangeEndYear                            string `json:"AttendingDoctorNameValidityRangeEndYear"`
		AttendingDoctorNameValidityRangeEndMonth                           string `json:"AttendingDoctorNameValidityRangeEndMonth"`
		AttendingDoctorNameValidityRangeEndDay                             string `json:"AttendingDoctorNameValidityRangeEndDay"`
		AttendingDoctorNameValidityRangeEndHours                           string `json:"AttendingDoctorNameValidityRangeEndHours"`
		AttendingDoctorNameValidityRangeEndMinutes                         string `json:"AttendingDoctorNameValidityRangeEndMinutes"`
		AttendingDoctorNameValidityRangeEndSeconds                         string `json:"AttendingDoctorNameValidityRangeEndSeconds"`
		AttendingDoctorNameValidityRangeEndMills                           string `json:"AttendingDoctorNameValidityRangeEndMills"`
		AttendingDoctorNameValidityRangeEndGmtOffset                       string `json:"AttendingDoctorNameValidityRangeEndGmtOffset"`
		AttendingDoctorNameValidityRangeEndPrecision                       string `json:"AttendingDoctorNameValidityRangeEndPrecision"`
		NameAssemblyOrder                                                  string `json:"NameAssemblyOrder"`
		AttendingDoctorEffectiveTime                                       string `json:"AttendingDoctorEffectiveTime"`
		AttendingDoctorEffectiveYear                                       string `json:"AttendingDoctorEffectiveYear"`
		AttendingDoctorEffectiveMonth                                      string `json:"AttendingDoctorEffectiveMonth"`
		AttendingDoctorEffectiveDay                                        string `json:"AttendingDoctorEffectiveDay"`
		AttendingDoctorEffectiveHours                                      string `json:"AttendingDoctorEffectiveHours"`
		AttendingDoctorEffectiveMinutes                                    string `json:"AttendingDoctorEffectiveMinutes"`
		AttendingDoctorEffectiveSeconds                                    string `json:"AttendingDoctorEffectiveSeconds"`
		AttendingDoctorEffectiveMills                                      string `json:"AttendingDoctorEffectiveMills"`
		AttendingDoctorEffectiveGmtOffset                                  string `json:"AttendingDoctorEffectiveGmtOffset"`
		AttendingDoctorEffectivePrecision                                  string `json:"AttendingDoctorEffectivePrecision"`
		AttendingDoctorExpirationTime                                      string `json:"AttendingDoctorExpirationTime"`
		AttendingDoctorExpirationYear                                      string `json:"AttendingDoctorExpirationYear"`
		AttendingDoctorExpirationMonth                                     string `json:"AttendingDoctorExpirationMonth"`
		AttendingDoctorExpirationDay                                       string `json:"AttendingDoctorExpirationDay"`
		AttendingDoctorExpirationHours                                     string `json:"AttendingDoctorExpirationHours"`
		AttendingDoctorExpirationMinutes                                   string `json:"AttendingDoctorExpirationMinutes"`
		AttendingDoctorExpirationSeconds                                   string `json:"AttendingDoctorExpirationSeconds"`
		AttendingDoctorExpirationMills                                     string `json:"AttendingDoctorExpirationMills"`
		AttendingDoctorExpirationGmtOffset                                 string `json:"AttendingDoctorExpirationGmtOffset"`
		AttendingDoctorExpirationPrecision                                 string `json:"AttendingDoctorExpirationPrecision"`
		ProfessionalSuffix                                                 string `json:"ProfessionalSuffix"`
		AttendingDoctorAssigningJurisdictionIdentifier                     string `json:"AttendingDoctorAssigningJurisdictionIdentifier"`
		AttendingDoctorAssigningJurisdictionText                           string `json:"AttendingDoctorAssigningJurisdictionText"`
		AttendingDoctorAssigningJurisdictionNameOfCodingSystem             string `json:"AttendingDoctorAssigningJurisdictionNameOfCodingSystem"`
		AttendingDoctorAssigningJurisdictionAlternateIdentifier            string `json:"AttendingDoctorAssigningJurisdictionAlternateIdentifier"`
		AttendingDoctorAssigningJurisdictionAlternateText                  string `json:"AttendingDoctorAssigningJurisdictionAlternateText"`
		AttendingDoctorAssigningJurisdictionNameOfAlternateCodingSystem    string `json:"AttendingDoctorAssigningJurisdictionNameOfAlternateCodingSystem"`
		AttendingDoctorAssigningJurisdictionCodingSystemVersionID          string `json:"AttendingDoctorAssigningJurisdictionCodingSystemVersionID"`
		AttendingDoctorAssigningJurisdictionAlternateCodingSystemVersionID string `json:"AttendingDoctorAssigningJurisdictionAlternateCodingSystemVersionID"`
		AttendingDoctorAssigningJurisdictionOriginalText                   string `json:"AttendingDoctorAssigningJurisdictionOriginalText"`
		AttendingDoctorAgencyorDepartmentIdentifier                        string `json:"AttendingDoctorAgencyorDepartmentIdentifier"`
		AttendingDoctorAgencyorDepartmentText                              string `json:"AttendingDoctorAgencyorDepartmentText"`
		AttendingDoctorAgencyorDepartmentNameOfCodingSystem                string `json:"AttendingDoctorAgencyorDepartmentNameOfCodingSystem"`
		AttendingDoctorAgencyorDepartmentAlternateIdentifier               string `json:"AttendingDoctorAgencyorDepartmentAlternateIdentifier"`
		AttendingDoctorAgencyorDepartmentAlternateText                     string `json:"AttendingDoctorAgencyorDepartmentAlternateText"`
		AttendingDoctorAgencyorDepartmentNameOfAlternateCodingSystem       string `json:"AttendingDoctorAgencyorDepartmentNameOfAlternateCodingSystem"`
		AttendingDoctorAgencyorDepartmentCodingSystemVersionID             string `json:"AttendingDoctorAgencyorDepartmentCodingSystemVersionID"`
		AttendingDoctorAgencyorDepartmentAlternateCodingSystemVersionID    string `json:"AttendingDoctorAgencyorDepartmentAlternateCodingSystemVersionID"`
		AttendingDoctorAgencyorDepartmentOriginalText                      string `json:"AttendingDoctorAgencyorDepartmentOriginalText"`
		AttendingDoctorFamilyName                                          string `json:"AttendingDoctorFamilyName"`
	} `json:"PV1AttendingDoctor"`
	PV1ContractAmount struct {
		Class          string `json:"$class"`
		ContractAmount int    `json:"ContractAmount"`
	} `json:"PV1ContractAmount"`
	PV1ContractCode struct {
		Class        string `json:"$class"`
		ContractCode string `json:"ContractCode"`
	} `json:"PV1ContractCode"`
	PV1ContractEffective struct {
		Class                  string `json:"$class"`
		ContractEffectiveTime  string `json:"ContractEffectiveTime"`
		ContractEffectiveYear  string `json:"ContractEffectiveYear"`
		ContractEffectiveMonth string `json:"ContractEffectiveMonth"`
		ContractEffectiveDay   string `json:"ContractEffectiveDay"`
	} `json:"PV1ContractEffective"`
	PV1ContractPeriod struct {
		Class          string `json:"$class"`
		ContractPeriod int    `json:"ContractPeriod"`
	} `json:"PV1ContractPeriod"`
	PV1DischargeDate struct {
		Class                               string `json:"$class"`
		DischargeTime                       string `json:"DischargeTime"`
		DischargeYear                       string `json:"DischargeYear"`
		DischargeMonth                      string `json:"DischargeMonth"`
		DischargeDay                        string `json:"DischargeDay"`
		DischargeHours                      string `json:"DischargeHours"`
		DischargeMinutes                    string `json:"DischargeMinutes"`
		DischargeSeconds                    string `json:"DischargeSeconds"`
		DischargeMills                      string `json:"DischargeMills"`
		DischargeGmtOffset                  string `json:"DischargeGmtOffset"`
		DischarPV1FinancialClassgePrecision string `json:"DischarPV1FinancialClassgePrecision"`
	} `json:"PV1DischargeDate"`
	PV1FinancialClass struct {
		Class                   string `json:"$class"`
		FinancialClass          string `json:"FinancialClass"`
		FinancialClassTime      string `json:"FinancialClassTime"`
		FinancialClassYear      string `json:"FinancialClassYear"`
		FinancialClassMonth     string `json:"FinancialClassMonth"`
		FinancialClassDay       string `json:"FinancialClassDay"`
		FinancialClassHours     string `json:"FinancialClassHours"`
		FinancialClassMinutes   string `json:"FinancialClassMinutes"`
		FinancialClassSeconds   string `json:"FinancialClassSeconds"`
		FinancialClassMills     string `json:"FinancialClassMills"`
		FinancialClassGmtOffset string `json:"FinancialClassGmtOffset"`
		FinancialClassPrecision string `json:"FinancialClassPrecision"`
	} `json:"PV1FinancialClass"`
	PV1OtherHealthcareProvider struct {
		Class                                                                            string `json:"$class"`
		OtherHealthcareProviderIDNumber                                                  string `json:"OtherHealthcareProviderIDNumber"`
		OtherHealthcareProviderFamilySurname                                             string `json:"OtherHealthcareProviderFamilySurname"`
		OtherHealthcareProviderFamilyOwnSurnamePrefix                                    string `json:"OtherHealthcareProviderFamilyOwnSurnamePrefix"`
		OtherHealthcareProviderFamilyOwnSurname                                          string `json:"OtherHealthcareProviderFamilyOwnSurname"`
		OtherHealthcareProviderFamilySurnamePrefixFromPartner                            string `json:"OtherHealthcareProviderFamilySurnamePrefixFromPartner"`
		OtherHealthcareProviderFamilySurnameFromPartner                                  string `json:"OtherHealthcareProviderFamilySurnameFromPartner"`
		OtherHealthcareProviderGivenName                                                 string `json:"OtherHealthcareProviderGivenName"`
		OtherHealthcareProviderMiddleInitialOrName                                       string `json:"OtherHealthcareProviderMiddleInitialOrName"`
		OtherHealthcareProviderSuffix                                                    string `json:"OtherHealthcareProviderSuffix"`
		OtherHealthcareProviderPrefix                                                    string `json:"OtherHealthcareProviderPrefix"`
		OtherHealthcareProviderDegree                                                    string `json:"OtherHealthcareProviderDegree"`
		OtherHealthcareProviderSourceTable                                               string `json:"OtherHealthcareProviderSourceTable"`
		OtherHealthcareProviderAANamespaceID                                             string `json:"OtherHealthcareProviderAANamespaceID"`
		OtherHealthcareProviderAAUniversalID                                             string `json:"OtherHealthcareProviderAAUniversalID"`
		OtherHealthcareProviderAAUniversalIDType                                         string `json:"OtherHealthcareProviderAAUniversalIDType"`
		OtherHealthcareProviderNameTypeCode                                              string `json:"OtherHealthcareProviderNameTypeCode"`
		OtherHealthcareProviderIdentifierCheckDigit                                      string `json:"OtherHealthcareProviderIdentifierCheckDigit"`
		OtherHealthcareProviderCheckDigitScheme                                          string `json:"OtherHealthcareProviderCheckDigitScheme"`
		OtherHealthcareProviderIdentifierTypeCode                                        string `json:"OtherHealthcareProviderIdentifierTypeCode"`
		OtherHealthcareProviderAFNamespaceID                                             string `json:"OtherHealthcareProviderAFNamespaceID"`
		OtherHealthcareProviderAFUniversalID                                             string `json:"OtherHealthcareProviderAFUniversalID"`
		OtherHealthcareProviderAFUniversalIDType                                         string `json:"OtherHealthcareProviderAFUniversalIDType"`
		OtherHealthcareProviderNameRepresentationCode                                    string `json:"OtherHealthcareProviderNameRepresentationCode"`
		OtherHealthcareProviderNameContextIdentifier                                     string `json:"OtherHealthcareProviderNameContextIdentifier"`
		OtherHealthcareProviderNameContextText                                           string `json:"OtherHealthcareProviderNameContextText"`
		OtherHealthcareProviderNameContextNameOfCodingSystem                             string `json:"OtherHealthcareProviderNameContextNameOfCodingSystem"`
		OtherHealthcareProviderNameContextAlternateIdentifier                            string `json:"OtherHealthcareProviderNameContextAlternateIdentifier"`
		OtherHealthcareProviderNameContextAlternateText                                  string `json:"OtherHealthcareProviderNameContextAlternateText"`
		OtherHealthcareProviderNameContextNameOfAlternateCodingSystem                    string `json:"OtherHealthcareProviderNameContextNameOfAlternateCodingSystem"`
		OtherHealthcareProviderNameValidityRangeStartTime                                string `json:"OtherHealthcareProviderNameValidityRangeStartTime"`
		OtherHealthcareProviderNameValidityRangeStartYear                                string `json:"OtherHealthcareProviderNameValidityRangeStartYear"`
		OtherHealthcareProviderNameValidityRangeStartMonth                               string `json:"OtherHealthcareProviderNameValidityRangeStartMonth"`
		OtherHealthcareProviderNameValidityRangeStartDay                                 string `json:"OtherHealthcareProviderNameValidityRangeStartDay"`
		OtherHealthcareProviderNameValidityRangeStartHours                               string `json:"OtherHealthcareProviderNameValidityRangeStartHours"`
		OtherHealthcareProviderNameValidityRangeStartMinutes                             string `json:"OtherHealthcareProviderNameValidityRangeStartMinutes"`
		OtherHealthcareProviderNameValidityRangeStartSeconds                             string `json:"OtherHealthcareProviderNameValidityRangeStartSeconds"`
		OtherHealthcareProviderNameValidityRangeStartMills                               string `json:"OtherHealthcareProviderNameValidityRangeStartMills"`
		OtherHealthcareProviderNameValidityRangeStartGmtOffset                           string `json:"OtherHealthcareProviderNameValidityRangeStartGmtOffset"`
		OtherHealthcareProviderNameValidityRangeStartPrecision                           string `json:"OtherHealthcareProviderNameValidityRangeStartPrecision"`
		OtherHealthcareProviderNameValidityRangeEndTime                                  string `json:"OtherHealthcareProviderNameValidityRangeEndTime"`
		OtherHealthcareProviderNameValidityRangeEndYear                                  string `json:"OtherHealthcareProviderNameValidityRangeEndYear"`
		OtherHealthcareProviderNameValidityRangeEndMonth                                 string `json:"OtherHealthcareProviderNameValidityRangeEndMonth"`
		OtherHealthcareProviderNameValidityRangeEndDay                                   string `json:"OtherHealthcareProviderNameValidityRangeEndDay"`
		OtherHealthcareProviderNameValidityRangeEndHours                                 string `json:"OtherHealthcareProviderNameValidityRangeEndHours"`
		OtherHealthcareProviderNameValidityRangeEndMinutes                               string `json:"OtherHealthcareProviderNameValidityRangeEndMinutes"`
		OtherHealthcareProviderNameValidityRangeEndSeconds                               string `json:"OtherHealthcareProviderNameValidityRangeEndSeconds"`
		OtherHealthcareProviderNameValidityRangeEndMills                                 string `json:"OtherHealthcareProviderNameValidityRangeEndMills"`
		OtherHealthcareProviderNameValidityRangeEndGmtOffset                             string `json:"OtherHealthcareProviderNameValidityRangeEndGmtOffset"`
		OtherHealthcareProviderNameValidityRangeEndPrecision                             string `json:"OtherHealthcareProviderNameValidityRangeEndPrecision"`
		OtherHealthcareProviderNameAssemblyOrder                                         string `json:"OtherHealthcareProviderNameAssemblyOrder"`
		OtherHealthcareProviderEffectiveTime                                             string `json:"OtherHealthcareProviderEffectiveTime"`
		OtherHealthcareProviderEffectiveYear                                             string `json:"OtherHealthcareProviderEffectiveYear"`
		OtherHealthcareProviderEffectiveMonth                                            string `json:"OtherHealthcareProviderEffectiveMonth"`
		OtherHealthcareProviderEffectiveDay                                              string `json:"OtherHealthcareProviderEffectiveDay"`
		OtherHealthcareProviderEffectiveHours                                            string `json:"OtherHealthcareProviderEffectiveHours"`
		OtherHealthcareProviderEffectiveMinutes                                          string `json:"OtherHealthcareProviderEffectiveMinutes"`
		OtherHealthcareProviderEffectiveSeconds                                          string `json:"OtherHealthcareProviderEffectiveSeconds"`
		OtherHealthcareProviderEffectiveMills                                            string `json:"OtherHealthcareProviderEffectiveMills"`
		OtherHealthcareProviderEffectiveGmtOffset                                        string `json:"OtherHealthcareProviderEffectiveGmtOffset"`
		OtherHealthcareProviderEffectivePrecision                                        string `json:"OtherHealthcareProviderEffectivePrecision"`
		OtherHealthcareProviderExpirationTime                                            string `json:"OtherHealthcareProviderExpirationTime"`
		OtherHealthcareProviderExpirationYear                                            string `json:"OtherHealthcareProviderExpirationYear"`
		OtherHealthcareProviderExpirationMonth                                           string `json:"OtherHealthcareProviderExpirationMonth"`
		OtherHealthcareProviderExpirationDay                                             string `json:"OtherHealthcareProviderExpirationDay"`
		OtherHealthcareProviderExpirationHours                                           string `json:"OtherHealthcareProviderExpirationHours"`
		OtherHealthcareProviderExpirationMinutes                                         string `json:"OtherHealthcareProviderExpirationMinutes"`
		OtherHealthcareProviderExpirationSeconds                                         string `json:"OtherHealthcareProviderExpirationSeconds"`
		OtherHealthcareProviderExpirationMills                                           string `json:"OtherHealthcareProviderExpirationMills"`
		OtherHealthcareProviderExpirationGmtOffset                                       string `json:"OtherHealthcareProviderExpirationGmtOffset"`
		OtherHealthcareProviderExpirationPrecision                                       string `json:"OtherHealthcareProviderExpirationPrecision"`
		OtherHealthcareProviderProfessionalSuffix                                        string `json:"OtherHealthcareProviderProfessionalSuffix"`
		OtherHealthcareProviderAssigningJurisdictionIdentifier                           string `json:"OtherHealthcareProviderAssigningJurisdictionIdentifier"`
		OtherHealthcareProviderAssigningJurisdictionText                                 string `json:"OtherHealthcareProviderAssigningJurisdictionText"`
		OtherHealthcareProviderAssigningJurisdictionNameOfCodingSystem                   string `json:"OtherHealthcareProviderAssigningJurisdictionNameOfCodingSystem"`
		OtherHealthcareProviderAssigningJurisdictionAlternateIdentifier                  string `json:"OtherHealthcareProviderAssigningJurisdictionAlternateIdentifier"`
		OtherHealthcareProviderAssigningJurisdictionAlternateText                        string `json:"OtherHealthcareProviderAssigningJurisdictionAlternateText"`
		OtherHealthcareProviderAssigningJurisdictionNameOfAlternateCodingSystem          string `json:"OtherHealthcareProviderAssigningJurisdictionNameOfAlternateCodingSystem"`
		OtherHealthcareProviderAssigningJurisdictionCodingSystemVersionID                string `json:"OtherHealthcareProviderAssigningJurisdictionCodingSystemVersionID"`
		OtherHealthcareProviderAssigningJurisdictionAlternateCodingSystemVersionID       string `json:"OtherHealthcareProviderAssigningJurisdictionAlternateCodingSystemVersionID"`
		OtherHealthcareProviderAssigningJurisdictionOriginalText                         string `json:"OtherHealthcareProviderAssigningJurisdictionOriginalText"`
		OtherHealthcareProviderAssigningAgencyorDepartmentIdentifier                     string `json:"OtherHealthcareProviderAssigningAgencyorDepartmentIdentifier"`
		OtherHealthcareProviderAssigningAgencyorDepartmentText                           string `json:"OtherHealthcareProviderAssigningAgencyorDepartmentText"`
		OtherHealthcareProviderAssigningAgencyorDepartmentNameOfCodingSystem             string `json:"OtherHealthcareProviderAssigningAgencyorDepartmentNameOfCodingSystem"`
		OtherHealthcareProviderAssigningAgencyorDepartmentAlternateIdentifier            string `json:"OtherHealthcareProviderAssigningAgencyorDepartmentAlternateIdentifier"`
		OtherHealthcareProviderAssigningAgencyorDepartmentAlternateText                  string `json:"OtherHealthcareProviderAssigningAgencyorDepartmentAlternateText"`
		OtherHealthcareProviderAssigningAgencyorDepartmentNameOfAlternateCodingSystem    string `json:"OtherHealthcareProviderAssigningAgencyorDepartmentNameOfAlternateCodingSystem"`
		OtherHealthcareProviderAssigningAgencyorDepartmentCodingSystemVersionID          string `json:"OtherHealthcareProviderAssigningAgencyorDepartmentCodingSystemVersionID"`
		OtherHealthcareProviderAssigningAgencyorDepartmentAlternateCodingSystemVersionID string `json:"OtherHealthcareProviderAssigningAgencyorDepartmentAlternateCodingSystemVersionID"`
		OtherHealthcareProviderAssigningAgencyorDepartmentOriginalText                   string `json:"OtherHealthcareProviderAssigningAgencyorDepartmentOriginalText"`
		OthHealthProvFamilyName                                                          string `json:"OthHealthProvFamilyName"`
	} `json:"PV1OtherHealthcareProvider"`
	PV1ReferringDoctor struct {
		Class                                                                    string `json:"$class"`
		ReferringDoctorIDNumber                                                  string `json:"ReferringDoctorIDNumber"`
		ReferringDoctorFamilySurname                                             string `json:"ReferringDoctorFamilySurname"`
		ReferringDoctorFamilyOwnSurnamePrefix                                    string `json:"ReferringDoctorFamilyOwnSurnamePrefix"`
		ReferringDoctorFamilyOwnSurname                                          string `json:"ReferringDoctorFamilyOwnSurname"`
		ReferringDoctorFamilySurnamePrefixFromPartner                            string `json:"ReferringDoctorFamilySurnamePrefixFromPartner"`
		ReferringDoctorFamilySurnameFromPartner                                  string `json:"ReferringDoctorFamilySurnameFromPartner"`
		ReferringDoctorGivenName                                                 string `json:"ReferringDoctorGivenName"`
		ReferringDoctorMiddleInitialOrName                                       string `json:"ReferringDoctorMiddleInitialOrName"`
		ReferringDoctorSuffix                                                    string `json:"ReferringDoctorSuffix"`
		ReferringDoctorPrefix                                                    string `json:"ReferringDoctorPrefix"`
		ReferringDoctorDegreeDEPRECATEDFROM25                                    string `json:"ReferringDoctorDegree_DEPRECATED_FROM_2_5"`
		ReferringDoctorSourceTable                                               string `json:"ReferringDoctorSourceTable"`
		ReferringDoctorAANamespaceID                                             string `json:"ReferringDoctorAANamespaceID"`
		ReferringDoctorAAUniversalID                                             string `json:"ReferringDoctorAAUniversalID"`
		ReferringDoctorAAUniversalIDType                                         string `json:"ReferringDoctorAAUniversalIDType"`
		ReferringDoctorNameTypeCode                                              string `json:"ReferringDoctorNameTypeCode"`
		ReferringDoctorIdentifierCheckDigit                                      string `json:"ReferringDoctorIdentifierCheckDigit"`
		ReferringDoctorCheckDigitScheme                                          string `json:"ReferringDoctorCheckDigitScheme"`
		ReferringDoctorIdentifierTypeCode                                        string `json:"ReferringDoctorIdentifierTypeCode"`
		ReferringDoctorAFNamespaceID                                             string `json:"ReferringDoctorAFNamespaceID"`
		ReferringDoctorAFUniversalID                                             string `json:"ReferringDoctorAFUniversalID"`
		ReferringDoctorAFUniversalIDType                                         string `json:"ReferringDoctorAFUniversalIDType"`
		ReferringDoctorNameRepresentationCode                                    string `json:"ReferringDoctorNameRepresentationCode"`
		ReferringDoctorNameContextIdentifier                                     string `json:"ReferringDoctorNameContextIdentifier"`
		ReferringDoctorNameContextText                                           string `json:"ReferringDoctorNameContextText"`
		ReferringDoctorNameContextNameOfCodingSystem                             string `json:"ReferringDoctorNameContextNameOfCodingSystem"`
		ReferringDoctorNameContextAlternateIdentifier                            string `json:"ReferringDoctorNameContextAlternateIdentifier"`
		ReferringDoctorNameContextAlternateText                                  string `json:"ReferringDoctorNameContextAlternateText"`
		ReferringDoctorNameContextNameOfAlternateCodingSystem                    string `json:"ReferringDoctorNameContextNameOfAlternateCodingSystem"`
		ReferringDoctorNameValidityRangeStartTime                                string `json:"ReferringDoctorNameValidityRangeStartTime"`
		ReferringDoctorNameValidityRangeStartYear                                string `json:"ReferringDoctorNameValidityRangeStartYear"`
		ReferringDoctorNameValidityRangeStartMonth                               string `json:"ReferringDoctorNameValidityRangeStartMonth"`
		ReferringDoctorNameValidityRangeStartDay                                 string `json:"ReferringDoctorNameValidityRangeStartDay"`
		ReferringDoctorNameValidityRangeStartHours                               string `json:"ReferringDoctorNameValidityRangeStartHours"`
		ReferringDoctorNameValidityRangeStartMinutes                             string `json:"ReferringDoctorNameValidityRangeStartMinutes"`
		ReferringDoctorNameValidityRangeStartSeconds                             string `json:"ReferringDoctorNameValidityRangeStartSeconds"`
		ReferringDoctorNameValidityRangeStartMills                               string `json:"ReferringDoctorNameValidityRangeStartMills"`
		ReferringDoctorNameValidityRangeStartGmtOffset                           string `json:"ReferringDoctorNameValidityRangeStartGmtOffset"`
		ReferringDoctorNameValidityRangeStartPrecision                           string `json:"ReferringDoctorNameValidityRangeStartPrecision"`
		ReferringDoctorNameValidityRangeEndTime                                  string `json:"ReferringDoctorNameValidityRangeEndTime"`
		ReferringDoctorNameValidityRangeEndYear                                  string `json:"ReferringDoctorNameValidityRangeEndYear"`
		ReferringDoctorNameValidityRangeEndMonth                                 string `json:"ReferringDoctorNameValidityRangeEndMonth"`
		ReferringDoctorNameValidityRangeEndDay                                   string `json:"ReferringDoctorNameValidityRangeEndDay"`
		ReferringDoctorNameValidityRangeEndHours                                 string `json:"ReferringDoctorNameValidityRangeEndHours"`
		ReferringDoctorNameValidityRangeEndMinutes                               string `json:"ReferringDoctorNameValidityRangeEndMinutes"`
		ReferringDoctorNameValidityRangeEndSeconds                               string `json:"ReferringDoctorNameValidityRangeEndSeconds"`
		ReferringDoctorNameValidityRangeEndMills                                 string `json:"ReferringDoctorNameValidityRangeEndMills"`
		ReferringDoctorNameValidityRangeEndGmtOffset                             string `json:"ReferringDoctorNameValidityRangeEndGmtOffset"`
		ReferringDoctorNameValidityRangeEndPrecision                             string `json:"ReferringDoctorNameValidityRangeEndPrecision"`
		ReferringDoctorNameAssemblyOrder                                         string `json:"ReferringDoctorNameAssemblyOrder"`
		ReferringDoctorEffectiveTime                                             string `json:"ReferringDoctorEffectiveTime"`
		ReferringDoctorEffectiveYear                                             string `json:"ReferringDoctorEffectiveYear"`
		ReferringDoctorEffectiveMonth                                            string `json:"ReferringDoctorEffectiveMonth"`
		ReferringDoctorEffectiveDay                                              string `json:"ReferringDoctorEffectiveDay"`
		ReferringDoctorEffectiveHours                                            string `json:"ReferringDoctorEffectiveHours"`
		ReferringDoctorEffectiveMinutes                                          string `json:"ReferringDoctorEffectiveMinutes"`
		ReferringDoctorEffectiveSeconds                                          string `json:"ReferringDoctorEffectiveSeconds"`
		ReferringDoctorEffectiveMills                                            string `json:"ReferringDoctorEffectiveMills"`
		ReferringDoctorEffectiveGmtOffset                                        string `json:"ReferringDoctorEffectiveGmtOffset"`
		ReferringDoctorEffectivePrecision                                        string `json:"ReferringDoctorEffectivePrecision"`
		ReferringDoctorExpirationTime                                            string `json:"ReferringDoctorExpirationTime"`
		ReferringDoctorExpirationYear                                            string `json:"ReferringDoctorExpirationYear"`
		ReferringDoctorExpirationMonth                                           string `json:"ReferringDoctorExpirationMonth"`
		ReferringDoctorExpirationDay                                             string `json:"ReferringDoctorExpirationDay"`
		ReferringDoctorExpirationHours                                           string `json:"ReferringDoctorExpirationHours"`
		ReferringDoctorExpirationMinutes                                         string `json:"ReferringDoctorExpirationMinutes"`
		ReferringDoctorExpirationSeconds                                         string `json:"ReferringDoctorExpirationSeconds"`
		ReferringDoctorExpirationMills                                           string `json:"ReferringDoctorExpirationMills"`
		ReferringDoctorExpirationGmtOffset                                       string `json:"ReferringDoctorExpirationGmtOffset"`
		ReferringDoctorExpirationPrecision                                       string `json:"ReferringDoctorExpirationPrecision"`
		ReferringDoctorExpirationProfessionalSuffix                              string `json:"ReferringDoctorExpirationProfessionalSuffix"`
		ReferringDoctorAssigningJurisdictionIdentifier                           string `json:"ReferringDoctorAssigningJurisdictionIdentifier"`
		ReferringDoctorAssigningJurisdictionText                                 string `json:"ReferringDoctorAssigningJurisdictionText"`
		ReferringDoctorAssigningJurisdictionNameOfCodingSystem                   string `json:"ReferringDoctorAssigningJurisdictionNameOfCodingSystem"`
		ReferringDoctorAssigningJurisdictionAlternateIdentifier                  string `json:"ReferringDoctorAssigningJurisdictionAlternateIdentifier"`
		ReferringDoctorAssigningJurisdictionAlternateText                        string `json:"ReferringDoctorAssigningJurisdictionAlternateText"`
		ReferringDoctorAssigningJurisdictionNameOfAlternateCodingSystem          string `json:"ReferringDoctorAssigningJurisdictionNameOfAlternateCodingSystem"`
		ReferringDoctorAssigningJurisdictionCodingSystemVersionID                string `json:"ReferringDoctorAssigningJurisdictionCodingSystemVersionID"`
		ReferringDoctorAssigningJurisdictionAlternateCodingSystemVersionID       string `json:"ReferringDoctorAssigningJurisdictionAlternateCodingSystemVersionID"`
		ReferringDoctorAssigningJurisdictionOriginalText                         string `json:"ReferringDoctorAssigningJurisdictionOriginalText"`
		ReferringDoctorAssigningAgencyorDepartmentIdentifier                     string `json:"ReferringDoctorAssigningAgencyorDepartmentIdentifier"`
		ReferringDoctorAssigningAgencyorDepartmentText                           string `json:"ReferringDoctorAssigningAgencyorDepartmentText"`
		ReferringDoctorAssigningAgencyorDepartmentNameOfCodingSystem             string `json:"ReferringDoctorAssigningAgencyorDepartmentNameOfCodingSystem"`
		ReferringDoctorAssigningAgencyorDepartmentAlternateIdentifier            string `json:"ReferringDoctorAssigningAgencyorDepartmentAlternateIdentifier"`
		ReferringDoctorAssigningAgencyorDepartmentAlternateText                  string `json:"ReferringDoctorAssigningAgencyorDepartmentAlternateText"`
		ReferringDoctorAssigningAgencyorDepartmentNameOfAlternateCodingSystem    string `json:"ReferringDoctorAssigningAgencyorDepartmentNameOfAlternateCodingSystem"`
		ReferringDoctorAssigningAgencyorDepartmentCodingSystemVersionID          string `json:"ReferringDoctorAssigningAgencyorDepartmentCodingSystemVersionID"`
		ReferringDoctorAssigningAgencyorDepartmentAlternateCodingSystemVersionID string `json:"ReferringDoctorAssigningAgencyorDepartmentAlternateCodingSystemVersionID"`
		ReferringDoctorAssigningAgencyorDepartmentOriginalText                   string `json:"ReferringDoctorAssigningAgencyorDepartmentOriginalText"`
		RefDoctorFamilyName                                                      string `json:"RefDoctorFamilyName"`
	} `json:"PV1ReferringDoctor"`
}

func (mo *Hl7Pv1Format) fnAddPv1(ctx contractapi.TransactionContextInterface) error {

	err := FnValidationCheckStruct(mo)
	if err != nil {
		return err
	}
	mo.MSHPV1 = mo.MSHKEY + "_" + "PV1"
	pv1Bytes, err := ctx.GetStub().GetState(mo.MSHPV1)
	if pv1Bytes != nil || err != nil {
		return fmt.Errorf("Key Already Exists in the Network")
	}
	pv1Bytes, _ = json.Marshal(mo)
	return ctx.GetStub().PutState(mo.MSHPV1, pv1Bytes)
}
