package main

import (
	"encoding/json"
	"fmt"

	"github.com/hyperledger/fabric-contract-api-go/contractapi"
)

//Hl7PidFormat ..
type Hl7PidFormat struct {
	Class                                                                         string `json:"$class"`
	PIDKEY                                                                        string `json:"PIDKEY"`
	MSHPID                                                                        string `json:"MSH_PID"`
	MSHKEY                                                                        string `json:"MSHKEY"`
	SetID                                                                         string `json:"SetID"`
	PatientIDNumber                                                               string `json:"PatientIDNumber"`
	PatientCheckDigit                                                             string `json:"PatientCheckDigit"`
	PatientCheckDigitScheme                                                       string `json:"PatientCheckDigitScheme"`
	PatientAANamespaceID                                                          string `json:"PatientAANamespaceID"`
	PatientAAUniversalID                                                          string `json:"PatientAAUniversalID"`
	PatientAAUniversalIDType                                                      string `json:"PatientAAUniversalIDType"`
	PatientIdentifierTypeCode                                                     string `json:"PatientIdentifierTypeCode"`
	PatientAFNamespaceID                                                          string `json:"PatientAFNamespaceID"`
	PatientAFUniversalID                                                          string `json:"PatientAFUniversalID"`
	PatientAFUniversalIDType                                                      string `json:"PatientAFUniversalIDType"`
	PatientEffectiveTime                                                          string `json:"PatientEffectiveTime"`
	PatientEffectiveYear                                                          string `json:"PatientEffectiveYear"`
	PatientEffectiveMonth                                                         string `json:"PatientEffectiveMonth"`
	PatientEffectiveDay                                                           string `json:"PatientEffectiveDay"`
	PatientExpirationTime                                                         string `json:"PatientExpirationTime"`
	PatientExpirationYear                                                         string `json:"PatientExpirationYear"`
	PatientExpirationMonth                                                        string `json:"PatientExpirationMonth"`
	PatientExpirationDay                                                          string `json:"PatientExpirationDay"`
	AssigningJurisdictionIdentifier                                               string `json:"AssigningJurisdictionIdentifier"`
	AssigningJurisdictionText                                                     string `json:"AssigningJurisdictionText"`
	AssigningJurisdictionNameOfCodingSystem                                       string `json:"AssigningJurisdictionNameOfCodingSystem"`
	AssigningJurisdictionAlternateIdentifier                                      string `json:"AssigningJurisdictionAlternateIdentifier"`
	AssigningJurisdictionAlternateText                                            string `json:"AssigningJurisdictionAlternateText"`
	AssigningJurisdictionNameOfAlternateCodingSystem                              string `json:"AssigningJurisdictionNameOfAlternateCodingSystem"`
	AssigningJurisdictionCodingSystemVersionID                                    string `json:"AssigningJurisdictionCodingSystemVersionID"`
	AssigningJurisdictionAlternateCodingSystemVersionID                           string `json:"AssigningJurisdictionAlternateCodingSystemVersionID"`
	AssigningJurisdictionOriginalText                                             string `json:"AssigningJurisdictionOriginalText"`
	AssigningAgencyorDepartmentIdentifier                                         string `json:"AssigningAgencyorDepartmentIdentifier"`
	AssigningAgencyorDepartmentText                                               string `json:"AssigningAgencyorDepartmentText"`
	AssigningAgencyorDepartmentNameOfCodingSystem                                 string `json:"AssigningAgencyorDepartmentNameOfCodingSystem"`
	AssigningAgencyorDepartmentAlternateIdentifier                                string `json:"AssigningAgencyorDepartmentAlternateIdentifier"`
	AssigningAgencyorDepartmentAlternateText                                      string `json:"AssigningAgencyorDepartmentAlternateText"`
	AssigningAgencyorDepartmentNameOfAlternateCodingSystem                        string `json:"AssigningAgencyorDepartmentNameOfAlternateCodingSystem"`
	AssigningAgencyorDepartmentCodingSystemVersionID                              string `json:"AssigningAgencyorDepartmentCodingSystemVersionID"`
	AssigningAgencyorDepartmentOriginalText                                       string `json:"AssigningAgencyorDepartmentOriginalText"`
	DOBTime                                                                       string `json:"DOBTime"`
	DOBYear                                                                       string `json:"DOBYear"`
	DOBMonth                                                                      string `json:"DOBMonth"`
	DOBDay                                                                        string `json:"DOBDay"`
	DOBHours                                                                      string `json:"DOBHours"`
	DOBMinutes                                                                    string `json:"DOBMinutes"`
	DOBSeconds                                                                    string `json:"DOBSeconds"`
	DOBMills                                                                      string `json:"DOBMills"`
	DOBGmtOffset                                                                  string `json:"DOBGmtOffset"`
	DOBPrecision                                                                  string `json:"DOBPrecision"`
	Sex                                                                           string `json:"Sex"`
	AdressExpirationCountyCode                                                    string `json:"AdressExpirationCountyCode"`
	PrimaryLanguageIdentifier                                                     string `json:"PrimaryLanguageIdentifier"`
	PrimaryLanguageText                                                           string `json:"PrimaryLanguageText"`
	PrimaryLanguageNameOfCodingSystem                                             string `json:"PrimaryLanguageNameOfCodingSystem"`
	PrimaryLanguageAlternateIdentifier                                            string `json:"PrimaryLanguageAlternateIdentifier"`
	PrimaryLanguageAlternateText                                                  string `json:"PrimaryLanguageAlternateText"`
	PrimaryLanguageNameOfAlternateCodingSystem                                    string `json:"PrimaryLanguageNameOfAlternateCodingSystem"`
	MaritalStatusIdentifier                                                       string `json:"MaritalStatusIdentifier"`
	MaritalStatusText                                                             string `json:"MaritalStatusText"`
	MaritalStatusNameOfCodingSystem                                               string `json:"MaritalStatusNameOfCodingSystem"`
	MaritalStatusAlternateIdentifier                                              string `json:"MaritalStatusAlternateIdentifier"`
	MaritalStatusAlternateText                                                    string `json:"MaritalStatusAlternateText"`
	MaritalStatusNameOfAlternateCodingSystem                                      string `json:"MaritalStatusNameOfAlternateCodingSystem"`
	ReligionIdentifier                                                            string `json:"ReligionIdentifier"`
	ReligionText                                                                  string `json:"ReligionText"`
	ReligionNameOfCodingSystem                                                    string `json:"ReligionNameOfCodingSystem"`
	ReligionAlternateIdentifier                                                   string `json:"ReligionAlternateIdentifier"`
	ReligionAlternateText                                                         string `json:"ReligionAlternateText"`
	ReligionNameOfAlternateCodingSystem                                           string `json:"ReligionNameOfAlternateCodingSystem"`
	PatientAccountNumberIDNumber                                                  string `json:"PatientAccountNumberIDNumber"`
	PatientAccountNumberCheckDigit                                                string `json:"PatientAccountNumberCheckDigit"`
	PatientAccountNumberCheckDigitScheme                                          string `json:"PatientAccountNumberCheckDigitScheme"`
	PatientAccountNumberAANamespaceID                                             string `json:"PatientAccountNumberAANamespaceID"`
	PatientAccountNumberAAUniversalID                                             string `json:"PatientAccountNumberAAUniversalID"`
	PatientAccountNumberAAUniversalIDType                                         string `json:"PatientAccountNumberAAUniversalIDType"`
	PatientAccountNumberIdentifierTypeCode                                        string `json:"PatientAccountNumberIdentifierTypeCode"`
	PatientAccountNumberAFNamespaceID                                             string `json:"PatientAccountNumberAFNamespaceID"`
	PatientAccountNumberAFUniversalID                                             string `json:"PatientAccountNumberAFUniversalID"`
	PatientAccountNumberAFUniversalIDType                                         string `json:"PatientAccountNumberAFUniversalIDType"`
	PatientAccountNumberEffectiveTime                                             string `json:"PatientAccountNumberEffectiveTime"`
	PatientAccountNumberEffectiveYear                                             string `json:"PatientAccountNumberEffectiveYear"`
	PatientAccountNumberEffectiveMonth                                            string `json:"PatientAccountNumberEffectiveMonth"`
	PatientAccountNumberEffectiveDay                                              string `json:"PatientAccountNumberEffectiveDay"`
	PatientAccountNumberExpirationTime                                            string `json:"PatientAccountNumberExpirationTime"`
	PatientAccountNumberExpirationYear                                            string `json:"PatientAccountNumberExpirationYear"`
	PatientAccountNumberExpirationMonth                                           string `json:"PatientAccountNumberExpirationMonth"`
	PatientAccountNumberExpirationDay                                             string `json:"PatientAccountNumberExpirationDay"`
	PatientAccountNumberAssigningJurisdictionIdentifier                           string `json:"PatientAccountNumberAssigningJurisdictionIdentifier"`
	PatientAccountNumberAssigningJurisdictionText                                 string `json:"PatientAccountNumberAssigningJurisdictionText"`
	PatientAccountNumberAssigningJurisdictionNameOfCodingSystem                   string `json:"PatientAccountNumberAssigningJurisdictionNameOfCodingSystem"`
	PatientAccountNumberAssigningJurisdictionAlternateIdentifier                  string `json:"PatientAccountNumberAssigningJurisdictionAlternateIdentifier"`
	PatientAccountNumberAssigningJurisdictionAlternateText                        string `json:"PatientAccountNumberAssigningJurisdictionAlternateText"`
	PatientAccountNumberAssigningJurisdictionNameOfAlternateCodingSystem          string `json:"PatientAccountNumberAssigningJurisdictionNameOfAlternateCodingSystem"`
	PatientAccountNumberAssigningJurisdictionCodingSystemVersionID                string `json:"PatientAccountNumberAssigningJurisdictionCodingSystemVersionID"`
	PatientAccountNumberAssigningJurisdictionAlternateCodingSystemVersionID       string `json:"PatientAccountNumberAssigningJurisdictionAlternateCodingSystemVersionID"`
	PatientAccountNumberAssigningJurisdictionOriginalText                         string `json:"PatientAccountNumberAssigningJurisdictionOriginalText"`
	PatientAccountNumberAssigningAgencyorDepartmentnIdentifier                    string `json:"PatientAccountNumberAssigningAgencyorDepartmentnIdentifier"`
	PatientAccountNumberAssigningAgencyorDepartmentText                           string `json:"PatientAccountNumberAssigningAgencyorDepartmentText"`
	PatientAccountNumberAssigningAgencyorDepartmentNameOfCodingSystem             string `json:"PatientAccountNumberAssigningAgencyorDepartmentNameOfCodingSystem"`
	PatientAccountNumberAssigningAgencyorDepartmentAlternateIdentifier            string `json:"PatientAccountNumberAssigningAgencyorDepartmentAlternateIdentifier"`
	PatientAccountNumberAssigningAgencyorDepartmentAlternateText                  string `json:"PatientAccountNumberAssigningAgencyorDepartmentAlternateText"`
	PatientAccountNumberAssigningAgencyorDepartmentNameOfAlternateCodingSystem    string `json:"PatientAccountNumberAssigningAgencyorDepartmentNameOfAlternateCodingSystem"`
	PatientAccountNumberAssigningAgencyorDepartmentCodingSystemVersionID          string `json:"PatientAccountNumberAssigningAgencyorDepartmentCodingSystemVersionID"`
	PatientAccountNumberAssigningAgencyorDepartmentAlternateCodingSystemVersionID string `json:"PatientAccountNumberAssigningAgencyorDepartmentAlternateCodingSystemVersionID"`
	PatientAccountNumberAssigningAgencyorDepartmentOriginalText                   string `json:"PatientAccountNumberAssigningAgencyorDepartmentOriginalText"`
	SSNNumber                                                                     string `json:"SSNNumber"`
	DriversLicenseLicenseNumber                                                   string `json:"DriversLicenseLicenseNumber"`
	DriversLicenseIssuingStateProvinceCountry                                     string `json:"DriversLicenseIssuingStateProvinceCountry"`
	DriversLicenseTime                                                            string `json:"DriversLicenseTime"`
	DriversLicenseExpirationYear                                                  string `json:"DriversLicenseExpirationYear"`
	DriversLicenseExpirationMonth                                                 string `json:"DriversLicenseExpirationMonth"`
	DriversLicenseExpirationDay                                                   string `json:"DriversLicenseExpirationDay"`
	CitizenshipIdentifier                                                         string `json:"CitizenshipIdentifier"`
	CitizenshipText                                                               string `json:"CitizenshipText"`
	CitizenshipNameOfCodingSystem                                                 string `json:"CitizenshipNameOfCodingSystem"`
	CitizenshipAlternateIdentifier                                                string `json:"CitizenshipAlternateIdentifier"`
	CitizenshipAlternateText                                                      string `json:"CitizenshipAlternateText"`
	CitizenshipNameOfAlternateCodingSystem                                        string `json:"CitizenshipNameOfAlternateCodingSystem"`
	VeteransMilitaryStatusIdentifier                                              string `json:"VeteransMilitaryStatusIdentifier"`
	VeteransMilitaryStatusText                                                    string `json:"VeteransMilitaryStatusText"`
	VeteransMilitaryStatusNameOfCodingSystem                                      string `json:"VeteransMilitaryStatusNameOfCodingSystem"`
	VeteransMilitaryStatusAlternateIdentifier                                     string `json:"VeteransMilitaryStatusAlternateIdentifier"`
	VeteransMilitaryStatusAlternateText                                           string `json:"VeteransMilitaryStatusAlternateText"`
	VeteransMilitaryStatusNameOfAlternateCodingSystem                             string `json:"VeteransMilitaryStatusNameOfAlternateCodingSystem"`
	NationalityIdentifier                                                         string `json:"NationalityIdentifier"`
	NationalityText                                                               string `json:"NationalityText"`
	NationalityNameOfCodingSystem                                                 string `json:"NationalityNameOfCodingSystem"`
	NationalityAlternateIdentifier                                                string `json:"NationalityAlternateIdentifier"`
	NationalityAlternateText                                                      string `json:"NationalityAlternateText"`
	NationalityNameOfAlternateCodingSystem                                        string `json:"NationalityNameOfAlternateCodingSystem"`
	PatientDeathTime                                                              string `json:"PatientDeathTime"`
	PatientDeathYear                                                              string `json:"PatientDeathYear"`
	PatientDeathMonth                                                             string `json:"PatientDeathMonth"`
	PatientDeathDay                                                               string `json:"PatientDeathDay"`
	PatientDeathHours                                                             string `json:"PatientDeathHours"`
	PatientDeathMinutes                                                           string `json:"PatientDeathMinutes"`
	PatientDeathSeconds                                                           string `json:"PatientDeathSeconds"`
	PatientDeathMills                                                             string `json:"PatientDeathMills"`
	PatientDeathGmtOffset                                                         string `json:"PatientDeathGmtOffset"`
	PatientDeathPrecision                                                         string `json:"PatientDeathPrecision"`
	PatientDeathIndicator                                                         string `json:"PatientDeathIndicator"`
	IdentityUnknownIndicator                                                      string `json:"IdentityUnknownIndicator"`
	LastUpdateTime                                                                string `json:"LastUpdateTime"`
	LastUpdateYear                                                                string `json:"LastUpdateYear"`
	LastUpdateMonth                                                               string `json:"LastUpdateMonth"`
	LastUpdateDay                                                                 string `json:"LastUpdateDay"`
	LastUpdateHours                                                               string `json:"LastUpdateHours"`
	LastUpdateMinutes                                                             string `json:"LastUpdateMinutes"`
	LastUpdateSeconds                                                             string `json:"LastUpdateSeconds"`
	LastUpdateMills                                                               string `json:"LastUpdateMills"`
	LastUpdateGmtOffset                                                           string `json:"LastUpdateGmtOffset"`
	LastUpdatePrecision                                                           string `json:"LastUpdatePrecision"`
	LastUpdateFacilityNamespaceID                                                 string `json:"LastUpdateFacilityNamespaceID"`
	LastUpdateFacilityUniversalID                                                 string `json:"LastUpdateFacilityUniversalID"`
	LastUpdateFacilityUniversalIDType                                             string `json:"LastUpdateFacilityUniversalIDType"`
	SpeciesCodeIdentifier                                                         string `json:"SpeciesCodeIdentifier"`
	SpeciesCodeText                                                               string `json:"SpeciesCodeText"`
	SpeciesCodeNameOfCodingSystem                                                 string `json:"SpeciesCodeNameOfCodingSystem"`
	SpeciesCodeAlternateIdentifier                                                string `json:"SpeciesCodeAlternateIdentifier"`
	SpeciesCodeAlternateText                                                      string `json:"SpeciesCodeAlternateText"`
	SpeciesCodeNameOfAlternateCodingSystem                                        string `json:"SpeciesCodeNameOfAlternateCodingSystem"`
	BreedCodeIdentifier                                                           string `json:"BreedCodeIdentifier"`
	BreedCodeText                                                                 string `json:"BreedCodeText"`
	BreedCodeNameOfCodingSystem                                                   string `json:"BreedCodeNameOfCodingSystem"`
	BreedCodeAlternateIdentifier                                                  string `json:"BreedCodeAlternateIdentifier"`
	BreedCodeAlternateText                                                        string `json:"BreedCodeAlternateText"`
	BreedCodeNameOfAlternateCodingSystem                                          string `json:"BreedCodeNameOfAlternateCodingSystem"`
	BreedCodeStrain                                                               string `json:"BreedCodeStrain"`
	BirthPlace                                                                    string `json:"BirthPlace"`
	MultipleBirthIndicator                                                        string `json:"MultipleBirthIndicator"`
	BirthOrder                                                                    string `json:"BirthOrder"`
	MaritalStatus                                                                 string `json:"MaritalStatus"`
	Religion                                                                      string `json:"Religion"`
	PatientNameFamilyName                                                         string `json:"PatientNameFamilyName"`
	MothersMaidenNameFamilyName                                                   string `json:"MothersMaidenNameFamilyName"`
	PatientAliasFamilyName                                                        string `json:"PatientAliasFamilyName"`
	PatientAddressStreetAddress                                                   string `json:"PatientAddressStreetAddress"`
	PatientAccountNumber                                                          string `json:"PatientAccountNumber"`
	PIDDateTimeOfBirth                                                            string `json:"PIDDateTimeOfBirth"`
	PIDGender                                                                     string `json:"PIDGender"`
	PIDAlternatePatient                                                           struct {
		Class                                                               string `json:"$class"`
		AlternatePatientIDNumber                                            string `json:"AlternatePatientIDNumber"`
		AlternatePatientCheckDigit                                          string `json:"AlternatePatientCheckDigit"`
		AlternatePatientCheckDigitSchemeEmployed                            string `json:"AlternatePatientCheckDigitSchemeEmployed"`
		AlternatePatientAANamespaceID                                       string `json:"AlternatePatientAANamespaceID"`
		AlternatePatientAAUniversalID                                       string `json:"AlternatePatientAAUniversalID"`
		AlternatePatientAAUniversalIDType                                   string `json:"AlternatePatientAAUniversalIDType"`
		IdentifierTypeCode                                                  string `json:"IdentifierTypeCode"`
		AlternatePatientAFNamespaceID                                       string `json:"AlternatePatientAFNamespaceID"`
		AlternatePatientAFUniversalID                                       string `json:"AlternatePatientAFUniversalID"`
		AlternatePatientAFUniversalIDType                                   string `json:"AlternatePatientAFUniversalIDType"`
		AlternatePatientEffectivetTime                                      string `json:"AlternatePatientEffectivetTime"`
		AlternatePatientEffectivetYear                                      string `json:"AlternatePatientEffectivetYear"`
		AlternatePatientEffectiveMonth                                      string `json:"AlternatePatientEffectiveMonth"`
		AlternatePatientEffectiveDay                                        string `json:"AlternatePatientEffectiveDay"`
		AlternatePatientExpirationTime                                      string `json:"AlternatePatientExpirationTime"`
		AlternatePatientExpirationYear                                      string `json:"AlternatePatientExpirationYear"`
		AlternatePatientExpirationMonth                                     string `json:"AlternatePatientExpirationMonth"`
		AlternatePatientExpirationDay                                       string `json:"AlternatePatientExpirationDay"`
		AlternatePatientAssigningJurisdictionIdentifier                     string `json:"AlternatePatientAssigningJurisdictionIdentifier"`
		AlternatePatientAssigningJurisdictionText                           string `json:"AlternatePatientAssigningJurisdictionText"`
		AlternatePatientAssigningJurisdictionNameOfCodingSystem             string `json:"AlternatePatientAssigningJurisdictionNameOfCodingSystem"`
		AlternatePatientAssigningJurisdictionAlternateIdentifier            string `json:"AlternatePatientAssigningJurisdictionAlternateIdentifier"`
		AlternatePatientAssigningJurisdictionAlternateText                  string `json:"AlternatePatientAssigningJurisdictionAlternateText"`
		AlternatePatientAssigningJurisdictionNameOfAlternateCodingSystem    string `json:"AlternatePatientAssigningJurisdictionNameOfAlternateCodingSystem"`
		AlternatePatientAssigningJurisdictionCodingSystemVersionID          string `json:"AlternatePatientAssigningJurisdictionCodingSystemVersionID"`
		AlternatePatientAssigningJurisdictionAlternateCodingSystemVersionID string `json:"AlternatePatientAssigningJurisdictionAlternateCodingSystemVersionID"`
		AlternatePatientAssigningJurisdictionOriginalText                   string `json:"AlternatePatientAssigningJurisdictionOriginalText"`
		AlternatePatientAssigningAgencyorDepartmentIdentifier               string `json:"AlternatePatientAssigningAgencyorDepartmentIdentifier"`
		AlternatePatientAssigningAgencyorDepartmentText                     string `json:"AlternatePatientAssigningAgencyorDepartmentText"`
	} `json:"PIDAlternatePatient"`
	PIDBusinessPhone struct {
		Class                                  string `json:"$class"`
		BusinessTelephoneNumber                string `json:"BusinessTelephoneNumber"`
		BusinessTelecommunicationUseCode       string `json:"BusinessTelecommunicationUseCode"`
		BusinessTelecommunicationEquipmentType string `json:"BusinessTelecommunicationEquipmentType"`
		BusinessEmailAddress                   string `json:"BusinessEmailAddress"`
		BusinessCountryCode                    int    `json:"BusinessCountryCode"`
		BusinessAreaOrCityCode                 int    `json:"BusinessAreaOrCityCode"`
		BusinessPhoneNumber                    int    `json:"BusinessPhoneNumber"`
		BusinessExtension                      int    `json:"BusinessExtension"`
		BusinessAnyText                        string `json:"BusinessAnyText"`
		BusinessExtensionPrefix                string `json:"BusinessExtensionPrefix"`
		BusinessSpeedDialCode                  string `json:"BusinessSpeedDialCode"`
		BusinessUnformattedTelephonenumber     string `json:"BusinessUnformattedTelephonenumber"`
	} `json:"PIDBusinessPhone"`
	PIDEthnicGroup struct {
		Class                                  string `json:"$class"`
		EthnicGroupIdentifier                  string `json:"EthnicGroupIdentifier"`
		EthnicGroupText                        string `json:"EthnicGroupText"`
		EthnicGroupNameOfCodingSystem          string `json:"EthnicGroupNameOfCodingSystem"`
		EthnicGroupAlternateIdentifier         string `json:"EthnicGroupAlternateIdentifier"`
		EthnicGroupAlternateText               string `json:"EthnicGroupAlternateText"`
		EthnicGroupNameOfAlternateCodingSystem string `json:"EthnicGroupNameOfAlternateCodingSystem"`
		EthnicGroup                            string `json:"EthnicGroup"`
	} `json:"PIDEthnicGroup"`
	PIDCitizenship struct {
		Class                                  string `json:"$class"`
		CitizenshipIdentifier                  string `json:"CitizenshipIdentifier"`
		CitizenshipText                        string `json:"CitizenshipText"`
		CitizenshipNameOfCodingSystem          string `json:"CitizenshipNameOfCodingSystem"`
		Citizenship                            string `json:"Citizenship"`
		CitizenshipAlternateIdentifier         string `json:"CitizenshipAlternateIdentifier"`
		CitizenshipAlternateText               string `json:"CitizenshipAlternateText"`
		CitizenshipNameOfAlternateCodingSystem string `json:"CitizenshipNameOfAlternateCodingSystem"`
	} `json:"PIDCitizenship"`
	PIDIdentityReliabilityCode struct {
		Class                   string `json:"$class"`
		IdentityReliabilityCode string `json:"IdentityReliabilityCode"`
	} `json:"PIDIdentityReliabilityCode"`
	PIDHomePhone struct {
		Class                          string `json:"$class"`
		TelephoneNumber                string `json:"TelephoneNumber"`
		TelecommunicationUseCode       string `json:"TelecommunicationUseCode"`
		TelecommunicationEquipmentType string `json:"TelecommunicationEquipmentType"`
		EmailAddress                   string `json:"EmailAddress"`
		CountryCode                    int    `json:"CountryCode"`
		AreaOrCityCode                 int    `json:"AreaOrCityCode"`
		PhoneNumber                    int    `json:"PhoneNumber"`
		Extension                      int    `json:"Extension"`
		ExtensionPrefix                string `json:"ExtensionPrefix"`
		SpeedDialCode                  string `json:"SpeedDialCode"`
		UnformattedTelephonenumber     string `json:"UnformattedTelephonenumber"`
	} `json:"PIDHomePhone"`
	PIDMothersID struct {
		Class                                                        string `json:"$class"`
		MotherIDNumber                                               string `json:"MotherIDNumber"`
		MotherCheckDigit                                             string `json:"MotherCheckDigit"`
		MotherCheckDigitScheme                                       string `json:"MotherCheckDigitScheme"`
		MotherAANamespaceID                                          string `json:"MotherAANamespaceID"`
		MotherAAUniversalID                                          string `json:"MotherAAUniversalID"`
		MotherAAUniversalIDType                                      string `json:"MotherAAUniversalIDType"`
		MotherIdentifierTypeCode                                     string `json:"MotherIdentifierTypeCode"`
		MotherAFNamespaceID                                          string `json:"MotherAFNamespaceID"`
		MotherAFUniversalID                                          string `json:"MotherAFUniversalID"`
		MotherAFUniversalIDType                                      string `json:"MotherAFUniversalIDType"`
		MotherEffectiveTime                                          string `json:"MotherEffectiveTime"`
		MotherEffectiveYear                                          string `json:"MotherEffectiveYear"`
		MotherEffectiveMonth                                         string `json:"MotherEffectiveMonth"`
		MotherEffectiveDay                                           string `json:"MotherEffectiveDay"`
		MotherExpirationTime                                         string `json:"MotherExpirationTime"`
		MotherExpirationYear                                         string `json:"MotherExpirationYear"`
		MotherExpirationMonth                                        string `json:"MotherExpirationMonth"`
		MotherExpirationDay                                          string `json:"MotherExpirationDay"`
		MotherAssigningJurisdictionIdentifier                        string `json:"MotherAssigningJurisdictionIdentifier"`
		MotherAssigningJurisdictionText                              string `json:"MotherAssigningJurisdictionText"`
		MotherAssigningJurisdictionNameOfCodingSystem                string `json:"MotherAssigningJurisdictionNameOfCodingSystem"`
		MotherAssigningJurisdictionAlternateIdentifier               string `json:"MotherAssigningJurisdictionAlternateIdentifier"`
		MotherAssigningJurisdictionAlternateText                     string `json:"MotherAssigningJurisdictionAlternateText"`
		MotherAssigningJurisdictionNameOfAlternateCodingSystem       string `json:"MotherAssigningJurisdictionNameOfAlternateCodingSystem"`
		MotherAssigningJurisdictionCodingSystemVersionID             string `json:"MotherAssigningJurisdictionCodingSystemVersionID"`
		MotherAssigningJurisdictionAlternateCodingSystemVersionID    string `json:"MotherAssigningJurisdictionAlternateCodingSystemVersionID"`
		MotherAssigningJurisdictionOriginalText                      string `json:"MotherAssigningJurisdictionOriginalText"`
		MotherAssigningAgencyorDepartmentIdentifier                  string `json:"MotherAssigningAgencyorDepartmentIdentifier"`
		MotherAssigningAgencyorDepartmentText                        string `json:"MotherAssigningAgencyorDepartmentText"`
		MotherAssigningAgencyorDepartmentNameOfCodingSystem          string `json:"MotherAssigningAgencyorDepartmentNameOfCodingSystem"`
		MotherAssigningAgencyorDepartmentAlternateIdentifier         string `json:"MotherAssigningAgencyorDepartmentAlternateIdentifier"`
		MotherAssigningAgencyorDepartmentAlternateText               string `json:"MotherAssigningAgencyorDepartmentAlternateText"`
		MotherAssigningAgencyorDepartmentNameOfAlternateCodingSystem string `json:"MotherAssigningAgencyorDepartmentNameOfAlternateCodingSystem"`
	} `json:"PIDMothersId"`
	PIDMothersMaiden struct {
		Class                                               string `json:"$class"`
		MothersMaidenFamilySurname                          string `json:"MothersMaidenFamilySurname"`
		MothersMaidenFamilyOwnSurnamePrefix                 string `json:"MothersMaidenFamilyOwnSurnamePrefix"`
		MothersMaidenFamilyOwnSurname                       string `json:"MothersMaidenFamilyOwnSurname"`
		MothersMaidenFamilySurnamePrefixFromPartner         string `json:"MothersMaidenFamilySurnamePrefixFromPartner"`
		MothersMaidenFamilySurnameFromPartnerSpouse         string `json:"MothersMaidenFamilySurnameFromPartnerSpouse"`
		MothersMaidenGivenName                              string `json:"MothersMaidenGivenName"`
		MothersMaidenMiddleInitialOrName                    string `json:"MothersMaidenMiddleInitialOrName"`
		MothersMaidenSuffix                                 string `json:"MothersMaidenSuffix"`
		MothersMaidenPrefix                                 string `json:"MothersMaidenPrefix"`
		MothersMaidenDegree                                 string `json:"MothersMaidenDegree"`
		MothersMaidenNameTypeCode                           string `json:"MothersMaidenNameTypeCode"`
		MothersMaidenNameRepresentationCode                 string `json:"MothersMaidenNameRepresentationCode"`
		MothersMaidenNameContextIdentifier                  string `json:"MothersMaidenNameContextIdentifier"`
		MothersMaidenNameContextText                        string `json:"MothersMaidenNameContextText"`
		MothersMaidenNameContextNameOfCodingSystem          string `json:"MothersMaidenNameContextNameOfCodingSystem"`
		MothersMaidenNameContextAlternateIdentifier         string `json:"MothersMaidenNameContextAlternateIdentifier"`
		MothersMaidenNameContextAlternateText               string `json:"MothersMaidenNameContextAlternateText"`
		MothersMaidenNameContextNameOfAlternateCodingSystem string `json:"MothersMaidenNameContextNameOfAlternateCodingSystem"`
		MothersMaidenNameValidityRangeStartTime             string `json:"MothersMaidenNameValidityRangeStartTime"`
		MothersMaidenNameValidityRangeStartYear             string `json:"MothersMaidenNameValidityRangeStartYear"`
		MothersMaidenNameValidityRangeStartMonth            string `json:"MothersMaidenNameValidityRangeStartMonth"`
		MothersMaidenNameValidityRangeStartDay              string `json:"MothersMaidenNameValidityRangeStartDay"`
		MothersMaidenNameValidityRangeStartHours            string `json:"MothersMaidenNameValidityRangeStartHours"`
		MothersMaidenNameValidityRangeStartMinutes          string `json:"MothersMaidenNameValidityRangeStartMinutes"`
		MothersMaidenNameValidityRangeStartSeconds          string `json:"MothersMaidenNameValidityRangeStartSeconds"`
		MothersMaidenNameValidityRangeStartMills            string `json:"MothersMaidenNameValidityRangeStartMills"`
		MothersMaidenNameValidityRangeStartGmtOffset        string `json:"MothersMaidenNameValidityRangeStartGmtOffset"`
		MothersMaidenNameValidityRangeStartPrecision        string `json:"MothersMaidenNameValidityRangeStartPrecision"`
		MothersMaidenNameValidityRangeEndTime               string `json:"MothersMaidenNameValidityRangeEndTime"`
		MothersMaidenNameValidityRangeEndYear               string `json:"MothersMaidenNameValidityRangeEndYear"`
		MothersMaidenNameValidityRangeEndMonth              string `json:"MothersMaidenNameValidityRangeEndMonth"`
	} `json:"PIDMothersMaiden"`
	PIDPatientAddress struct {
		Class                             string `json:"$class"`
		PatientStreetOrMailingAddress     string `json:"PatientStreetOrMailingAddress"`
		PatientStreetName                 string `json:"PatientStreetName"`
		PatientDwellingNumber             string `json:"PatientDwellingNumber"`
		PatientOtherDesignation           string `json:"PatientOtherDesignation"`
		PatientCity                       string `json:"PatientCity"`
		PatientStateOrProvince            string `json:"PatientStateOrProvince"`
		PatientZipOrPostalCode            string `json:"PatientZipOrPostalCode"`
		PatientCountry                    string `json:"PatientCountry"`
		PatientAddressType                string `json:"PatientAddressType"`
		PatientOtherGeographicDesignation string `json:"PatientOtherGeographicDesignation"`
		PatientCountyOrParishCode         string `json:"PatientCountyOrParishCode"`
		PatientCensusTract                string `json:"PatientCensusTract"`
		PatientAddressRepresentationCode  string `json:"PatientAddressRepresentationCode"`
		AdressValidityStartRangeTime      string `json:"AdressValidityStartRangeTime"`
		AdressValidityStartRangeYear      string `json:"AdressValidityStartRangeYear"`
		AdressValidityStartRangeMonth     string `json:"AdressValidityStartRangeMonth"`
		AdressValidityStartRangeDay       string `json:"AdressValidityStartRangeDay"`
		AdressValidityStartRangeHours     string `json:"AdressValidityStartRangeHours"`
		AdressValidityStartRangeMinutes   string `json:"AdressValidityStartRangeMinutes"`
		AdressValidityStartRangeSeconds   string `json:"AdressValidityStartRangeSeconds"`
		AdressValidityStartRangeMills     string `json:"AdressValidityStartRangeMills"`
		AdressValidityStartRangeGmtOffset string `json:"AdressValidityStartRangeGmtOffset"`
		AdressValidityStartRangePrecision string `json:"AdressValidityStartRangePrecision"`
		AdressValidityEndRangeTime        string `json:"AdressValidityEndRangeTime"`
		AdressValidityEndRangeYear        string `json:"AdressValidityEndRangeYear"`
		AdressValidityEndRangeMonth       string `json:"AdressValidityEndRangeMonth"`
		AdressValidityEndRangeDay         string `json:"AdressValidityEndRangeDay"`
		AdressValidityEndRangeHours       string `json:"AdressValidityEndRangeHours"`
		AdressValidityEndRangeMinutes     string `json:"AdressValidityEndRangeMinutes"`
		AdressValidityEndRangeSeconds     string `json:"AdressValidityEndRangeSeconds"`
		AdressValidityEndRangeMills       string `json:"AdressValidityEndRangeMills"`
		AdressValidityEndRangeGmtOffset   string `json:"AdressValidityEndRangeGmtOffset"`
		AdressValidityEndRangePrecision   string `json:"AdressValidityEndRangePrecision"`
		AdressEffectiveTime               string `json:"AdressEffectiveTime"`
		AdressEffectiveYear               string `json:"AdressEffectiveYear"`
		AdressEffectiveMonth              string `json:"AdressEffectiveMonth"`
		AdressEffectiveDay                string `json:"AdressEffectiveDay"`
		AdressEffectiveHours              string `json:"AdressEffectiveHours"`
		AdressEffectiveMinutes            string `json:"AdressEffectiveMinutes"`
	} `json:"PIDPatientAddress"`
	PIDPatientAlias struct {
		Class                                              string `json:"$class"`
		PatientAliasFamilySurname                          string `json:"PatientAliasFamilySurname"`
		PatientAliasFamilyOwnSurnamePrefix                 string `json:"PatientAliasFamilyOwnSurnamePrefix"`
		PatientAliasFamilyOwnSurname                       string `json:"PatientAliasFamilyOwnSurname"`
		PatientAliasFamilySurnamePrefixFromPartner         string `json:"PatientAliasFamilySurnamePrefixFromPartner"`
		PatientAliasFamilySurnameFromPartner               string `json:"PatientAliasFamilySurnameFromPartner"`
		PatientAliasGivenName                              string `json:"PatientAliasGivenName"`
		PatientAliasMiddleInitialOrName                    string `json:"PatientAliasMiddleInitialOrName"`
		PatientAliasSuffix                                 string `json:"PatientAliasSuffix"`
		PatientAliasPrefix                                 string `json:"PatientAliasPrefix"`
		PatientAliasDegree                                 string `json:"PatientAliasDegree"`
		PatientAliasNameTypeCode                           string `json:"PatientAliasNameTypeCode"`
		PatientAliasNameRepresentationCode                 string `json:"PatientAliasNameRepresentationCode"`
		PatientAliasNameContextIdentifier                  string `json:"PatientAliasNameContextIdentifier"`
		PatientAliasNameContextText                        string `json:"PatientAliasNameContextText"`
		PatientAliasNameContextNameOfCodingSystem          string `json:"PatientAliasNameContextNameOfCodingSystem"`
		PatientAliasNameContextAlternateIdentifier         string `json:"PatientAliasNameContextAlternateIdentifier"`
		PatientAliasNameContextAlternateText               string `json:"PatientAliasNameContextAlternateText"`
		PatientAliasNameContextNameOfAlternateCodingSystem string `json:"PatientAliasNameContextNameOfAlternateCodingSystem"`
		PatientAliasValidityRangeStartTime                 string `json:"PatientAliasValidityRangeStartTime"`
		PatientAliasValidityRangeStartYear                 string `json:"PatientAliasValidityRangeStartYear"`
		PatientAliasValidityRangeStartMonth                string `json:"PatientAliasValidityRangeStartMonth"`
		PatientAliasValidityRangeStartDay                  string `json:"PatientAliasValidityRangeStartDay"`
		PatientAliasValidityRangeStartHours                string `json:"PatientAliasValidityRangeStartHours"`
		PatientAliasValidityRangeStartMinutes              string `json:"PatientAliasValidityRangeStartMinutes"`
		PatientAliasValidityRangeStartSeconds              string `json:"PatientAliasValidityRangeStartSeconds"`
		PatientAliasValidityRangeStartMills                string `json:"PatientAliasValidityRangeStartMills"`
		PatientAliasValidityRangeStartGmtOffset            string `json:"PatientAliasValidityRangeStartGmtOffset"`
		PatientAliasValidityRangeStartPrecision            string `json:"PatientAliasValidityRangeStartPrecision"`
		PatientAliasValidityRangeEndTime                   string `json:"PatientAliasValidityRangeEndTime"`
		PatientAliasValidityRangeEndYear                   string `json:"PatientAliasValidityRangeEndYear"`
		PatientAliasValidityRangeEndMonth                  string `json:"PatientAliasValidityRangeEndMonth"`
		PatientAliasValidityRangeEndDay                    string `json:"PatientAliasValidityRangeEndDay"`
		PatientAliasValidityRangeEndHours                  string `json:"PatientAliasValidityRangeEndHours"`
	} `json:"PIDPatientAlias"`
	PIDPatientID struct {
		Class                                                          string `json:"$class"`
		PatientListIDNumber                                            string `json:"PatientListIDNumber"`
		PatientListCheckDigit                                          string `json:"PatientListCheckDigit"`
		PatientListCheckDigitScheme                                    string `json:"PatientListCheckDigitScheme"`
		PatientListAANamespaceID                                       string `json:"PatientListAANamespaceID"`
		PatientListAAUniversalID                                       string `json:"PatientListAAUniversalID"`
		PatientListAAUniversalIDType                                   string `json:"PatientListAAUniversalIDType"`
		PatientListIdentifierTypeCode                                  string `json:"PatientListIdentifierTypeCode"`
		PatientListAFNamespaceID                                       string `json:"PatientListAFNamespaceID"`
		PatientListAFUniversalID                                       string `json:"PatientListAFUniversalID"`
		PatientListAFUniversalIDType                                   string `json:"PatientListAFUniversalIDType"`
		PatientListEffectiveTime                                       string `json:"PatientListEffectiveTime"`
		PatientListEffectiveYear                                       string `json:"PatientListEffectiveYear"`
		PatientListEffectiveMonth                                      string `json:"PatientListEffectiveMonth"`
		PatientListEffectiveDay                                        string `json:"PatientListEffectiveDay"`
		PatientListExpirationTime                                      string `json:"PatientListExpirationTime"`
		PatientListEXPIRATIONYear                                      string `json:"PatientListEXPIRATIONYear"`
		PatientListEXPIRATIONMonth                                     string `json:"PatientListEXPIRATIONMonth"`
		PatientListEXPIRATIONDay                                       string `json:"PatientListEXPIRATIONDay"`
		PatientListAssigningJurisdictionIdentifier                     string `json:"PatientListAssigningJurisdictionIdentifier"`
		PatientListAssigningJurisdictionText                           string `json:"PatientListAssigningJurisdictionText"`
		PatientListAssigningJurisdictionNameOfCodingSystem             string `json:"PatientListAssigningJurisdictionNameOfCodingSystem"`
		PatientListAssigningJurisdictionAlternateIdentifier            string `json:"PatientListAssigningJurisdictionAlternateIdentifier"`
		PatientListAssigningJurisdictionAlternateText                  string `json:"PatientListAssigningJurisdictionAlternateText"`
		PatientListAssigningJurisdictionNameOfAlternateCodingSystem    string `json:"PatientListAssigningJurisdictionNameOfAlternateCodingSystem"`
		PatientListAssigningJurisdictionCodingSystemVersionID          string `json:"PatientListAssigningJurisdictionCodingSystemVersionID"`
		PatientListAssigningJurisdictionAlternateCodingSystemVersionID string `json:"PatientListAssigningJurisdictionAlternateCodingSystemVersionID"`
		PatientListAssigningJurisdictionOriginalText                   string `json:"PatientListAssigningJurisdictionOriginalText"`
		PatientListAssigningAgencyorDepartmentIdentifier               string `json:"PatientListAssigningAgencyorDepartmentIdentifier"`
		PatientListAssigningAgencyorDepartmentText                     string `json:"PatientListAssigningAgencyorDepartmentText"`
		PatientListAssigningAgencyorDepartmentNameOfCodingSystem       string `json:"PatientListAssigningAgencyorDepartmentNameOfCodingSystem"`
		PatientListAssigningAgencyorDepartmentAlternateIdentifier      string `json:"PatientListAssigningAgencyorDepartmentAlternateIdentifier"`
	} `json:"PIDPatientId"`
	PIDPatientName struct {
		Class                                         string `json:"$class"`
		PatientFamilySurname                          string `json:"PatientFamilySurname"`
		PatientFamilyOwnSurnamePrefix                 string `json:"PatientFamilyOwnSurnamePrefix"`
		PatientFamilyOwnSurname                       string `json:"PatientFamilyOwnSurname"`
		PatientFamilySurnamePrefixFromPartner         string `json:"PatientFamilySurnamePrefixFromPartner"`
		PatientFamilySurnameFromPartnerSpouse         string `json:"PatientFamilySurnameFromPartnerSpouse"`
		PatientGivenName                              string `json:"PatientGivenName"`
		PatientMiddleInitialOrName                    string `json:"PatientMiddleInitialOrName"`
		PatientSuffix                                 string `json:"PatientSuffix"`
		PatientPrefix                                 string `json:"PatientPrefix"`
		PatientDegree                                 string `json:"PatientDegree"`
		PatientNameTypeCode                           string `json:"PatientNameTypeCode"`
		PatientNameRepresentationCode                 string `json:"PatientNameRepresentationCode"`
		PatientNameContextIdentifier                  string `json:"PatientNameContextIdentifier"`
		PatientNameContextText                        string `json:"PatientNameContextText"`
		PatientNameContextNameOfCodingSystem          string `json:"PatientNameContextNameOfCodingSystem"`
		PatientNameContextAlternateIdentifier         string `json:"PatientNameContextAlternateIdentifier"`
		PatientNameContextAlternateText               string `json:"PatientNameContextAlternateText"`
		PatientNameContextNameOfAlternateCodingSystem string `json:"PatientNameContextNameOfAlternateCodingSystem"`
		PatientNameValidityStartRangeTime             string `json:"PatientNameValidityStartRangeTime"`
		PatientNameValidityStartRangeYear             string `json:"PatientNameValidityStartRangeYear"`
		PatientNameValidityStartRangeMonth            string `json:"PatientNameValidityStartRangeMonth"`
		PatientNameValidityStartRangeDay              string `json:"PatientNameValidityStartRangeDay"`
		PatientNameValidityStartRangeHours            string `json:"PatientNameValidityStartRangeHours"`
		PatientNameValidityStartRangeMinutes          string `json:"PatientNameValidityStartRangeMinutes"`
		PatientNameValidityStartRangeSeconds          string `json:"PatientNameValidityStartRangeSeconds"`
		PatientNameValidityStartRangeMills            string `json:"PatientNameValidityStartRangeMills"`
		PatientNameValidityStartRangeGmtOffset        string `json:"PatientNameValidityStartRangeGmtOffset"`
		PatientNameValidityStartRangePrecision        string `json:"PatientNameValidityStartRangePrecision"`
		PatientNameValidityEndRangeTime               string `json:"PatientNameValidityEndRangeTime"`
		PatientNameValidityEndRangeYear               string `json:"PatientNameValidityEndRangeYear"`
		PatientNameValidityEndRangeMonth              string `json:"PatientNameValidityEndRangeMonth"`
		PatientNameValidityEndRangeDay                string `json:"PatientNameValidityEndRangeDay"`
		PatientNameValidityEndRangeHours              string `json:"PatientNameValidityEndRangeHours"`
		PatientNameValidityEndRangeMinutes            string `json:"PatientNameValidityEndRangeMinutes"`
		PatientNameValidityEndRangeSeconds            string `json:"PatientNameValidityEndRangeSeconds"`
	} `json:"PIDPatientName"`
	PIDRace struct {
		Class                           string `json:"$class"`
		RaceIdentifier                  string `json:"RaceIdentifier"`
		RaceText                        string `json:"RaceText"`
		RaceNameOfCodingSystem          string `json:"RaceNameOfCodingSystem"`
		RaceAlternateIdentifier         string `json:"RaceAlternateIdentifier"`
		RaceAlternateText               string `json:"RaceAlternateText"`
		RaceNameOfAlternateCodingSystem string `json:"RaceNameOfAlternateCodingSystem"`
		Race                            string `json:"Race"`
	} `json:"PIDRace"`
	PIDProductionClass struct {
		Class                                          string `json:"$class"`
		ProductionClassCodeIdentifier                  string `json:"ProductionClassCodeIdentifier"`
		ProductionClassCodeText                        string `json:"ProductionClassCodeText"`
		ProductionClassCodeNameOfCodingSystem          string `json:"ProductionClassCodeNameOfCodingSystem"`
		ProductionClassCodeAlternateIdentifier         string `json:"ProductionClassCodeAlternateIdentifier"`
		ProductionClassCodeAlternateText               string `json:"ProductionClassCodeAlternateText"`
		ProductionClassCodeNameOfAlternateCodingSystem string `json:"ProductionClassCodeNameOfAlternateCodingSystem"`
	} `json:"PIDProductionClass"`
	PIDTribalCitizenship struct {
		Class                                           string `json:"$class"`
		TribalCitizenshipIdentifier                     string `json:"TribalCitizenshipIdentifier"`
		TribalCitizenshipText                           string `json:"TribalCitizenshipText"`
		TribalCitizenshipNameOfCodingSystem             string `json:"TribalCitizenshipNameOfCodingSystem"`
		TribalCitizenshipAlternateIdentifier            string `json:"TribalCitizenshipAlternateIdentifier"`
		TribalCitizenshipAlternateText                  string `json:"TribalCitizenshipAlternateText"`
		TribalCitizenshipNameOfAlternateCodingSystem    string `json:"TribalCitizenshipNameOfAlternateCodingSystem"`
		TribalCitizenshipCodingSystemVersionID          string `json:"TribalCitizenshipCodingSystemVersionID"`
		TribalCitizenshipAlternateCodingSystemVersionID string `json:"TribalCitizenshipAlternateCodingSystemVersionID"`
		TribalCitizenshipOriginalText                   string `json:"TribalCitizenshipOriginalText"`
	} `json:"PIDTribalCitizenship"`
}

func (mo *Hl7PidFormat) fnAddPid(ctx contractapi.TransactionContextInterface) error {

	err := FnValidationCheckStruct(mo)
	if err != nil {
		return err
	}
	mo.MSHPID = mo.MSHKEY + "_" + "PID"
	fmt.Println(mo.MSHPID, "pid key value")
	pidBytes, err := ctx.GetStub().GetState(mo.MSHPID)
	if pidBytes != nil || err != nil {
		return fmt.Errorf("Key Already Exists in the Network")
	}
	pidBytes, _ = json.Marshal(mo)
	return ctx.GetStub().PutState(mo.MSHPID, pidBytes)
}
